#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <unistd.h>
#include <stdarg.h>
#ifdef CONFIG_LP
#include "lp_version.h"
#endif

#define OPTCHARS 		"dhc:l:t:"
#define DEFAULT_PARSE_PATH	"./STRINGS_ZH.txt"
#define DEFAULT_TARGET_PATH	"./"
#define BUFFER_SIZE		2048
int debug_flag = 0;

int init_file(char *file)
{
        FILE *fp;

        if ((fp = fopen(file ,"w")) == NULL) {
                printf("Can't open %s\n", file);
                exit(1);
        }

        fclose(fp);
        return 0;
}

void save2file(const char *file, const char *fmt, ...)
{
        char buf[10240];
        va_list args;
        FILE *fp;

        if ((fp = fopen(file ,"a")) == NULL) {
                printf("Can't open %s\n", file);
                exit(1);
        }

        va_start(args, fmt);
        vsnprintf(buf, sizeof(buf), fmt, args);
        va_end(args);
        va_start(args, fmt);
        fprintf(fp, "%s", buf);
        va_end(args);

        fclose(fp);
}

void help_info(void)
{
	printf("m17n_tool [options]\n");
	printf("[options]:\n");
	printf("	-d		Enable debug message\n");
	printf("        -c file_name    Select a file to parse.The file must generated by Ubicom.Default is STRINGS_ZH.txt\n");
	printf("  	-l language	Select a language to create,only support TW,JA,GE,GR,KO and EN now.Default is EN.\n");
	printf("	-t target_path	Select target path\n");
	printf("        -h		Help message\n");
}

int _system(const char *fmt, ...)
{
        va_list args;
        int i;
        char buf[512];

        va_start(args, fmt);
        i = vsprintf(buf, fmt,args);
        va_end(args);

        printf("%s\n",buf);
        system(buf);
        return i;

}
void recover_quot_sed(char *filename){
//equal to the command:  sed -i 's/\\\\\"/\\\"/g' filename
	_system("sed -i 's/\\\\\\\\\\\"/\\\\\\\"/g' %s", filename);
}

void mapping_page_sed(char *filename){
	int i=0;
	typedef struct{
		char *orig;
		char *mapped;
	}map_string;
#define MAP_PAGE_NUM	19
	map_string map_array[MAP_PAGE_NUM]={};
	map_array[i].orig="..\\/Tools\\/EMail.shtml";	map_array[i++].mapped="tools_email.asp";
	map_array[i].orig="..\\/Help\\/Tools.shtml";	map_array[i++].mapped="support_tools.asp";
	map_array[i].orig="..\\/Tools\\/Schedules.shtml";    map_array[i++].mapped="tools_schedules.asp";
	map_array[i].orig="..\\/Help\\/Basic.shtml";    map_array[i++].mapped="support_internet.asp";
	map_array[i].orig="..\\/Advanced\\/Inbound_Filter.shtml";    map_array[i++].mapped="Inbound_Filter.asp";
	map_array[i].orig="..\\/Advanced\\/Virtual_Server.shtml";    map_array[i++].mapped="adv_virtual.asp";
	map_array[i].orig="..\\/Advanced\\/Web_Filter.shtml";    map_array[i++].mapped="adv_filters_url.asp";
	map_array[i].orig="..\\/Basic\\/Network.shtml";    map_array[i++].mapped="lan.asp";
	map_array[i].orig="..\\/Tools\\/System.shtml";    map_array[i++].mapped="tools_system.asp";
	map_array[i].orig="..\\/Help\\/Advanced.shtml";    map_array[i++].mapped="support_adv.asp";
	map_array[i].orig="..\\/Basic\\/Wireless.shtml";    map_array[i++].mapped="wireless.asp";
	map_array[i].orig="..\\/Advanced\\/Advanced_Wireless.shtml";    map_array[i++].mapped="adv_wlan_perform.asp";
	map_array[i].orig="..\\/Advanced\\/WISH.shtml";    map_array[i++].mapped="adv_wish.asp";
	map_array[i].orig="..\\/Advanced\\/Protected_Setup.shtml";    map_array[i++].mapped="wireless.asp";
	map_array[i].orig="..\\/Advanced\\/Gaming.shtml";	map_array[i++].mapped="adv_portforward.asp";
	map_array[i].orig="..\\/Advanced\\/Special_Applications.shtml";map_array[i++].mapped="adv_appl.asp";
	map_array[i].orig="..\\/Advanced\\/Network.shtml";map_array[i++].mapped="adv_network.asp";
	map_array[i].orig="..\\/Basic\\/Wizard_WLAN.shtml";map_array[i++].mapped="wizard_wlan.asp";
	map_array[i].orig="..\\/Advanced\\/Access_Control.shtml";map_array[i++].mapped="adv_access_control.asp";
//	map_array[i].orig="";map_array[i++].mapped="";

	for (i=0;i<MAP_PAGE_NUM;i++){
	_system("sed -i \"s/%s/%s/g\" %s",map_array[i].orig,map_array[i].mapped,filename);
	}
        return;
}

void copyright_date_sed(char *filename){
_system("sed -i '/_copyright/s/2004-2006/2004-'$(date +%Y)'/' %s", filename);	
}

// Naming rule for .js
void transfer_parameter_name(char *parameter_name)
{
	char *ptr_first,*ptr;
	char temp[128] = {};
	int i;

	if(parameter_name[0] == '.')
	{
		if(ptr_first = strtok(parameter_name,"."))
		{
			strcat(temp,"_");
			strcat(temp,ptr_first);
                        strcat(temp,"_");
			while(ptr = strtok(NULL,".")){
				strcat(temp,ptr);
                strcat(temp,"_");
			}
        }
	}
	else
	{
		if(isdigit(parameter_name[0]))
  		{
                	strcat(temp,"num_");
                	strcat(temp,parameter_name);
                	memset(parameter_name,0,sizeof(parameter_name));
                	strcpy(parameter_name,temp);
                	memset(temp,0,sizeof(temp));
		}

		if(ptr_first = strtok(parameter_name,"."))
		{
			strcat(temp,ptr_first);
			strcat(temp,"_");
			while(ptr = strtok(NULL,"."))
			{
				strcat(temp,ptr);
				strcat(temp,"_");

			}
		}
	}

	if(strstr(temp,"?") || strstr(temp,"-"))
	{
		for(i=0;i<strlen(temp);i++)
		{
			if(temp[i] == '?' || temp[i] == '-')
				break;
		}
		temp[i] = '_';
	}
	memset(parameter_name,0,sizeof(parameter_name));
	strncpy(parameter_name,temp,strlen(temp) - 1);
		
}

char *check_format(char *value)
{
	char temp[BUFFER_SIZE] = {};
	char buffer[BUFFER_SIZE] = {};
	char *ptr_first,*ptr;
	int count = 0, i, check_flag = 0;
	strcpy(buffer,value);
	if(value[0] == '"')
		strcat(temp,"\\\"");
	if(value[strlen(value) - 1] == '"')
	{
		count++;
		check_flag = 1;
	}
	if(ptr_first = strtok(buffer,"\""))
	{
		while(ptr = strtok(NULL,"\""))
			count++;
	}
	if(debug_flag)
		printf("count = %d\n",count);

	if((ptr_first = strtok(value,"\"")) && count != 0)
        {
		strcat(temp,ptr_first);
		
		strcat(temp,"\\\"");
		for(i = 0;i < count;i++)
                {
			ptr = strtok(NULL,"\"");
			if(ptr)	
				strcat(temp,ptr);
			
			if(i < count - 1)
                        	strcat(temp,"\\\"");
                }
		if(debug_flag)
			printf("check_format = %s\n",temp);
		memset(value,0,sizeof(value));
                strncpy(value,temp,strlen(temp));
	}
	return value;
}

int main(int argc, char *argv[])
{
	char *head, *tail, *en_string, *transfer_string;
	int ret, en_flag = 0;
	char file_path[128] = {}, target_path[128]={}, buf[BUFFER_SIZE] = {}, parameter_name[128] = {}, create_js_file_name[32] = {};
	FILE *fp_parse;
	strcpy(file_path,DEFAULT_PARSE_PATH);
	strcpy(target_path,DEFAULT_TARGET_PATH);
	while ((ret = getopt(argc, argv, OPTCHARS)) != EOF)
	{
		switch (ret) 
		{
			case 'd':
				debug_flag = 1;
				break;
			case 'c':
				memset(file_path,0,sizeof(file_path));
				strcpy(file_path,optarg);	
				break;
			case 'l':
				memset(create_js_file_name,0,sizeof(create_js_file_name));
				if(strcmp(optarg,"TW") != 0 && strcmp(optarg,"JA") != 0 && strcmp(optarg,"EN") != 0 &&
				   strcmp(optarg,"DE") != 0 && strcmp(optarg,"ES") != 0 && strcmp(optarg,"KO") != 0 &&
				   strcmp(optarg,"CN") != 0 && strcmp(optarg,"FR") != 0 && strcmp(optarg,"IT") != 0)
				{
					printf("Not supported language.Only support TW, CN, JA, EN, DE, ES, FR, IT and KO.\n");
					return -1;
				}
				else
				{
					sprintf(create_js_file_name,"lingual_%s.js",optarg);
					if(strcmp(optarg,"EN") == 0)
						en_flag = 1;
				}
				init_file(create_js_file_name);		
				break;
			case 't':
				memset(target_path,0,sizeof(target_path));
				strcpy(target_path,optarg);
				break;
			case 'h':
				help_info();
				break;
			default:
				printf("Not support option\n");
				return -1;
		}
	}
	if(strlen(create_js_file_name)<=0){
		printf("you must select a language. use -l\n");
		return -1;
	}
	if(debug_flag)	
		printf("debug_flag = %d file_path = %s\n",debug_flag,file_path);
		
	fp_parse = fopen(file_path,"r");
#ifdef CONFIG_LP	
	save2file(create_js_file_name,"/*LP_VER: %s_%s*/\n","DIR-652","1.0");
#endif
	if(fp_parse)
	{
		while(fgets(buf,BUFFER_SIZE,fp_parse))
		{
			if(head = strstr(buf,"#From:"))
			{
				head = head + 6;
				if(tail = strstr(head,","))
				{
					en_string = tail + 1;
					if(debug_flag)
						printf("en_string = %s\n",en_string);
					if(head[0] == ' ')
						head++;
					strncpy(parameter_name,head,tail - head);
					transfer_parameter_name(parameter_name);
					if(debug_flag)
				                printf("parameter_name = %s\n",parameter_name);			
					save2file(create_js_file_name,"var %s =",parameter_name);
					if(en_flag)
					{
						en_string[strlen(en_string) - 1] = '\0';
						save2file(create_js_file_name,"\"%s\";\n",check_format(en_string));
					}
						
				}
				
			}
			else
			{
				if(!en_flag)
				{
					if(head = strstr(buf,","))
					{
						transfer_string = head + 1;
						transfer_string[strlen(transfer_string) - 1] = '\0';
						if(debug_flag)
							printf("transfer_string = %s\n",transfer_string);
						save2file(create_js_file_name,"\"%s\";\n",check_format(transfer_string));
					}
				}
			}
			
			memset(parameter_name,0,sizeof(parameter_name));
			memset(buf,0,sizeof(buf));
		}
		fclose(fp_parse);
	}
	else
		printf("parse file does not exist\n");
	printf("mapping_page in file:%s\n",create_js_file_name);
	mapping_page_sed(create_js_file_name);
	recover_quot_sed(create_js_file_name);
	copyright_date_sed(create_js_file_name);
	_system("cp -f %s %s",create_js_file_name,target_path);
	return 0;
}
