#! /bin/sh
PROJECTS_PATH=$1
LP_VER=$2_$3
PROJECTS_IMAGE_PATH=$PROJECTS_PATH/image
FILE_NAME=$2_LP_$4_$3
LP_JS=$5
REG=$4

if [ ! -d $PROJECTS_IMAGE_PATH ]
then
	mkdir $PROJECTS_IMAGE_PATH
	chmod 644 $PROJECTS_IMAGE_PATH
fi

rm -f $PROJECTS_IMAGE_PATH/$FILE_NAME
rm -f $PROJECTS_IMAGE_PATH/$FILE_NAME.bin
#../mksquashfs $PROJECTS_PATH/$LP_JS $PROJECTS_IMAGE_PATH/$FILE_NAME -be
zip lang_fr.zip lang_fr.js
mv lang_fr.zip $FILE_NAME
chmod 644 $PROJECTS_IMAGE_PATH/$FILE_NAME
dd if=$PROJECTS_IMAGE_PATH/$FILE_NAME of=$PROJECTS_IMAGE_PATH/$FILE_NAME.bin bs=1k conv=sync
echo -n $LP_VER$REG >> $PROJECTS_IMAGE_PATH/$FILE_NAME.bin
