#include <stdlib.h>
#include <string.h>
#include <stdio.h>
#include <sys/types.h>
#include <sys/klog.h>
#include <stdlib.h>
#include <unistd.h>
#include <search.h>
#include <assert.h>

#include "libdb.h"
#include "ssc.h"
#include "public.h"
#include "querys.h"
#include "netinf.h"
#include "debug.h"
#include "update_log_table.h"
#include "shvar.h"


void return_log_current_page(int argc, char *argv[]){
        printf("%d", atoi(nvram_get("log_current_page")));
}

void return_log_total_page(int argc, char *argv[]){
        printf("%d",atoi(nvram_get("log_total_page")));
}


int show_page(int argc, char *argv[])
{

	char cmd[128]={0};	
	int remainder,total_logs,cur_page,total_page;
	int i, j, log_system_activity, log_debug_information, log_attacks, log_dropped_packets, log_notice;
        int per_page, quotient, flag_quotient_equal_0;
        flag_quotient_equal_0 = 0;
	log_system_activity = atoi(nvram_get("log_system_activity"));
        log_debug_information = atoi(nvram_get("log_debug_information"));
        log_attacks = atoi(nvram_get("log_attacks"));
        log_dropped_packets = atoi(nvram_get("log_dropped_packets"));
        log_notice = atoi(nvram_get("log_notice"));
        total_logs = update_log_table(log_system_activity, log_debug_information, log_attacks, log_dropped_packets, log_notice);
	cprintf("%s(%d)\n", __func__, __LINE__);
	per_page = atoi(nvram_safe_get("log_per_page") != NULL ? nvram_safe_get("log_per_page") : "0");
	cur_page = atoi(nvram_safe_get("log_current_page") != NULL ? nvram_safe_get("log_current_page") : "0");
	total_page = atoi(nvram_safe_get("log_total_page") != NULL ? nvram_safe_get("log_total_page") : "0");
	
        if(per_page <= 0)
                per_page = 10;

        quotient = total_logs / per_page;
        remainder = total_logs % per_page;

        if (quotient == 0)
                flag_quotient_equal_0 = 1;

        if(remainder != 0)
                quotient += 1;

        if(quotient != 0)
                total_page = quotient;
        else
                total_page = 1;

        if(cur_page == 0)
                cur_page = 1;

        if(cur_page > total_page)
                cur_page = 1;


        if(cur_page == 1){    //current page is the first page
                for(i = 0 ; i < per_page && i < total_logs ; i++){
                        printf("|syslog|%s|%s|%s ",
                                                log_dynamic_table[i].time,
                                                log_dynamic_table[i].type,
                                                log_dynamic_table[i].message);
		}
	 }else if(cur_page == -1){     //clear all log messages

                cur_page = 1;
                total_page = 1;
        /* Note:
  		the code below is copy from rc/app.c, start_syslogd()
  		The codes below and in start_syslogd() must be identically !!
       */
                char *nvram_syslog_server = NULL, *syslog_enable = NULL, *syslog_ip = NULL;
                char tmp_syslog_server[20]={0};
                nvram_syslog_server = nvram_safe_get("syslog_server");
                strcpy(tmp_syslog_server, nvram_syslog_server);
                system("killall syslogd klogd");
                /* jimmy added , remove the file generated by syslogd */
                unlink("/var/log/message_die_bak");
                /* --------------------------------------- */

                if( strlen(nvram_syslog_server) ){
                    syslog_enable = strtok(tmp_syslog_server, "/");
                    syslog_ip = strtok(NULL, "/");

                    if(syslog_enable == NULL || syslog_ip == NULL){
                      	printf("start_syslogd: syslog_server error\n");
			sprintf(cmd,"syslogd -C %d -b 0 &", LOG_MAX_SIZE);
                    }else{
                            if( strcmp(syslog_enable, "1") == 0 ) 
				sprintf(cmd,"syslogd -C %d -L -R %s:514 &", LOG_MAX_SIZE, syslog_ip);
                            else 
				sprintf(cmd,"syslogd -C %d &", LOG_MAX_SIZE);	
			    
                        }
                }else{
			sprintf(cmd,"syslogd -C %d -b 0 &", LOG_MAX_SIZE);
                }
		system(cmd);
                system("klogd &");
                syslog(LOG_INFO, "Log cleared by Administrator");
                cprintf("log clear page\n");
        }else{
                j = 0;
	 	for(i = (cur_page - 1) * per_page ; (j < per_page) && (i < total_logs) ; i++ , j++){
                        printf("|syslog|%s|%s|%s ",
                                        log_dynamic_table[i].time,
                                        log_dynamic_table[i].type,
                                        log_dynamic_table[i].message);
                }
        }
	
	memset(cmd,'\0',128);
	sprintf(cmd,"nvram set log_current_page=\"%d\";nvram set log_per_page=\"%d\";nvram set log_total_page=\"%d\""
		,cur_page,per_page,total_page);
	sprintf(cmd, "%d", cur_page);
	nvram_set("log_current_page", cmd);
	sprintf(cmd, "%d", per_page);
	nvram_set("log_per_page", cmd);
	sprintf(cmd, "%d", total_page);
	nvram_set("log_total_page", cmd);
	return 0;
}


static int misc_log_help(struct __log_struct *p)
{
        cprintf("Usage:\n");

        for (; p && p->param; p++)
                cprintf("\t%s: %s\n", p->param, p->desc);

        cprintf("\n");
        return 0;
}

int get_log_page_main(int argc, char *argv[])
{
        int ret = -1;
        struct __log_struct *p, list[] = {
                { "page", "Show the page", show_page},
		{ "log_current_page","Show current page",return_log_current_page},
		{ "log_total_page","Show total page",return_log_total_page},
                { NULL, NULL, NULL }
        };

        if (argc == 1 || strcmp(argv[1], "help") == 0)
                        goto help;

        for (p = list; p && p->param; p++) {
                if (strcmp(argv[1], p->param) == 0) {
                        ret = p->fn(argc - 1, argv + 1);
                        goto out;
                }
        }

help:
        ret = misc_log_help(list);
out:
        return ret;

}

