
static struct items vpn_ipsec[] = {
	{ "vpn_nat_traversal", NULL },
	{ "vpn_conn1", ""},
	{ "vpn_conn2", ""},
	{ "vpn_conn3", ""},
	{ "vpn_conn4", ""},
	{ "vpn_conn5", ""},
	{ "vpn_conn6", ""},
	{ "vpn_conn7", ""},
	{ "vpn_conn8", ""},
	{ "vpn_conn9", ""},
	{ "vpn_conn10", ""},
	{ "vpn_conn11", ""},
	{ "vpn_conn12", ""},
	{ "vpn_conn13", ""},
	{ "vpn_conn14", ""},
	{ "vpn_conn15", ""},
	{ "vpn_conn16", ""},
	{ "vpn_conn17", ""},
	{ "vpn_conn18", ""},
	{ "vpn_conn19", ""},
	{ "vpn_conn20", ""},
	{ "vpn_conn21", ""},
	{ "vpn_conn22", ""},
	{ "vpn_conn23", ""},
	{ "vpn_conn24", ""},
	{ "vpn_conn25", ""},
	{ "vpn_extra1", ""},
	{ "vpn_extra2", ""},
	{ "vpn_extra3", ""},
	{ "vpn_extra4", ""},
	{ "vpn_extra5", ""},
	{ "vpn_extra6", ""},
	{ "vpn_extra7", ""},
	{ "vpn_extra8", ""},
	{ "vpn_extra9", ""},
	{ "vpn_extra10", ""},
	{ "vpn_extra11", ""},
	{ "vpn_extra12", ""},
	{ "vpn_extra13", ""},
	{ "vpn_extra14", ""},
	{ "vpn_extra15", ""},
	{ "vpn_extra16", ""},
	{ "vpn_extra17", ""},
	{ "vpn_extra18", ""},
	{ "vpn_extra19", ""},
	{ "vpn_extra20", ""},
	{ "vpn_extra21", ""},
	{ "vpn_extra22", ""},
	{ "vpn_extra23", ""},
	{ "vpn_extra24", ""},
	{ "vpn_extra25", ""},
	{ NULL, NULL},
};

static struct items vpn_pptp[] = {
	{ "l2tpd_overipsec_enable", ""},
	{ "pptpd_enable", ""},
	{ "pptpd_servername", ""},
	{ "pptpd_local_ip", ""},
	{ "pptpd_remote_ip", ""},
	{ "pptpd_auth_proto", ""},
	{ "pptpd_encryption", ""},
	{ "pptpd_auth_source", ""},
	{ "l2tpd_enable", ""},
	{ "l2tpd_servername", ""},
	{ "l2tpd_local_ip", ""},
	{ "l2tpd_remote_ip", ""},
	{ "l2tpd_auth_proto", ""},
	{ "l2tpd_auth_source", ""},
	{ "auth_pptpd_l2tpd", ""},
	{ "edit_vpn", ""},
	{ "edit_type", ""},
	{ "pptpd_conn_1", ""},
	{ "pptpd_conn_2", ""},
	{ "pptpd_conn_3", ""},
	{ "pptpd_conn_4", ""},
	{ "pptpd_conn_5", ""},
	{ "pptpd_conn_6", ""},
	{ "pptpd_conn_7", ""},
	{ "pptpd_conn_8", ""},
	{ "pptpd_conn_9", ""},
	{ "pptpd_conn_10", ""},
	{ "pptpd_conn_11", ""},
	{ "pptpd_conn_12", ""},
	{ "pptpd_conn_13", ""},
	{ "pptpd_conn_14", ""},
	{ "pptpd_conn_15", ""},
	{ "pptpd_conn_16", ""},
	{ "pptpd_conn_17", ""},
	{ "pptpd_conn_18", ""},
	{ "pptpd_conn_19", ""},
	{ "pptpd_conn_20", ""},
	{ "pptpd_conn_21", ""},
	{ "pptpd_conn_22", ""},
	{ "pptpd_conn_23", ""},
	{ "pptpd_conn_24", ""},
	{ "pptpd_conn_25", ""},
	{ "l2tpd_conn_1", ""},
	{ "l2tpd_conn_2", ""},
	{ "l2tpd_conn_3", ""},
	{ "l2tpd_conn_4", ""},
	{ "l2tpd_conn_5", ""},
	{ "l2tpd_conn_6", ""},
	{ "l2tpd_conn_7", ""},
	{ "l2tpd_conn_8", ""},
	{ "l2tpd_conn_9", ""},
	{ "l2tpd_conn_10", ""},
	{ "l2tpd_conn_11", ""},
	{ "l2tpd_conn_12", ""},
	{ "l2tpd_conn_13", ""},
	{ "l2tpd_conn_14", ""},
	{ "l2tpd_conn_15", ""},
	{ "l2tpd_conn_16", ""},
	{ "l2tpd_conn_17", ""},
	{ "l2tpd_conn_18", ""},
	{ "l2tpd_conn_19", ""},
	{ "l2tpd_conn_20", ""},
	{ "l2tpd_conn_21", ""},
	{ "l2tpd_conn_22", ""},
	{ "l2tpd_conn_23", ""},
	{ "l2tpd_conn_24", ""},
	{ "l2tpd_conn_25", ""},
	{ "vpn_conn26", ""},
	{ "vpn_extra26", ""},
	/* for phase_1 130 1.5 version */
	{ "username1", ""},
	{ "passwd1", ""},
	{ "username2", ""},
	{ "passwd2", ""},
	{ "username3", ""},
	{ "passwd3", ""},
	{ NULL, NULL}
};

static struct items vpn_ssl[] = {
	{ "https_pem", ""},
	{ "sslvpn1", ""},
	{ "sslvpn2", ""},
	{ "sslvpn3", ""},
	{ "sslvpn4", ""},
	{ "sslvpn5", ""},
	{ "sslvpn6", ""},
	{ "sslvpn_remote_ipaddr", "*"},
	{ "sslonly", "0"},
	{ NULL, NULL},
};

static struct items wizard_vpn[] = {
	{ "vpn_type", "" },
	{ "vpn_ipsec", "" },
	{ "vpn_pptp", "" },
	{ "vpn_l2tp", "" },
	{ "vpn_ssl", "" },
	{ "vpn_ssl_ca", "" },
	{ NULL, NULL }
};
