#!/bin/sh

. /etc/wireless_config

case "$1" in
start)	
	if [ -f /bin/dhcpcd ]; then
		echo "Running DHCP client for WLAN ($WLANINTERFACE) interface"
		dhcpcd $WLANINTERFACE &
	else 
		echo "DHCP client application does not exist!"
	fi

	while [ 1 ]; do
		sleep 10
		eth=`ifconfig | grep $WLANINTERFACE`
		if [ "$eth" != "" ]; then
			NEWWLANIP=`ifconfig $WLANINTERFACE | grep 'inet addr' | cut -f2 -d':' | cut -f1 -d' '`
			if [ "$NEWWLANIP" != "" ]; then
				NEWWLANMASK=`ifconfig $WLANINTERFACE | grep 'Mask' | cut -f4 -d':'`
				NEWWLANGW=`cat /etc/config/dhcpcd-$WLANINTERFACE.info | grep GATEWAY  | awk -F'=' '{print $2}'`
				sed -i '/^DHCPWLANIP=/ c\DHCPWLANIP='$NEWWLANIP'' /etc/wireless_config
				sed -i '/^DHCPWLANMASK=/ c\DHCPWLANMASK='$NEWWLANMASK'' /etc/wireless_config
				sed -i '/^DHCPGATEWAY=/ c\DHCPGATEWAY='$NEWWLANGW'' /etc/wireless_config
				
				# dhcpcd app writes DNS server addresses to /etc/resolv.conf. Copy them to /etc/wireless_config
				# Do not change identation of following operations!
				NEWDNS1=`cat /etc/resolv.conf | grep nameserver | cut -c 12-30 | cut -f1 -d'
'`
				NEWDNS2=`cat /etc/resolv.conf | grep nameserver | cut -c 12-30 | cut -f2 -d'
'`
				NEWDNS3=`cat /etc/resolv.conf | grep nameserver | cut -c 12-30 | cut -f3 -d'
'`
				sed -i '/^DHCPDNS1=/ c\DHCPDNS1='$NEWDNS1'' /etc/wireless_config
				sed -i '/^DHCPDNS2=/ c\DHCPDNS2='$NEWDNS2'' /etc/wireless_config
				sed -i '/^DHCPDNS3=/ c\DHCPDNS3='$NEWDNS3'' /etc/wireless_config

				# For dnsmasq to get DNS addresses, create a link to resolv.conf. 
				# Dnsmasq searchs for /etc/config/config/resolv.conf.
				if [ ! -f /etc/config/config/resolv.conf ]; then 
					ln -s /etc/resolv.conf /etc/config/config/resolv.conf
				fi
				echo "WLAN ($WLANINTERFACE) IP address given by DHCP Server: $NEWWLANIP"
				exit 0
			else
				# Try again! Firstly kill existing dhcpcd processes, if any.
				dhcpcd_pidlist=`ps | grep 'dhcpcd' | grep -v 'grep' | cut -b1-5`
				if [ "$dhcpcd_pidlist" != "" ]; then
					echo "Could not get IP from a DHCP server yet."
					echo "Restart dhcpcd and try again..."
					for i in $dhcpcd_pidlist
					do
						kill -9 $i
					done
				fi
				dhcpcd $WLANINTERFACE &
			fi
		fi
	done
        ;;
stop)	
	dhcpcd_pidlist=`ps | grep 'dhcpcd' | grep -v 'grep' | cut -b1-5`
	if [ "$dhcpcd_pidlist" != "" ]; then
		echo "Killing existing dhcpcd processes"
		for i in $dhcpcd_pidlist
		do
			kill -9 $i
		done
	fi
	
	rm /etc/config/dhcpcd-$WLANINTERFACE*
	
	sed -i '/^DHCPWLANIP=/ c\DHCPWLANIP=''' /etc/wireless_config
	sed -i '/^DHCPWLANMASK=/ c\DHCPWLANMASK=''' /etc/wireless_config
	sed -i '/^DHCPGATEWAY=/ c\DHCPGATEWAY=''' /etc/wireless_config
	
	sed -i '/^DHCPDNS1=/ c\DHCPDNS1=''' /etc/wireless_config
	sed -i '/^DHCPDNS2=/ c\DHCPDNS2=''' /etc/wireless_config
	sed -i '/^DHCPDNS3=/ c\DHCPDNS3=''' /etc/wireless_config
esac
exit 0
