#OBJS=services_cmds.o dhcpd.o ntp.o syslogd.o \
	klogd.o upnp.o igmp.o ddns.o httpd.o https.o \
	policy_route.o route.o settime.o dnsmasq.o tftpd.o \
	usb.o qos.o webfilter.o ips.o

OBJS=services_cmds.o https.o dhcprelay.o
include ../Rules.make
