#!/bin/sh
#
# This script is run by the pppd after the link is down.
#
# This script is called with the following arguments:
#    Arg  Name                          Example
#    $1   Interface name                ppp0
#    $2   The tty                       ttyS1
#    $3   The link speed                38400
#    $4   Local IP number               12.34.56.78
#    $5   Peer  IP number               12.34.56.99
#    $6   Optional ``ipparam'' value    foo

# These variables are for the use of the scripts run by run-parts
PPP_IFACE="$1"
PPP_TTY="$2"
PPP_SPEED="$3"
PPP_LOCAL="$4"
PPP_REMOTE="$5"
PPP_IPPARAM="$6"

sed -i '/^PPPDNS1=/ c\PPPDNS1=''' /etc/rgw_config
sed -i '/^PPPDNS2=/ c\PPPDNS2=''' /etc/rgw_config
sed -i '/^PPPDNS3=/ c\PPPDNS3=''' /etc/rgw_config
sed -i '/^PPPLOCALIP=/ c\PPPLOCALIP=''' /etc/rgw_config
sed -i '/^PPPREMOTEIP=/ c\PPPREMOTEIP=''' /etc/rgw_config
sed -i '/^PPPINTERFACE=/ c\PPPINTERFACE='"Down"'' /etc/rgw_config
sed -i '/^WAN_MODE_INTERFACE=/ c\WAN_MODE_INTERFACE=''' /etc/rgw_config

# Delete the default route.
route del default

if [ -f /etc/config/config/resolv.conf ]; then 
	rm /etc/config/config/resolv.conf
fi
