#!/bin/sh
#
# Grab current version number from configure.in and emit on stdout
#
# $Id: version,v 1.1 2008/05/02 10:09:55 jimmy_huang Exp $

VER=`grep AM_INIT_AUTOMAKE configure.in | awk -F'[(),]' '{print $3}'`

if [ "$1" == "-VERSION" ]
then
  echo $VER | awk -F'.' '{print $1}'
  exit
fi

if [ "$1" == "-PATCHLEVEL" ]
then
  echo $VER | awk -F'.' '{print $2}'
  exit
fi

if [ "$1" == "-SUBLEVEL" ]
then
  echo $VER | awk -F'.' '{print $3}'
  exit
fi

echo $VER
exit
