static struct items lan[] = {
	{ "opendns_enable", "0"},
	{ "dhcpd_reserve_00", NULL},
	{ "dhcpd_reserve_01", NULL},
	{ "dhcpd_reserve_02", NULL},
	{ "dhcpd_reserve_03", NULL},
	{ "dhcpd_reserve_04", NULL},
	{ "dhcpd_reserve_05", NULL},
	{ "dhcpd_reserve_06", NULL},
	{ "dhcpd_reserve_07", NULL},
	{ "dhcpd_reserve_08", NULL},
	{ "dhcpd_reserve_09", NULL},
	{ "dhcpd_reserve_10", NULL},
	{ "dhcpd_reserve_11", NULL},
	{ "dhcpd_reserve_12", NULL},
	{ "dhcpd_reserve_13", NULL},
	{ "dhcpd_reserve_14", NULL},
	{ "dhcpd_reserve_15", NULL},
	{ "dhcpd_reserve_16", NULL},
	{ "dhcpd_reserve_17", NULL},
	{ "dhcpd_reserve_18", NULL},
	{ "dhcpd_reserve_19", NULL},
	{ "dhcpd_reserve_20", NULL},
	{ "dhcpd_reserve_21", NULL},
	{ "dhcpd_reserve_22", NULL},
	{ "dhcpd_reserve_23", NULL},
	{ "dhcpd_reserve_24", NULL},
	{ "lan_device_name", "dlinkrouter"},
	{ "dhcpd_domain_name", NULL},
	{ "DNSrelay", "1"},
	{ "dns_relay", "1"},
	{ "dhcp_relay", "0" },
	{ "dhcp_relay_ip", "" },
	{ "dhcpd_enable", "1"},
	{ "dhcpsvr", "1"},
	{ "dhcpd_start", "192.168.0.100"},
	{ "dhcpd_end", "192.168.0.199"},
	{ "dhcpd_lease_time", "10080"},
	{ "dhcpd_always_bcast", "1"},
	{ "dhcpd_netbios_enable", "0"},
	{ "dhcpd_netbios_learn", "0"},
	{ "dhcpd_static_scope", NULL},
	{ "dhcpd_static_node_type", "1"},
	{ "dhcpd_static_wins_server", NULL},
	{ "lan_ipaddr", "192.168.0.1"},
	{ "lan_netmask", "255.255.255.0"},
	{ NULL, NULL}
};

static struct items_range dmz[] = {
	{ "static_addr1", -1, -1, "192.168.0.1"},
	{ "static_netmask1", -1, -1, "255.255.255.0"},
	{ "static_hostname1", -1, -1, "DIR-730"}, //{ "dmz_domain", ""},
	{ "dhcpd_dns_relay1", -1, -1, "1"},
	{ "dhcpd_enable1", -1, -1, "1"},
	{ "dhcpd_start1", -1, -1, "192.168.0.100"},
	{ "dhcpd_end1", -1, -1, "192.168.0.150"},
	{ "dhcpd_lease1", -1, -1, "86400"},
	{ "dhcpd_reserve_", 50, 99, NULL},
	{ "if_services1", -1, -1, DMZ_SERVICES},
	{ NULL, NULL}
};
