rm -rf .config
rm -rf .config.old
rm -rf .configured
rm -rf .preparedf4aaf15a5b54377408616c9c0871bbe2
rm -rf .sgbuilt_lib
rm -rf extra/config/.depend
rm -rf extra/config/conf
rm -rf extra/config/conf.o
rm -rf extra/config/kxgettext.o
rm -rf extra/config/lex.zconf.c
rm -rf extra/config/zconf.hash.c
rm -rf extra/config/zconf.tab.c
rm -rf extra/config/zconf.tab.o
rm -rf extra/scripts/unifdef
rm -rf include/asm-generic/
rm -rf include/asm-ubicom32/
rm -rf include/asm/
rm -rf include/bits/
rm -rf include/config/
rm -rf include/dl-osinfo.h
rm -rf include/fpu_control.h
rm -rf include/hp-timing.h
rm -rf include/linux/
rm -rf include/pthread.h
rm -rf include/semaphore.h
rm -rf include/sys/acct.h
rm -rf include/sys/epoll.h
rm -rf include/sys/inotify.h
rm -rf include/sys/prctl.h
rm -rf include/sys/procfs.h
rm -rf include/sys/ptrace.h
rm -rf include/sys/ucontext.h
rm -rf include/sys/user.h
rm -rf include/thread_db.h
rm -rf ldso/ldso/.ldso.oS.dep
rm -rf ldso/ldso/ld-uClibc_so.a
rm -rf ldso/ldso/ldso.oS
rm -rf ldso/ldso/ubicom32/.resolve.oS.dep
rm -rf ldso/ldso/ubicom32/.resolve.os.dep
rm -rf ldso/ldso/ubicom32/resolve.oS
rm -rf ldso/ldso/ubicom32/resolve.os
rm -rf ldso/libdl/.libdl.oS.dep
rm -rf ldso/libdl/.libdl.os.dep
rm -rf ldso/libdl/libdl.oS
rm -rf ldso/libdl/libdl.os
rm -rf ldso/libdl/libdl_so.a
rm -rf lib/
rm -rf libc/inet/.accept.os.dep
rm -rf libc/inet/.bind.os.dep
rm -rf libc/inet/.closenameservers.os.dep
rm -rf libc/inet/.connect.os.dep
rm -rf libc/inet/.decodea.os.dep
rm -rf libc/inet/.decoded.os.dep
rm -rf libc/inet/.decodeh.os.dep
rm -rf libc/inet/.decodep.os.dep
rm -rf libc/inet/.decodeq.os.dep
rm -rf libc/inet/.dnslookup.os.dep
rm -rf libc/inet/.encodea.os.dep
rm -rf libc/inet/.encoded.os.dep
rm -rf libc/inet/.encodeh.os.dep
rm -rf libc/inet/.encodep.os.dep
rm -rf libc/inet/.encodeq.os.dep
rm -rf libc/inet/.ether_addr.os.dep
rm -rf libc/inet/.ethers.os.dep
rm -rf libc/inet/.formquery.os.dep
rm -rf libc/inet/.gai_strerror.os.dep
rm -rf libc/inet/.get_hosts_byaddr_r.os.dep
rm -rf libc/inet/.get_hosts_byname_r.os.dep
rm -rf libc/inet/.getaddrinfo.os.dep
rm -rf libc/inet/.gethostbyaddr.os.dep
rm -rf libc/inet/.gethostbyaddr_r.os.dep
rm -rf libc/inet/.gethostbyname.os.dep
rm -rf libc/inet/.gethostbyname2.os.dep
rm -rf libc/inet/.gethostbyname2_r.os.dep
rm -rf libc/inet/.gethostbyname_r.os.dep
rm -rf libc/inet/.gethostent.os.dep
rm -rf libc/inet/.getnameinfo.os.dep
rm -rf libc/inet/.getnetbyad.os.dep
rm -rf libc/inet/.getnetbynm.os.dep
rm -rf libc/inet/.getnetent.os.dep
rm -rf libc/inet/.getpeername.os.dep
rm -rf libc/inet/.getproto.os.dep
rm -rf libc/inet/.getservice.os.dep
rm -rf libc/inet/.getsockname.os.dep
rm -rf libc/inet/.getsockopt.os.dep
rm -rf libc/inet/.herror.os.dep
rm -rf libc/inet/.hostid.os.dep
rm -rf libc/inet/.if_index.os.dep
rm -rf libc/inet/.ifaddrs.os.dep
rm -rf libc/inet/.in6_addr.os.dep
rm -rf libc/inet/.inet_addr.os.dep
rm -rf libc/inet/.inet_aton.os.dep
rm -rf libc/inet/.inet_lnaof.os.dep
rm -rf libc/inet/.inet_makeaddr.os.dep
rm -rf libc/inet/.inet_net.os.dep
rm -rf libc/inet/.inet_netof.os.dep
rm -rf libc/inet/.inet_ntoa.os.dep
rm -rf libc/inet/.lengthd.os.dep
rm -rf libc/inet/.lengthq.os.dep
rm -rf libc/inet/.listen.os.dep
rm -rf libc/inet/.ns_name.os.dep
rm -rf libc/inet/.ntohl.os.dep
rm -rf libc/inet/.ntop.os.dep
rm -rf libc/inet/.opennameservers.os.dep
rm -rf libc/inet/.opensock.os.dep
rm -rf libc/inet/.read_etc_hosts_r.os.dep
rm -rf libc/inet/.recv.os.dep
rm -rf libc/inet/.recvfrom.os.dep
rm -rf libc/inet/.recvmsg.os.dep
rm -rf libc/inet/.res_comp.os.dep
rm -rf libc/inet/.res_init.os.dep
rm -rf libc/inet/.res_query.os.dep
rm -rf libc/inet/.resolveaddress.os.dep
rm -rf libc/inet/.resolvename.os.dep
rm -rf libc/inet/.send.os.dep
rm -rf libc/inet/.sendmsg.os.dep
rm -rf libc/inet/.sendto.os.dep
rm -rf libc/inet/.setsockopt.os.dep
rm -rf libc/inet/.shutdown.os.dep
rm -rf libc/inet/.socket.os.dep
rm -rf libc/inet/.socketpair.os.dep
rm -rf libc/inet/accept.os
rm -rf libc/inet/bind.os
rm -rf libc/inet/closenameservers.os
rm -rf libc/inet/connect.os
rm -rf libc/inet/decodea.os
rm -rf libc/inet/decoded.os
rm -rf libc/inet/decodeh.os
rm -rf libc/inet/decodep.os
rm -rf libc/inet/decodeq.os
rm -rf libc/inet/dnslookup.os
rm -rf libc/inet/encodea.os
rm -rf libc/inet/encoded.os
rm -rf libc/inet/encodeh.os
rm -rf libc/inet/encodep.os
rm -rf libc/inet/encodeq.os
rm -rf libc/inet/ether_addr.os
rm -rf libc/inet/ethers.os
rm -rf libc/inet/formquery.os
rm -rf libc/inet/gai_strerror.os
rm -rf libc/inet/get_hosts_byaddr_r.os
rm -rf libc/inet/get_hosts_byname_r.os
rm -rf libc/inet/getaddrinfo.os
rm -rf libc/inet/gethostbyaddr.os
rm -rf libc/inet/gethostbyaddr_r.os
rm -rf libc/inet/gethostbyname.os
rm -rf libc/inet/gethostbyname2.os
rm -rf libc/inet/gethostbyname2_r.os
rm -rf libc/inet/gethostbyname_r.os
rm -rf libc/inet/gethostent.os
rm -rf libc/inet/getnameinfo.os
rm -rf libc/inet/getnetbyad.os
rm -rf libc/inet/getnetbynm.os
rm -rf libc/inet/getnetent.os
rm -rf libc/inet/getpeername.os
rm -rf libc/inet/getproto.os
rm -rf libc/inet/getservice.os
rm -rf libc/inet/getsockname.os
rm -rf libc/inet/getsockopt.os
rm -rf libc/inet/herror.os
rm -rf libc/inet/hostid.os
rm -rf libc/inet/if_index.os
rm -rf libc/inet/ifaddrs.os
rm -rf libc/inet/in6_addr.os
rm -rf libc/inet/inet_addr.os
rm -rf libc/inet/inet_aton.os
rm -rf libc/inet/inet_lnaof.os
rm -rf libc/inet/inet_makeaddr.os
rm -rf libc/inet/inet_net.os
rm -rf libc/inet/inet_netof.os
rm -rf libc/inet/inet_ntoa.os
rm -rf libc/inet/lengthd.os
rm -rf libc/inet/lengthq.os
rm -rf libc/inet/listen.os
rm -rf libc/inet/ns_name.os
rm -rf libc/inet/ntohl.os
rm -rf libc/inet/ntop.os
rm -rf libc/inet/opennameservers.os
rm -rf libc/inet/opensock.os
rm -rf libc/inet/read_etc_hosts_r.os
rm -rf libc/inet/recv.os
rm -rf libc/inet/recvfrom.os
rm -rf libc/inet/recvmsg.os
rm -rf libc/inet/res_comp.os
rm -rf libc/inet/res_init.os
rm -rf libc/inet/res_query.os
rm -rf libc/inet/resolveaddress.os
rm -rf libc/inet/resolvename.os
rm -rf libc/inet/rpc/.auth_none.os.dep
rm -rf libc/inet/rpc/.auth_unix.os.dep
rm -rf libc/inet/rpc/.authunix_prot.os.dep
rm -rf libc/inet/rpc/.bindresvport.os.dep
rm -rf libc/inet/rpc/.clnt_generic.os.dep
rm -rf libc/inet/rpc/.clnt_perror.os.dep
rm -rf libc/inet/rpc/.clnt_raw.os.dep
rm -rf libc/inet/rpc/.clnt_simple.os.dep
rm -rf libc/inet/rpc/.clnt_tcp.os.dep
rm -rf libc/inet/rpc/.clnt_udp.os.dep
rm -rf libc/inet/rpc/.clnt_unix.os.dep
rm -rf libc/inet/rpc/.create_xid.os.dep
rm -rf libc/inet/rpc/.get_myaddress.os.dep
rm -rf libc/inet/rpc/.getrpcent.os.dep
rm -rf libc/inet/rpc/.getrpcport.os.dep
rm -rf libc/inet/rpc/.pm_getmaps.os.dep
rm -rf libc/inet/rpc/.pm_getport.os.dep
rm -rf libc/inet/rpc/.pmap_clnt.os.dep
rm -rf libc/inet/rpc/.pmap_prot.os.dep
rm -rf libc/inet/rpc/.pmap_prot2.os.dep
rm -rf libc/inet/rpc/.pmap_rmt.os.dep
rm -rf libc/inet/rpc/.rcmd.os.dep
rm -rf libc/inet/rpc/.rexec.os.dep
rm -rf libc/inet/rpc/.rpc_cmsg.os.dep
rm -rf libc/inet/rpc/.rpc_commondata.os.dep
rm -rf libc/inet/rpc/.rpc_dtablesize.os.dep
rm -rf libc/inet/rpc/.rpc_prot.os.dep
rm -rf libc/inet/rpc/.rpc_thread.oS.dep
rm -rf libc/inet/rpc/.rpc_thread.os.dep
rm -rf libc/inet/rpc/.rtime.os.dep
rm -rf libc/inet/rpc/.ruserpass.os.dep
rm -rf libc/inet/rpc/.sa_len.os.dep
rm -rf libc/inet/rpc/.svc.os.dep
rm -rf libc/inet/rpc/.svc_auth.os.dep
rm -rf libc/inet/rpc/.svc_authux.os.dep
rm -rf libc/inet/rpc/.svc_raw.os.dep
rm -rf libc/inet/rpc/.svc_run.os.dep
rm -rf libc/inet/rpc/.svc_simple.os.dep
rm -rf libc/inet/rpc/.svc_tcp.os.dep
rm -rf libc/inet/rpc/.svc_udp.os.dep
rm -rf libc/inet/rpc/.svc_unix.os.dep
rm -rf libc/inet/rpc/.xdr.os.dep
rm -rf libc/inet/rpc/.xdr_array.os.dep
rm -rf libc/inet/rpc/.xdr_float.os.dep
rm -rf libc/inet/rpc/.xdr_intXX_t.os.dep
rm -rf libc/inet/rpc/.xdr_mem.os.dep
rm -rf libc/inet/rpc/.xdr_rec.os.dep
rm -rf libc/inet/rpc/.xdr_reference.os.dep
rm -rf libc/inet/rpc/.xdr_stdio.os.dep
rm -rf libc/inet/rpc/auth_none.os
rm -rf libc/inet/rpc/auth_unix.os
rm -rf libc/inet/rpc/authunix_prot.os
rm -rf libc/inet/rpc/bindresvport.os
rm -rf libc/inet/rpc/clnt_generic.os
rm -rf libc/inet/rpc/clnt_perror.os
rm -rf libc/inet/rpc/clnt_raw.os
rm -rf libc/inet/rpc/clnt_simple.os
rm -rf libc/inet/rpc/clnt_tcp.os
rm -rf libc/inet/rpc/clnt_udp.os
rm -rf libc/inet/rpc/clnt_unix.os
rm -rf libc/inet/rpc/create_xid.os
rm -rf libc/inet/rpc/get_myaddress.os
rm -rf libc/inet/rpc/getrpcent.os
rm -rf libc/inet/rpc/getrpcport.os
rm -rf libc/inet/rpc/pm_getmaps.os
rm -rf libc/inet/rpc/pm_getport.os
rm -rf libc/inet/rpc/pmap_clnt.os
rm -rf libc/inet/rpc/pmap_prot.os
rm -rf libc/inet/rpc/pmap_prot2.os
rm -rf libc/inet/rpc/pmap_rmt.os
rm -rf libc/inet/rpc/rcmd.os
rm -rf libc/inet/rpc/rexec.os
rm -rf libc/inet/rpc/rpc_cmsg.os
rm -rf libc/inet/rpc/rpc_commondata.os
rm -rf libc/inet/rpc/rpc_dtablesize.os
rm -rf libc/inet/rpc/rpc_prot.os
rm -rf libc/inet/rpc/rpc_thread.oS
rm -rf libc/inet/rpc/rpc_thread.os
rm -rf libc/inet/rpc/rtime.os
rm -rf libc/inet/rpc/ruserpass.os
rm -rf libc/inet/rpc/sa_len.os
rm -rf libc/inet/rpc/svc.os
rm -rf libc/inet/rpc/svc_auth.os
rm -rf libc/inet/rpc/svc_authux.os
rm -rf libc/inet/rpc/svc_raw.os
rm -rf libc/inet/rpc/svc_run.os
rm -rf libc/inet/rpc/svc_simple.os
rm -rf libc/inet/rpc/svc_tcp.os
rm -rf libc/inet/rpc/svc_udp.os
rm -rf libc/inet/rpc/svc_unix.os
rm -rf libc/inet/rpc/xdr.os
rm -rf libc/inet/rpc/xdr_array.os
rm -rf libc/inet/rpc/xdr_float.os
rm -rf libc/inet/rpc/xdr_intXX_t.os
rm -rf libc/inet/rpc/xdr_mem.os
rm -rf libc/inet/rpc/xdr_rec.os
rm -rf libc/inet/rpc/xdr_reference.os
rm -rf libc/inet/rpc/xdr_stdio.os
rm -rf libc/inet/send.os
rm -rf libc/inet/sendmsg.os
rm -rf libc/inet/sendto.os
rm -rf libc/inet/setsockopt.os
rm -rf libc/inet/shutdown.os
rm -rf libc/inet/socket.os
rm -rf libc/inet/socketpair.os
rm -rf libc/libc_so.a
rm -rf libc/misc/assert/.__assert.os.dep
rm -rf libc/misc/assert/__assert.os
rm -rf libc/misc/ctype/.__C_ctype_b.os.dep
rm -rf libc/misc/ctype/.__C_ctype_tolower.os.dep
rm -rf libc/misc/ctype/.__C_ctype_toupper.os.dep
rm -rf libc/misc/ctype/.__ctype_assert.os.dep
rm -rf libc/misc/ctype/.__ctype_b_loc.os.dep
rm -rf libc/misc/ctype/.__ctype_tolower_loc.os.dep
rm -rf libc/misc/ctype/.__ctype_toupper_loc.os.dep
rm -rf libc/misc/ctype/.isalnum.os.dep
rm -rf libc/misc/ctype/.isalpha.os.dep
rm -rf libc/misc/ctype/.isascii.os.dep
rm -rf libc/misc/ctype/.isblank.os.dep
rm -rf libc/misc/ctype/.iscntrl.os.dep
rm -rf libc/misc/ctype/.isctype.os.dep
rm -rf libc/misc/ctype/.isdigit.os.dep
rm -rf libc/misc/ctype/.isgraph.os.dep
rm -rf libc/misc/ctype/.islower.os.dep
rm -rf libc/misc/ctype/.isprint.os.dep
rm -rf libc/misc/ctype/.ispunct.os.dep
rm -rf libc/misc/ctype/.isspace.os.dep
rm -rf libc/misc/ctype/.isupper.os.dep
rm -rf libc/misc/ctype/.isxdigit.os.dep
rm -rf libc/misc/ctype/.toascii.os.dep
rm -rf libc/misc/ctype/.tolower.os.dep
rm -rf libc/misc/ctype/.toupper.os.dep
rm -rf libc/misc/ctype/__C_ctype_b.os
rm -rf libc/misc/ctype/__C_ctype_tolower.os
rm -rf libc/misc/ctype/__C_ctype_toupper.os
rm -rf libc/misc/ctype/__ctype_assert.os
rm -rf libc/misc/ctype/__ctype_b_loc.os
rm -rf libc/misc/ctype/__ctype_tolower_loc.os
rm -rf libc/misc/ctype/__ctype_toupper_loc.os
rm -rf libc/misc/ctype/isalnum.os
rm -rf libc/misc/ctype/isalpha.os
rm -rf libc/misc/ctype/isascii.os
rm -rf libc/misc/ctype/isblank.os
rm -rf libc/misc/ctype/iscntrl.os
rm -rf libc/misc/ctype/isctype.os
rm -rf libc/misc/ctype/isdigit.os
rm -rf libc/misc/ctype/isgraph.os
rm -rf libc/misc/ctype/islower.os
rm -rf libc/misc/ctype/isprint.os
rm -rf libc/misc/ctype/ispunct.os
rm -rf libc/misc/ctype/isspace.os
rm -rf libc/misc/ctype/isupper.os
rm -rf libc/misc/ctype/isxdigit.os
rm -rf libc/misc/ctype/toascii.os
rm -rf libc/misc/ctype/tolower.os
rm -rf libc/misc/ctype/toupper.os
rm -rf libc/misc/dirent/.alphasort.os.dep
rm -rf libc/misc/dirent/.alphasort64.os.dep
rm -rf libc/misc/dirent/.closedir.os.dep
rm -rf libc/misc/dirent/.dirfd.os.dep
rm -rf libc/misc/dirent/.opendir.os.dep
rm -rf libc/misc/dirent/.readdir.os.dep
rm -rf libc/misc/dirent/.readdir64.os.dep
rm -rf libc/misc/dirent/.readdir64_r.os.dep
rm -rf libc/misc/dirent/.readdir_r.os.dep
rm -rf libc/misc/dirent/.rewinddir.os.dep
rm -rf libc/misc/dirent/.scandir.os.dep
rm -rf libc/misc/dirent/.scandir64.os.dep
rm -rf libc/misc/dirent/.seekdir.os.dep
rm -rf libc/misc/dirent/.telldir.os.dep
rm -rf libc/misc/dirent/alphasort.os
rm -rf libc/misc/dirent/alphasort64.os
rm -rf libc/misc/dirent/closedir.os
rm -rf libc/misc/dirent/dirfd.os
rm -rf libc/misc/dirent/opendir.os
rm -rf libc/misc/dirent/readdir.os
rm -rf libc/misc/dirent/readdir64.os
rm -rf libc/misc/dirent/readdir64_r.os
rm -rf libc/misc/dirent/readdir_r.os
rm -rf libc/misc/dirent/rewinddir.os
rm -rf libc/misc/dirent/scandir.os
rm -rf libc/misc/dirent/scandir64.os
rm -rf libc/misc/dirent/seekdir.os
rm -rf libc/misc/dirent/telldir.os
rm -rf libc/misc/elf/.dl-core.os.dep
rm -rf libc/misc/elf/.dl-iterate-phdr.oS.dep
rm -rf libc/misc/elf/.dl-iterate-phdr.os.dep
rm -rf libc/misc/elf/.dl-support.os.dep
rm -rf libc/misc/elf/dl-core.os
rm -rf libc/misc/elf/dl-iterate-phdr.oS
rm -rf libc/misc/elf/dl-iterate-phdr.os
rm -rf libc/misc/elf/dl-support.os
rm -rf libc/misc/error/.err.os.dep
rm -rf libc/misc/error/.error.os.dep
rm -rf libc/misc/error/err.os
rm -rf libc/misc/error/error.os
rm -rf libc/misc/file/.lockf.os.dep
rm -rf libc/misc/file/.lockf64.os.dep
rm -rf libc/misc/file/lockf.os
rm -rf libc/misc/file/lockf64.os
rm -rf libc/misc/fnmatch/.fnmatch_old.os.dep
rm -rf libc/misc/fnmatch/fnmatch_old.os
rm -rf libc/misc/glob/.glob-susv3.os.dep
rm -rf libc/misc/glob/.glob.os.dep
rm -rf libc/misc/glob/.glob64-susv3.os.dep
rm -rf libc/misc/glob/.glob64.os.dep
rm -rf libc/misc/glob/glob-susv3.os
rm -rf libc/misc/glob/glob.os
rm -rf libc/misc/glob/glob64-susv3.os
rm -rf libc/misc/glob/glob64.os
rm -rf libc/misc/gnu/.obstack.os.dep
rm -rf libc/misc/gnu/obstack.os
rm -rf libc/misc/internals/.__errno_location.os.dep
rm -rf libc/misc/internals/.__h_errno_location.os.dep
rm -rf libc/misc/internals/.__uClibc_main.oS.dep
rm -rf libc/misc/internals/.__uClibc_main.os.dep
rm -rf libc/misc/internals/.errno.os.dep
rm -rf libc/misc/internals/.tempname.os.dep
rm -rf libc/misc/internals/__errno_location.os
rm -rf libc/misc/internals/__h_errno_location.os
rm -rf libc/misc/internals/__uClibc_main.oS
rm -rf libc/misc/internals/__uClibc_main.os
rm -rf libc/misc/internals/errno.os
rm -rf libc/misc/internals/tempname.os
rm -rf libc/misc/locale/._locale_init.os.dep
rm -rf libc/misc/locale/.localeconv.os.dep
rm -rf libc/misc/locale/.nl_langinfo.os.dep
rm -rf libc/misc/locale/.setlocale.os.dep
rm -rf libc/misc/locale/_locale_init.os
rm -rf libc/misc/locale/localeconv.os
rm -rf libc/misc/locale/nl_langinfo.os
rm -rf libc/misc/locale/setlocale.os
rm -rf libc/misc/mntent/.mntent.os.dep
rm -rf libc/misc/mntent/mntent.os
rm -rf libc/misc/regex/.regex_old.os.dep
rm -rf libc/misc/regex/regex_old.os
rm -rf libc/misc/search/.hcreate_r.os.dep
rm -rf libc/misc/search/.hdestroy_r.os.dep
rm -rf libc/misc/search/.hsearch.os.dep
rm -rf libc/misc/search/.hsearch_r.os.dep
rm -rf libc/misc/search/.insque.os.dep
rm -rf libc/misc/search/.lfind.os.dep
rm -rf libc/misc/search/.lsearch.os.dep
rm -rf libc/misc/search/.remque.os.dep
rm -rf libc/misc/search/.tdelete.os.dep
rm -rf libc/misc/search/.tdestroy.os.dep
rm -rf libc/misc/search/.tfind.os.dep
rm -rf libc/misc/search/.tsearch.os.dep
rm -rf libc/misc/search/.twalk.os.dep
rm -rf libc/misc/search/hcreate_r.os
rm -rf libc/misc/search/hdestroy_r.os
rm -rf libc/misc/search/hsearch.os
rm -rf libc/misc/search/hsearch_r.os
rm -rf libc/misc/search/insque.os
rm -rf libc/misc/search/lfind.os
rm -rf libc/misc/search/lsearch.os
rm -rf libc/misc/search/remque.os
rm -rf libc/misc/search/tdelete.os
rm -rf libc/misc/search/tdestroy.os
rm -rf libc/misc/search/tfind.os
rm -rf libc/misc/search/tsearch.os
rm -rf libc/misc/search/twalk.os
rm -rf libc/misc/statfs/.fstatfs64.os.dep
rm -rf libc/misc/statfs/.fstatvfs.os.dep
rm -rf libc/misc/statfs/.fstatvfs64.os.dep
rm -rf libc/misc/statfs/.statfs64.os.dep
rm -rf libc/misc/statfs/.statvfs.os.dep
rm -rf libc/misc/statfs/.statvfs64.os.dep
rm -rf libc/misc/statfs/fstatfs64.os
rm -rf libc/misc/statfs/fstatvfs.os
rm -rf libc/misc/statfs/fstatvfs64.os
rm -rf libc/misc/statfs/statfs64.os
rm -rf libc/misc/statfs/statvfs.os
rm -rf libc/misc/statfs/statvfs64.os
rm -rf libc/misc/syslog/.syslog.os.dep
rm -rf libc/misc/syslog/syslog.os
rm -rf libc/misc/sysvipc/.__syscall_ipc.os.dep
rm -rf libc/misc/sysvipc/.ftok.os.dep
rm -rf libc/misc/sysvipc/.msgctl.os.dep
rm -rf libc/misc/sysvipc/.msgget.os.dep
rm -rf libc/misc/sysvipc/.msgrcv.os.dep
rm -rf libc/misc/sysvipc/.msgsnd.os.dep
rm -rf libc/misc/sysvipc/.semctl.os.dep
rm -rf libc/misc/sysvipc/.semget.os.dep
rm -rf libc/misc/sysvipc/.semop.os.dep
rm -rf libc/misc/sysvipc/.semtimedop.os.dep
rm -rf libc/misc/sysvipc/.shmat.os.dep
rm -rf libc/misc/sysvipc/.shmctl.os.dep
rm -rf libc/misc/sysvipc/.shmdt.os.dep
rm -rf libc/misc/sysvipc/.shmget.os.dep
rm -rf libc/misc/sysvipc/__syscall_ipc.os
rm -rf libc/misc/sysvipc/ftok.os
rm -rf libc/misc/sysvipc/msgctl.os
rm -rf libc/misc/sysvipc/msgget.os
rm -rf libc/misc/sysvipc/msgrcv.os
rm -rf libc/misc/sysvipc/msgsnd.os
rm -rf libc/misc/sysvipc/semctl.os
rm -rf libc/misc/sysvipc/semget.os
rm -rf libc/misc/sysvipc/semop.os
rm -rf libc/misc/sysvipc/semtimedop.os
rm -rf libc/misc/sysvipc/shmat.os
rm -rf libc/misc/sysvipc/shmctl.os
rm -rf libc/misc/sysvipc/shmdt.os
rm -rf libc/misc/sysvipc/shmget.os
rm -rf libc/misc/time/.__time_tm.os.dep
rm -rf libc/misc/time/._time_localtime_tzi.os.dep
rm -rf libc/misc/time/._time_mktime.os.dep
rm -rf libc/misc/time/._time_mktime_tzi.os.dep
rm -rf libc/misc/time/._time_t2tm.os.dep
rm -rf libc/misc/time/.adjtime.os.dep
rm -rf libc/misc/time/.asctime.os.dep
rm -rf libc/misc/time/.asctime_r.os.dep
rm -rf libc/misc/time/.clock.os.dep
rm -rf libc/misc/time/.ctime.os.dep
rm -rf libc/misc/time/.ctime_r.os.dep
rm -rf libc/misc/time/.difftime.os.dep
rm -rf libc/misc/time/.dysize.os.dep
rm -rf libc/misc/time/.ftime.os.dep
rm -rf libc/misc/time/.gmtime.os.dep
rm -rf libc/misc/time/.gmtime_r.os.dep
rm -rf libc/misc/time/.localtime.os.dep
rm -rf libc/misc/time/.localtime_r.os.dep
rm -rf libc/misc/time/.mktime.os.dep
rm -rf libc/misc/time/.strftime.os.dep
rm -rf libc/misc/time/.strptime.os.dep
rm -rf libc/misc/time/.timegm.os.dep
rm -rf libc/misc/time/.tzset.os.dep
rm -rf libc/misc/time/.wcsftime.os.dep
rm -rf libc/misc/time/__time_tm.os
rm -rf libc/misc/time/_time_localtime_tzi.os
rm -rf libc/misc/time/_time_mktime.os
rm -rf libc/misc/time/_time_mktime_tzi.os
rm -rf libc/misc/time/_time_t2tm.os
rm -rf libc/misc/time/adjtime.os
rm -rf libc/misc/time/asctime.os
rm -rf libc/misc/time/asctime_r.os
rm -rf libc/misc/time/clock.os
rm -rf libc/misc/time/ctime.os
rm -rf libc/misc/time/ctime_r.os
rm -rf libc/misc/time/difftime.os
rm -rf libc/misc/time/dysize.os
rm -rf libc/misc/time/ftime.os
rm -rf libc/misc/time/gmtime.os
rm -rf libc/misc/time/gmtime_r.os
rm -rf libc/misc/time/localtime.os
rm -rf libc/misc/time/localtime_r.os
rm -rf libc/misc/time/mktime.os
rm -rf libc/misc/time/strftime.os
rm -rf libc/misc/time/strptime.os
rm -rf libc/misc/time/timegm.os
rm -rf libc/misc/time/tzset.os
rm -rf libc/misc/time/wcsftime.os
rm -rf libc/misc/ttyent/.getttyent.os.dep
rm -rf libc/misc/ttyent/getttyent.os
rm -rf libc/misc/utmp/.utent.os.dep
rm -rf libc/misc/utmp/.wtent.os.dep
rm -rf libc/misc/utmp/utent.os
rm -rf libc/misc/utmp/wtent.os
rm -rf libc/misc/wchar/._wchar_utf8sntowcs.os.dep
rm -rf libc/misc/wchar/._wchar_wcsntoutf8s.os.dep
rm -rf libc/misc/wchar/.btowc.os.dep
rm -rf libc/misc/wchar/.mbrlen.os.dep
rm -rf libc/misc/wchar/.mbrtowc.os.dep
rm -rf libc/misc/wchar/.mbsinit.os.dep
rm -rf libc/misc/wchar/.mbsnrtowcs.os.dep
rm -rf libc/misc/wchar/.mbsrtowcs.os.dep
rm -rf libc/misc/wchar/.wcrtomb.os.dep
rm -rf libc/misc/wchar/.wcsnrtombs.os.dep
rm -rf libc/misc/wchar/.wcsrtombs.os.dep
rm -rf libc/misc/wchar/.wcswidth.os.dep
rm -rf libc/misc/wchar/.wctob.os.dep
rm -rf libc/misc/wchar/.wcwidth.os.dep
rm -rf libc/misc/wchar/_wchar_utf8sntowcs.os
rm -rf libc/misc/wchar/_wchar_wcsntoutf8s.os
rm -rf libc/misc/wchar/btowc.os
rm -rf libc/misc/wchar/mbrlen.os
rm -rf libc/misc/wchar/mbrtowc.os
rm -rf libc/misc/wchar/mbsinit.os
rm -rf libc/misc/wchar/mbsnrtowcs.os
rm -rf libc/misc/wchar/mbsrtowcs.os
rm -rf libc/misc/wchar/wcrtomb.os
rm -rf libc/misc/wchar/wcsnrtombs.os
rm -rf libc/misc/wchar/wcsrtombs.os
rm -rf libc/misc/wchar/wcswidth.os
rm -rf libc/misc/wchar/wctob.os
rm -rf libc/misc/wchar/wcwidth.os
rm -rf libc/misc/wctype/.iswalnum.os.dep
rm -rf libc/misc/wctype/.iswalpha.os.dep
rm -rf libc/misc/wctype/.iswblank.os.dep
rm -rf libc/misc/wctype/.iswcntrl.os.dep
rm -rf libc/misc/wctype/.iswctype.os.dep
rm -rf libc/misc/wctype/.iswdigit.os.dep
rm -rf libc/misc/wctype/.iswgraph.os.dep
rm -rf libc/misc/wctype/.iswlower.os.dep
rm -rf libc/misc/wctype/.iswprint.os.dep
rm -rf libc/misc/wctype/.iswpunct.os.dep
rm -rf libc/misc/wctype/.iswspace.os.dep
rm -rf libc/misc/wctype/.iswupper.os.dep
rm -rf libc/misc/wctype/.iswxdigit.os.dep
rm -rf libc/misc/wctype/.towctrans.os.dep
rm -rf libc/misc/wctype/.towlower.os.dep
rm -rf libc/misc/wctype/.towupper.os.dep
rm -rf libc/misc/wctype/.wctrans.os.dep
rm -rf libc/misc/wctype/.wctype.os.dep
rm -rf libc/misc/wctype/iswalnum.os
rm -rf libc/misc/wctype/iswalpha.os
rm -rf libc/misc/wctype/iswblank.os
rm -rf libc/misc/wctype/iswcntrl.os
rm -rf libc/misc/wctype/iswctype.os
rm -rf libc/misc/wctype/iswdigit.os
rm -rf libc/misc/wctype/iswgraph.os
rm -rf libc/misc/wctype/iswlower.os
rm -rf libc/misc/wctype/iswprint.os
rm -rf libc/misc/wctype/iswpunct.os
rm -rf libc/misc/wctype/iswspace.os
rm -rf libc/misc/wctype/iswupper.os
rm -rf libc/misc/wctype/iswxdigit.os
rm -rf libc/misc/wctype/towctrans.os
rm -rf libc/misc/wctype/towlower.os
rm -rf libc/misc/wctype/towupper.os
rm -rf libc/misc/wctype/wctrans.os
rm -rf libc/misc/wctype/wctype.os
rm -rf libc/pwd_grp/.__getgrouplist_internal.os.dep
rm -rf libc/pwd_grp/.__parsegrent.os.dep
rm -rf libc/pwd_grp/.__parsepwent.os.dep
rm -rf libc/pwd_grp/.__parsespent.os.dep
rm -rf libc/pwd_grp/.__pgsreader.os.dep
rm -rf libc/pwd_grp/.fgetgrent.os.dep
rm -rf libc/pwd_grp/.fgetgrent_r.os.dep
rm -rf libc/pwd_grp/.fgetpwent.os.dep
rm -rf libc/pwd_grp/.fgetpwent_r.os.dep
rm -rf libc/pwd_grp/.fgetspent.os.dep
rm -rf libc/pwd_grp/.fgetspent_r.os.dep
rm -rf libc/pwd_grp/.getgrent.os.dep
rm -rf libc/pwd_grp/.getgrent_r.os.dep
rm -rf libc/pwd_grp/.getgrgid.os.dep
rm -rf libc/pwd_grp/.getgrgid_r.os.dep
rm -rf libc/pwd_grp/.getgrnam.os.dep
rm -rf libc/pwd_grp/.getgrnam_r.os.dep
rm -rf libc/pwd_grp/.getgrouplist.os.dep
rm -rf libc/pwd_grp/.getpw.os.dep
rm -rf libc/pwd_grp/.getpwent.os.dep
rm -rf libc/pwd_grp/.getpwent_r.os.dep
rm -rf libc/pwd_grp/.getpwnam.os.dep
rm -rf libc/pwd_grp/.getpwnam_r.os.dep
rm -rf libc/pwd_grp/.getpwuid.os.dep
rm -rf libc/pwd_grp/.getpwuid_r.os.dep
rm -rf libc/pwd_grp/.getspent.os.dep
rm -rf libc/pwd_grp/.getspent_r.os.dep
rm -rf libc/pwd_grp/.getspnam.os.dep
rm -rf libc/pwd_grp/.getspnam_r.os.dep
rm -rf libc/pwd_grp/.initgroups.os.dep
rm -rf libc/pwd_grp/.lckpwdf.os.dep
rm -rf libc/pwd_grp/.putgrent.os.dep
rm -rf libc/pwd_grp/.putpwent.os.dep
rm -rf libc/pwd_grp/.putspent.os.dep
rm -rf libc/pwd_grp/.sgetspent.os.dep
rm -rf libc/pwd_grp/.sgetspent_r.os.dep
rm -rf libc/pwd_grp/__getgrouplist_internal.os
rm -rf libc/pwd_grp/__parsegrent.os
rm -rf libc/pwd_grp/__parsepwent.os
rm -rf libc/pwd_grp/__parsespent.os
rm -rf libc/pwd_grp/__pgsreader.os
rm -rf libc/pwd_grp/fgetgrent.os
rm -rf libc/pwd_grp/fgetgrent_r.os
rm -rf libc/pwd_grp/fgetpwent.os
rm -rf libc/pwd_grp/fgetpwent_r.os
rm -rf libc/pwd_grp/fgetspent.os
rm -rf libc/pwd_grp/fgetspent_r.os
rm -rf libc/pwd_grp/getgrent.os
rm -rf libc/pwd_grp/getgrent_r.os
rm -rf libc/pwd_grp/getgrgid.os
rm -rf libc/pwd_grp/getgrgid_r.os
rm -rf libc/pwd_grp/getgrnam.os
rm -rf libc/pwd_grp/getgrnam_r.os
rm -rf libc/pwd_grp/getgrouplist.os
rm -rf libc/pwd_grp/getpw.os
rm -rf libc/pwd_grp/getpwent.os
rm -rf libc/pwd_grp/getpwent_r.os
rm -rf libc/pwd_grp/getpwnam.os
rm -rf libc/pwd_grp/getpwnam_r.os
rm -rf libc/pwd_grp/getpwuid.os
rm -rf libc/pwd_grp/getpwuid_r.os
rm -rf libc/pwd_grp/getspent.os
rm -rf libc/pwd_grp/getspent_r.os
rm -rf libc/pwd_grp/getspnam.os
rm -rf libc/pwd_grp/getspnam_r.os
rm -rf libc/pwd_grp/initgroups.os
rm -rf libc/pwd_grp/lckpwdf.os
rm -rf libc/pwd_grp/putgrent.os
rm -rf libc/pwd_grp/putpwent.os
rm -rf libc/pwd_grp/putspent.os
rm -rf libc/pwd_grp/sgetspent.os
rm -rf libc/pwd_grp/sgetspent_r.os
rm -rf libc/signal/.allocrtsig.os.dep
rm -rf libc/signal/.killpg.os.dep
rm -rf libc/signal/.raise.os.dep
rm -rf libc/signal/.sigaction.os.dep
rm -rf libc/signal/.sigaddset.os.dep
rm -rf libc/signal/.sigandset.os.dep
rm -rf libc/signal/.sigblock.os.dep
rm -rf libc/signal/.sigdelset.os.dep
rm -rf libc/signal/.sigempty.os.dep
rm -rf libc/signal/.sigfillset.os.dep
rm -rf libc/signal/.siggetmask.os.dep
rm -rf libc/signal/.sighold.os.dep
rm -rf libc/signal/.sigignore.os.dep
rm -rf libc/signal/.sigintr.os.dep
rm -rf libc/signal/.sigisempty.os.dep
rm -rf libc/signal/.sigismem.os.dep
rm -rf libc/signal/.sigjmp.os.dep
rm -rf libc/signal/.signal.os.dep
rm -rf libc/signal/.sigorset.os.dep
rm -rf libc/signal/.sigpause.os.dep
rm -rf libc/signal/.sigrelse.os.dep
rm -rf libc/signal/.sigset.os.dep
rm -rf libc/signal/.sigsetmask.os.dep
rm -rf libc/signal/.sigsetops.os.dep
rm -rf libc/signal/.sigwait.os.dep
rm -rf libc/signal/.sysv_signal.os.dep
rm -rf libc/signal/allocrtsig.os
rm -rf libc/signal/killpg.os
rm -rf libc/signal/raise.os
rm -rf libc/signal/sigaction.os
rm -rf libc/signal/sigaddset.os
rm -rf libc/signal/sigandset.os
rm -rf libc/signal/sigblock.os
rm -rf libc/signal/sigdelset.os
rm -rf libc/signal/sigempty.os
rm -rf libc/signal/sigfillset.os
rm -rf libc/signal/siggetmask.os
rm -rf libc/signal/sighold.os
rm -rf libc/signal/sigignore.os
rm -rf libc/signal/sigintr.os
rm -rf libc/signal/sigisempty.os
rm -rf libc/signal/sigismem.os
rm -rf libc/signal/sigjmp.os
rm -rf libc/signal/signal.os
rm -rf libc/signal/sigorset.os
rm -rf libc/signal/sigpause.os
rm -rf libc/signal/sigrelse.os
rm -rf libc/signal/sigset.os
rm -rf libc/signal/sigsetmask.os
rm -rf libc/signal/sigsetops.os
rm -rf libc/signal/sigwait.os
rm -rf libc/signal/sysv_signal.os
rm -rf libc/stdio/._READ.os.dep
rm -rf libc/stdio/._WRITE.os.dep
rm -rf libc/stdio/.__fbufsize.os.dep
rm -rf libc/stdio/.__flbf.os.dep
rm -rf libc/stdio/.__fpending.os.dep
rm -rf libc/stdio/.__fpurge.os.dep
rm -rf libc/stdio/.__freadable.os.dep
rm -rf libc/stdio/.__freading.os.dep
rm -rf libc/stdio/.__fsetlocking.os.dep
rm -rf libc/stdio/.__fwritable.os.dep
rm -rf libc/stdio/.__fwriting.os.dep
rm -rf libc/stdio/.__psfs_do_numeric.os.dep
rm -rf libc/stdio/.__psfs_parse_spec.os.dep
rm -rf libc/stdio/.__scan_cookie.os.dep
rm -rf libc/stdio/._adjust_pos.os.dep
rm -rf libc/stdio/._cs_funcs.os.dep
rm -rf libc/stdio/._flushlbf.os.dep
rm -rf libc/stdio/._fopen.os.dep
rm -rf libc/stdio/._fpmaxtostr.os.dep
rm -rf libc/stdio/._fwrite.os.dep
rm -rf libc/stdio/._load_inttype.os.dep
rm -rf libc/stdio/._ppfs_init.os.dep
rm -rf libc/stdio/._ppfs_parsespec.os.dep
rm -rf libc/stdio/._ppfs_prepargs.os.dep
rm -rf libc/stdio/._ppfs_setargs.os.dep
rm -rf libc/stdio/._rfill.os.dep
rm -rf libc/stdio/._stdio.os.dep
rm -rf libc/stdio/._store_inttype.os.dep
rm -rf libc/stdio/._trans2r.os.dep
rm -rf libc/stdio/._trans2w.os.dep
rm -rf libc/stdio/._uintmaxtostr.os.dep
rm -rf libc/stdio/._vfprintf_internal.os.dep
rm -rf libc/stdio/._vfwprintf_internal.os.dep
rm -rf libc/stdio/._wcommit.os.dep
rm -rf libc/stdio/._wfwrite.os.dep
rm -rf libc/stdio/.asprintf.os.dep
rm -rf libc/stdio/.clearerr.os.dep
rm -rf libc/stdio/.clearerr_unlocked.os.dep
rm -rf libc/stdio/.ctermid.os.dep
rm -rf libc/stdio/.dprintf.os.dep
rm -rf libc/stdio/.fclose.os.dep
rm -rf libc/stdio/.fcloseall.os.dep
rm -rf libc/stdio/.fdopen.os.dep
rm -rf libc/stdio/.feof.os.dep
rm -rf libc/stdio/.feof_unlocked.os.dep
rm -rf libc/stdio/.ferror.os.dep
rm -rf libc/stdio/.ferror_unlocked.os.dep
rm -rf libc/stdio/.fflush.os.dep
rm -rf libc/stdio/.fflush_unlocked.os.dep
rm -rf libc/stdio/.fgetc.os.dep
rm -rf libc/stdio/.fgetc_unlocked.os.dep
rm -rf libc/stdio/.fgetpos.os.dep
rm -rf libc/stdio/.fgetpos64.os.dep
rm -rf libc/stdio/.fgets.os.dep
rm -rf libc/stdio/.fgets_unlocked.os.dep
rm -rf libc/stdio/.fgetwc.os.dep
rm -rf libc/stdio/.fgetwc_unlocked.os.dep
rm -rf libc/stdio/.fgetws.os.dep
rm -rf libc/stdio/.fgetws_unlocked.os.dep
rm -rf libc/stdio/.fileno.os.dep
rm -rf libc/stdio/.fileno_unlocked.os.dep
rm -rf libc/stdio/.flockfile.os.dep
rm -rf libc/stdio/.fopen.os.dep
rm -rf libc/stdio/.fopen64.os.dep
rm -rf libc/stdio/.fprintf.os.dep
rm -rf libc/stdio/.fputc.os.dep
rm -rf libc/stdio/.fputc_unlocked.os.dep
rm -rf libc/stdio/.fputs.os.dep
rm -rf libc/stdio/.fputs_unlocked.os.dep
rm -rf libc/stdio/.fputwc.os.dep
rm -rf libc/stdio/.fputwc_unlocked.os.dep
rm -rf libc/stdio/.fputws.os.dep
rm -rf libc/stdio/.fputws_unlocked.os.dep
rm -rf libc/stdio/.fread.os.dep
rm -rf libc/stdio/.fread_unlocked.os.dep
rm -rf libc/stdio/.freopen.os.dep
rm -rf libc/stdio/.freopen64.os.dep
rm -rf libc/stdio/.fscanf.os.dep
rm -rf libc/stdio/.fseeko.os.dep
rm -rf libc/stdio/.fseeko64.os.dep
rm -rf libc/stdio/.fsetpos.os.dep
rm -rf libc/stdio/.fsetpos64.os.dep
rm -rf libc/stdio/.ftello.os.dep
rm -rf libc/stdio/.ftello64.os.dep
rm -rf libc/stdio/.ftrylockfile.os.dep
rm -rf libc/stdio/.funlockfile.os.dep
rm -rf libc/stdio/.fwide.os.dep
rm -rf libc/stdio/.fwprintf.os.dep
rm -rf libc/stdio/.fwrite.os.dep
rm -rf libc/stdio/.fwrite_unlocked.os.dep
rm -rf libc/stdio/.fwscanf.os.dep
rm -rf libc/stdio/.getchar.os.dep
rm -rf libc/stdio/.getchar_unlocked.os.dep
rm -rf libc/stdio/.getdelim.os.dep
rm -rf libc/stdio/.getline.os.dep
rm -rf libc/stdio/.gets.os.dep
rm -rf libc/stdio/.getw.os.dep
rm -rf libc/stdio/.getwchar.os.dep
rm -rf libc/stdio/.getwchar_unlocked.os.dep
rm -rf libc/stdio/.parse_printf_format.os.dep
rm -rf libc/stdio/.perror.os.dep
rm -rf libc/stdio/.popen.os.dep
rm -rf libc/stdio/.printf.os.dep
rm -rf libc/stdio/.putchar.os.dep
rm -rf libc/stdio/.putchar_unlocked.os.dep
rm -rf libc/stdio/.puts.os.dep
rm -rf libc/stdio/.putw.os.dep
rm -rf libc/stdio/.putwchar.os.dep
rm -rf libc/stdio/.putwchar_unlocked.os.dep
rm -rf libc/stdio/.register_printf_function.os.dep
rm -rf libc/stdio/.remove.os.dep
rm -rf libc/stdio/.rewind.os.dep
rm -rf libc/stdio/.scanf.os.dep
rm -rf libc/stdio/.setbuf.os.dep
rm -rf libc/stdio/.setbuffer.os.dep
rm -rf libc/stdio/.setlinebuf.os.dep
rm -rf libc/stdio/.setvbuf.os.dep
rm -rf libc/stdio/.snprintf.os.dep
rm -rf libc/stdio/.sprintf.os.dep
rm -rf libc/stdio/.sscanf.os.dep
rm -rf libc/stdio/.swprintf.os.dep
rm -rf libc/stdio/.swscanf.os.dep
rm -rf libc/stdio/.tempnam.os.dep
rm -rf libc/stdio/.tmpfile.os.dep
rm -rf libc/stdio/.tmpnam.os.dep
rm -rf libc/stdio/.tmpnam_r.os.dep
rm -rf libc/stdio/.ungetc.os.dep
rm -rf libc/stdio/.ungetwc.os.dep
rm -rf libc/stdio/.vasprintf.os.dep
rm -rf libc/stdio/.vdprintf.os.dep
rm -rf libc/stdio/.vfprintf.os.dep
rm -rf libc/stdio/.vfscanf.os.dep
rm -rf libc/stdio/.vfwprintf.os.dep
rm -rf libc/stdio/.vfwscanf.os.dep
rm -rf libc/stdio/.vprintf.os.dep
rm -rf libc/stdio/.vscanf.os.dep
rm -rf libc/stdio/.vsnprintf.os.dep
rm -rf libc/stdio/.vsprintf.os.dep
rm -rf libc/stdio/.vsscanf.os.dep
rm -rf libc/stdio/.vswprintf.os.dep
rm -rf libc/stdio/.vswscanf.os.dep
rm -rf libc/stdio/.vwprintf.os.dep
rm -rf libc/stdio/.vwscanf.os.dep
rm -rf libc/stdio/.wprintf.os.dep
rm -rf libc/stdio/.wscanf.os.dep
rm -rf libc/stdio/_READ.os
rm -rf libc/stdio/_WRITE.os
rm -rf libc/stdio/__fbufsize.os
rm -rf libc/stdio/__flbf.os
rm -rf libc/stdio/__fpending.os
rm -rf libc/stdio/__fpurge.os
rm -rf libc/stdio/__freadable.os
rm -rf libc/stdio/__freading.os
rm -rf libc/stdio/__fsetlocking.os
rm -rf libc/stdio/__fwritable.os
rm -rf libc/stdio/__fwriting.os
rm -rf libc/stdio/__psfs_do_numeric.os
rm -rf libc/stdio/__psfs_parse_spec.os
rm -rf libc/stdio/__scan_cookie.os
rm -rf libc/stdio/_adjust_pos.os
rm -rf libc/stdio/_cs_funcs.os
rm -rf libc/stdio/_flushlbf.os
rm -rf libc/stdio/_fopen.os
rm -rf libc/stdio/_fpmaxtostr.os
rm -rf libc/stdio/_fwrite.os
rm -rf libc/stdio/_load_inttype.os
rm -rf libc/stdio/_ppfs_init.os
rm -rf libc/stdio/_ppfs_parsespec.os
rm -rf libc/stdio/_ppfs_prepargs.os
rm -rf libc/stdio/_ppfs_setargs.os
rm -rf libc/stdio/_rfill.os
rm -rf libc/stdio/_stdio.os
rm -rf libc/stdio/_store_inttype.os
rm -rf libc/stdio/_trans2r.os
rm -rf libc/stdio/_trans2w.os
rm -rf libc/stdio/_uintmaxtostr.os
rm -rf libc/stdio/_vfprintf_internal.os
rm -rf libc/stdio/_vfwprintf_internal.os
rm -rf libc/stdio/_wcommit.os
rm -rf libc/stdio/_wfwrite.os
rm -rf libc/stdio/asprintf.os
rm -rf libc/stdio/clearerr.os
rm -rf libc/stdio/clearerr_unlocked.os
rm -rf libc/stdio/ctermid.os
rm -rf libc/stdio/dprintf.os
rm -rf libc/stdio/fclose.os
rm -rf libc/stdio/fcloseall.os
rm -rf libc/stdio/fdopen.os
rm -rf libc/stdio/feof.os
rm -rf libc/stdio/feof_unlocked.os
rm -rf libc/stdio/ferror.os
rm -rf libc/stdio/ferror_unlocked.os
rm -rf libc/stdio/fflush.os
rm -rf libc/stdio/fflush_unlocked.os
rm -rf libc/stdio/fgetc.os
rm -rf libc/stdio/fgetc_unlocked.os
rm -rf libc/stdio/fgetpos.os
rm -rf libc/stdio/fgetpos64.os
rm -rf libc/stdio/fgets.os
rm -rf libc/stdio/fgets_unlocked.os
rm -rf libc/stdio/fgetwc.os
rm -rf libc/stdio/fgetwc_unlocked.os
rm -rf libc/stdio/fgetws.os
rm -rf libc/stdio/fgetws_unlocked.os
rm -rf libc/stdio/fileno.os
rm -rf libc/stdio/fileno_unlocked.os
rm -rf libc/stdio/flockfile.os
rm -rf libc/stdio/fopen.os
rm -rf libc/stdio/fopen64.os
rm -rf libc/stdio/fprintf.os
rm -rf libc/stdio/fputc.os
rm -rf libc/stdio/fputc_unlocked.os
rm -rf libc/stdio/fputs.os
rm -rf libc/stdio/fputs_unlocked.os
rm -rf libc/stdio/fputwc.os
rm -rf libc/stdio/fputwc_unlocked.os
rm -rf libc/stdio/fputws.os
rm -rf libc/stdio/fputws_unlocked.os
rm -rf libc/stdio/fread.os
rm -rf libc/stdio/fread_unlocked.os
rm -rf libc/stdio/freopen.os
rm -rf libc/stdio/freopen64.os
rm -rf libc/stdio/fscanf.os
rm -rf libc/stdio/fseeko.os
rm -rf libc/stdio/fseeko64.os
rm -rf libc/stdio/fsetpos.os
rm -rf libc/stdio/fsetpos64.os
rm -rf libc/stdio/ftello.os
rm -rf libc/stdio/ftello64.os
rm -rf libc/stdio/ftrylockfile.os
rm -rf libc/stdio/funlockfile.os
rm -rf libc/stdio/fwide.os
rm -rf libc/stdio/fwprintf.os
rm -rf libc/stdio/fwrite.os
rm -rf libc/stdio/fwrite_unlocked.os
rm -rf libc/stdio/fwscanf.os
rm -rf libc/stdio/getchar.os
rm -rf libc/stdio/getchar_unlocked.os
rm -rf libc/stdio/getdelim.os
rm -rf libc/stdio/getline.os
rm -rf libc/stdio/gets.os
rm -rf libc/stdio/getw.os
rm -rf libc/stdio/getwchar.os
rm -rf libc/stdio/getwchar_unlocked.os
rm -rf libc/stdio/parse_printf_format.os
rm -rf libc/stdio/perror.os
rm -rf libc/stdio/popen.os
rm -rf libc/stdio/printf.os
rm -rf libc/stdio/putchar.os
rm -rf libc/stdio/putchar_unlocked.os
rm -rf libc/stdio/puts.os
rm -rf libc/stdio/putw.os
rm -rf libc/stdio/putwchar.os
rm -rf libc/stdio/putwchar_unlocked.os
rm -rf libc/stdio/register_printf_function.os
rm -rf libc/stdio/remove.os
rm -rf libc/stdio/rewind.os
rm -rf libc/stdio/scanf.os
rm -rf libc/stdio/setbuf.os
rm -rf libc/stdio/setbuffer.os
rm -rf libc/stdio/setlinebuf.os
rm -rf libc/stdio/setvbuf.os
rm -rf libc/stdio/snprintf.os
rm -rf libc/stdio/sprintf.os
rm -rf libc/stdio/sscanf.os
rm -rf libc/stdio/swprintf.os
rm -rf libc/stdio/swscanf.os
rm -rf libc/stdio/tempnam.os
rm -rf libc/stdio/tmpfile.os
rm -rf libc/stdio/tmpnam.os
rm -rf libc/stdio/tmpnam_r.os
rm -rf libc/stdio/ungetc.os
rm -rf libc/stdio/ungetwc.os
rm -rf libc/stdio/vasprintf.os
rm -rf libc/stdio/vdprintf.os
rm -rf libc/stdio/vfprintf.os
rm -rf libc/stdio/vfscanf.os
rm -rf libc/stdio/vfwprintf.os
rm -rf libc/stdio/vfwscanf.os
rm -rf libc/stdio/vprintf.os
rm -rf libc/stdio/vscanf.os
rm -rf libc/stdio/vsnprintf.os
rm -rf libc/stdio/vsprintf.os
rm -rf libc/stdio/vsscanf.os
rm -rf libc/stdio/vswprintf.os
rm -rf libc/stdio/vswscanf.os
rm -rf libc/stdio/vwprintf.os
rm -rf libc/stdio/vwscanf.os
rm -rf libc/stdio/wprintf.os
rm -rf libc/stdio/wscanf.os
rm -rf libc/stdlib/.__cxa_atexit.os.dep
rm -rf libc/stdlib/.__cxa_finalize.os.dep
rm -rf libc/stdlib/.__exit_handler.os.dep
rm -rf libc/stdlib/.__fp_range_check.os.dep
rm -rf libc/stdlib/.__strtofpmax.os.dep
rm -rf libc/stdlib/.__uc_malloc.os.dep
rm -rf libc/stdlib/.__wcstofpmax.os.dep
rm -rf libc/stdlib/._stdlib_mb_cur_max.os.dep
rm -rf libc/stdlib/._stdlib_strto_l.os.dep
rm -rf libc/stdlib/._stdlib_strto_ll.os.dep
rm -rf libc/stdlib/._stdlib_wcsto_l.os.dep
rm -rf libc/stdlib/._stdlib_wcsto_ll.os.dep
rm -rf libc/stdlib/.a64l.os.dep
rm -rf libc/stdlib/.abort.os.dep
rm -rf libc/stdlib/.abs.os.dep
rm -rf libc/stdlib/.arc4random.os.dep
rm -rf libc/stdlib/.atexit.os.dep
rm -rf libc/stdlib/.atof.os.dep
rm -rf libc/stdlib/.atoi.os.dep
rm -rf libc/stdlib/.atol.os.dep
rm -rf libc/stdlib/.atoll.os.dep
rm -rf libc/stdlib/.bsearch.os.dep
rm -rf libc/stdlib/.div.os.dep
rm -rf libc/stdlib/.drand48-iter.os.dep
rm -rf libc/stdlib/.drand48.os.dep
rm -rf libc/stdlib/.drand48_r.os.dep
rm -rf libc/stdlib/.erand48.os.dep
rm -rf libc/stdlib/.erand48_r.os.dep
rm -rf libc/stdlib/.exit.os.dep
rm -rf libc/stdlib/.gcvt.os.dep
rm -rf libc/stdlib/.getenv.os.dep
rm -rf libc/stdlib/.getpt.os.dep
rm -rf libc/stdlib/.grantpt.os.dep
rm -rf libc/stdlib/.jrand48.os.dep
rm -rf libc/stdlib/.jrand48_r.os.dep
rm -rf libc/stdlib/.l64a.os.dep
rm -rf libc/stdlib/.labs.os.dep
rm -rf libc/stdlib/.ldiv.os.dep
rm -rf libc/stdlib/.llabs.os.dep
rm -rf libc/stdlib/.lldiv.os.dep
rm -rf libc/stdlib/.lrand48.os.dep
rm -rf libc/stdlib/.lrand48_r.os.dep
rm -rf libc/stdlib/.mblen.os.dep
rm -rf libc/stdlib/.mbstowcs.os.dep
rm -rf libc/stdlib/.mbtowc.os.dep
rm -rf libc/stdlib/.mkdtemp.os.dep
rm -rf libc/stdlib/.mkstemp.os.dep
rm -rf libc/stdlib/.mkstemp64.os.dep
rm -rf libc/stdlib/.mktemp.os.dep
rm -rf libc/stdlib/.mrand48.os.dep
rm -rf libc/stdlib/.mrand48_r.os.dep
rm -rf libc/stdlib/.nrand48.os.dep
rm -rf libc/stdlib/.nrand48_r.os.dep
rm -rf libc/stdlib/.old_atexit.os.dep
rm -rf libc/stdlib/.on_exit.os.dep
rm -rf libc/stdlib/.posix_memalign.os.dep
rm -rf libc/stdlib/.ptsname.os.dep
rm -rf libc/stdlib/.qsort.os.dep
rm -rf libc/stdlib/.rand.os.dep
rm -rf libc/stdlib/.rand_r.os.dep
rm -rf libc/stdlib/.random.os.dep
rm -rf libc/stdlib/.random_r.os.dep
rm -rf libc/stdlib/.realpath.os.dep
rm -rf libc/stdlib/.seed48.os.dep
rm -rf libc/stdlib/.seed48_r.os.dep
rm -rf libc/stdlib/.setenv.os.dep
rm -rf libc/stdlib/.srand48.os.dep
rm -rf libc/stdlib/.srand48_r.os.dep
rm -rf libc/stdlib/.strtod.os.dep
rm -rf libc/stdlib/.strtof.os.dep
rm -rf libc/stdlib/.strtol.os.dep
rm -rf libc/stdlib/.strtold.os.dep
rm -rf libc/stdlib/.strtoll.os.dep
rm -rf libc/stdlib/.strtoul.os.dep
rm -rf libc/stdlib/.strtoull.os.dep
rm -rf libc/stdlib/.system.os.dep
rm -rf libc/stdlib/.unlockpt.os.dep
rm -rf libc/stdlib/.valloc.os.dep
rm -rf libc/stdlib/.wcstod.os.dep
rm -rf libc/stdlib/.wcstof.os.dep
rm -rf libc/stdlib/.wcstol.os.dep
rm -rf libc/stdlib/.wcstold.os.dep
rm -rf libc/stdlib/.wcstoll.os.dep
rm -rf libc/stdlib/.wcstombs.os.dep
rm -rf libc/stdlib/.wcstoul.os.dep
rm -rf libc/stdlib/.wcstoull.os.dep
rm -rf libc/stdlib/.wctomb.os.dep
rm -rf libc/stdlib/__cxa_atexit.os
rm -rf libc/stdlib/__cxa_finalize.os
rm -rf libc/stdlib/__exit_handler.os
rm -rf libc/stdlib/__fp_range_check.os
rm -rf libc/stdlib/__strtofpmax.os
rm -rf libc/stdlib/__uc_malloc.os
rm -rf libc/stdlib/__wcstofpmax.os
rm -rf libc/stdlib/_stdlib_mb_cur_max.os
rm -rf libc/stdlib/_stdlib_strto_l.os
rm -rf libc/stdlib/_stdlib_strto_ll.os
rm -rf libc/stdlib/_stdlib_wcsto_l.os
rm -rf libc/stdlib/_stdlib_wcsto_ll.os
rm -rf libc/stdlib/a64l.os
rm -rf libc/stdlib/abort.os
rm -rf libc/stdlib/abs.os
rm -rf libc/stdlib/arc4random.os
rm -rf libc/stdlib/atexit.os
rm -rf libc/stdlib/atof.os
rm -rf libc/stdlib/atoi.os
rm -rf libc/stdlib/atol.os
rm -rf libc/stdlib/atoll.os
rm -rf libc/stdlib/bsearch.os
rm -rf libc/stdlib/div.os
rm -rf libc/stdlib/drand48-iter.os
rm -rf libc/stdlib/drand48.os
rm -rf libc/stdlib/drand48_r.os
rm -rf libc/stdlib/erand48.os
rm -rf libc/stdlib/erand48_r.os
rm -rf libc/stdlib/exit.os
rm -rf libc/stdlib/gcvt.os
rm -rf libc/stdlib/getenv.os
rm -rf libc/stdlib/getpt.os
rm -rf libc/stdlib/grantpt.os
rm -rf libc/stdlib/jrand48.os
rm -rf libc/stdlib/jrand48_r.os
rm -rf libc/stdlib/l64a.os
rm -rf libc/stdlib/labs.os
rm -rf libc/stdlib/ldiv.os
rm -rf libc/stdlib/llabs.os
rm -rf libc/stdlib/lldiv.os
rm -rf libc/stdlib/lrand48.os
rm -rf libc/stdlib/lrand48_r.os
rm -rf libc/stdlib/malloc/.calloc.os.dep
rm -rf libc/stdlib/malloc/.free.os.dep
rm -rf libc/stdlib/malloc/.heap_alloc.os.dep
rm -rf libc/stdlib/malloc/.heap_alloc_at.os.dep
rm -rf libc/stdlib/malloc/.heap_debug.os.dep
rm -rf libc/stdlib/malloc/.heap_free.os.dep
rm -rf libc/stdlib/malloc/.malloc.os.dep
rm -rf libc/stdlib/malloc/.malloc_debug.os.dep
rm -rf libc/stdlib/malloc/.memalign.os.dep
rm -rf libc/stdlib/malloc/.realloc.os.dep
rm -rf libc/stdlib/malloc/calloc.os
rm -rf libc/stdlib/malloc/free.os
rm -rf libc/stdlib/malloc/heap_alloc.os
rm -rf libc/stdlib/malloc/heap_alloc_at.os
rm -rf libc/stdlib/malloc/heap_debug.os
rm -rf libc/stdlib/malloc/heap_free.os
rm -rf libc/stdlib/malloc/malloc.os
rm -rf libc/stdlib/malloc/malloc_debug.os
rm -rf libc/stdlib/malloc/memalign.os
rm -rf libc/stdlib/malloc/realloc.os
rm -rf libc/stdlib/mblen.os
rm -rf libc/stdlib/mbstowcs.os
rm -rf libc/stdlib/mbtowc.os
rm -rf libc/stdlib/mkdtemp.os
rm -rf libc/stdlib/mkstemp.os
rm -rf libc/stdlib/mkstemp64.os
rm -rf libc/stdlib/mktemp.os
rm -rf libc/stdlib/mrand48.os
rm -rf libc/stdlib/mrand48_r.os
rm -rf libc/stdlib/nrand48.os
rm -rf libc/stdlib/nrand48_r.os
rm -rf libc/stdlib/old_atexit.os
rm -rf libc/stdlib/on_exit.os
rm -rf libc/stdlib/posix_memalign.os
rm -rf libc/stdlib/ptsname.os
rm -rf libc/stdlib/qsort.os
rm -rf libc/stdlib/rand.os
rm -rf libc/stdlib/rand_r.os
rm -rf libc/stdlib/random.os
rm -rf libc/stdlib/random_r.os
rm -rf libc/stdlib/realpath.os
rm -rf libc/stdlib/seed48.os
rm -rf libc/stdlib/seed48_r.os
rm -rf libc/stdlib/setenv.os
rm -rf libc/stdlib/srand48.os
rm -rf libc/stdlib/srand48_r.os
rm -rf libc/stdlib/strtod.os
rm -rf libc/stdlib/strtof.os
rm -rf libc/stdlib/strtol.os
rm -rf libc/stdlib/strtold.os
rm -rf libc/stdlib/strtoll.os
rm -rf libc/stdlib/strtoul.os
rm -rf libc/stdlib/strtoull.os
rm -rf libc/stdlib/system.os
rm -rf libc/stdlib/unlockpt.os
rm -rf libc/stdlib/valloc.os
rm -rf libc/stdlib/wcstod.os
rm -rf libc/stdlib/wcstof.os
rm -rf libc/stdlib/wcstol.os
rm -rf libc/stdlib/wcstold.os
rm -rf libc/stdlib/wcstoll.os
rm -rf libc/stdlib/wcstombs.os
rm -rf libc/stdlib/wcstoul.os
rm -rf libc/stdlib/wcstoull.os
rm -rf libc/stdlib/wctomb.os
rm -rf libc/string/.__glibc_strerror_r.os.dep
rm -rf libc/string/.__xpg_basename.os.dep
rm -rf libc/string/.__xpg_strerror_r.os.dep
rm -rf libc/string/._string_syserrmsgs.os.dep
rm -rf libc/string/._string_syssigmsgs.os.dep
rm -rf libc/string/.basename.os.dep
rm -rf libc/string/.bcopy.os.dep
rm -rf libc/string/.bzero.os.dep
rm -rf libc/string/.dirname.os.dep
rm -rf libc/string/.ffs.os.dep
rm -rf libc/string/.memccpy.os.dep
rm -rf libc/string/.psignal.os.dep
rm -rf libc/string/.stpcpy.os.dep
rm -rf libc/string/.stpncpy.os.dep
rm -rf libc/string/.strcasecmp.os.dep
rm -rf libc/string/.strcasestr.os.dep
rm -rf libc/string/.strdup.os.dep
rm -rf libc/string/.strerror.os.dep
rm -rf libc/string/.strlcat.os.dep
rm -rf libc/string/.strlcpy.os.dep
rm -rf libc/string/.strncasecmp.os.dep
rm -rf libc/string/.strndup.os.dep
rm -rf libc/string/.strpbrk.os.dep
rm -rf libc/string/.strsignal.os.dep
rm -rf libc/string/.strtok.os.dep
rm -rf libc/string/.sys_errlist.os.dep
rm -rf libc/string/.sys_siglist.os.dep
rm -rf libc/string/.wcpcpy.os.dep
rm -rf libc/string/.wcpncpy.os.dep
rm -rf libc/string/.wcscasecmp.os.dep
rm -rf libc/string/.wcscat.os.dep
rm -rf libc/string/.wcschr.os.dep
rm -rf libc/string/.wcschrnul.os.dep
rm -rf libc/string/.wcscmp.os.dep
rm -rf libc/string/.wcscpy.os.dep
rm -rf libc/string/.wcscspn.os.dep
rm -rf libc/string/.wcsdup.os.dep
rm -rf libc/string/.wcslcpy.os.dep
rm -rf libc/string/.wcslen.os.dep
rm -rf libc/string/.wcsncasecmp.os.dep
rm -rf libc/string/.wcsncat.os.dep
rm -rf libc/string/.wcsncmp.os.dep
rm -rf libc/string/.wcsncpy.os.dep
rm -rf libc/string/.wcsnlen.os.dep
rm -rf libc/string/.wcspbrk.os.dep
rm -rf libc/string/.wcsrchr.os.dep
rm -rf libc/string/.wcsspn.os.dep
rm -rf libc/string/.wcsstr.os.dep
rm -rf libc/string/.wcstok.os.dep
rm -rf libc/string/.wmemchr.os.dep
rm -rf libc/string/.wmemcmp.os.dep
rm -rf libc/string/.wmemcpy.os.dep
rm -rf libc/string/.wmemmove.os.dep
rm -rf libc/string/.wmempcpy.os.dep
rm -rf libc/string/.wmemset.os.dep
rm -rf libc/string/__glibc_strerror_r.os
rm -rf libc/string/__xpg_basename.os
rm -rf libc/string/__xpg_strerror_r.os
rm -rf libc/string/_string_syserrmsgs.os
rm -rf libc/string/_string_syssigmsgs.os
rm -rf libc/string/basename.os
rm -rf libc/string/bcopy.os
rm -rf libc/string/bzero.os
rm -rf libc/string/dirname.os
rm -rf libc/string/ffs.os
rm -rf libc/string/generic/.memchr.os.dep
rm -rf libc/string/generic/.memcmp.os.dep
rm -rf libc/string/generic/.memmem.os.dep
rm -rf libc/string/generic/.memmove.os.dep
rm -rf libc/string/generic/.mempcpy.os.dep
rm -rf libc/string/generic/.memrchr.os.dep
rm -rf libc/string/generic/.rawmemchr.os.dep
rm -rf libc/string/generic/.strcat.os.dep
rm -rf libc/string/generic/.strchr.os.dep
rm -rf libc/string/generic/.strchrnul.os.dep
rm -rf libc/string/generic/.strcpy.os.dep
rm -rf libc/string/generic/.strcspn.os.dep
rm -rf libc/string/generic/.strlen.os.dep
rm -rf libc/string/generic/.strncat.os.dep
rm -rf libc/string/generic/.strncmp.os.dep
rm -rf libc/string/generic/.strncpy.os.dep
rm -rf libc/string/generic/.strnlen.os.dep
rm -rf libc/string/generic/.strrchr.os.dep
rm -rf libc/string/generic/.strsep.os.dep
rm -rf libc/string/generic/.strspn.os.dep
rm -rf libc/string/generic/.strstr.os.dep
rm -rf libc/string/generic/.strtok_r.os.dep
rm -rf libc/string/generic/memchr.os
rm -rf libc/string/generic/memcmp.os
rm -rf libc/string/generic/memmem.os
rm -rf libc/string/generic/memmove.os
rm -rf libc/string/generic/mempcpy.os
rm -rf libc/string/generic/memrchr.os
rm -rf libc/string/generic/rawmemchr.os
rm -rf libc/string/generic/strcat.os
rm -rf libc/string/generic/strchr.os
rm -rf libc/string/generic/strchrnul.os
rm -rf libc/string/generic/strcpy.os
rm -rf libc/string/generic/strcspn.os
rm -rf libc/string/generic/strlen.os
rm -rf libc/string/generic/strncat.os
rm -rf libc/string/generic/strncmp.os
rm -rf libc/string/generic/strncpy.os
rm -rf libc/string/generic/strnlen.os
rm -rf libc/string/generic/strrchr.os
rm -rf libc/string/generic/strsep.os
rm -rf libc/string/generic/strspn.os
rm -rf libc/string/generic/strstr.os
rm -rf libc/string/generic/strtok_r.os
rm -rf libc/string/memccpy.os
rm -rf libc/string/psignal.os
rm -rf libc/string/stpcpy.os
rm -rf libc/string/stpncpy.os
rm -rf libc/string/strcasecmp.os
rm -rf libc/string/strcasestr.os
rm -rf libc/string/strdup.os
rm -rf libc/string/strerror.os
rm -rf libc/string/strlcat.os
rm -rf libc/string/strlcpy.os
rm -rf libc/string/strncasecmp.os
rm -rf libc/string/strndup.os
rm -rf libc/string/strpbrk.os
rm -rf libc/string/strsignal.os
rm -rf libc/string/strtok.os
rm -rf libc/string/sys_errlist.os
rm -rf libc/string/sys_siglist.os
rm -rf libc/string/ubicom32/.memcpy.os.dep
rm -rf libc/string/ubicom32/.memset.os.dep
rm -rf libc/string/ubicom32/.strcmp.os.dep
rm -rf libc/string/ubicom32/memcpy.os
rm -rf libc/string/ubicom32/memset.os
rm -rf libc/string/ubicom32/strcmp.os
rm -rf libc/string/wcpcpy.os
rm -rf libc/string/wcpncpy.os
rm -rf libc/string/wcscasecmp.os
rm -rf libc/string/wcscat.os
rm -rf libc/string/wcschr.os
rm -rf libc/string/wcschrnul.os
rm -rf libc/string/wcscmp.os
rm -rf libc/string/wcscpy.os
rm -rf libc/string/wcscspn.os
rm -rf libc/string/wcsdup.os
rm -rf libc/string/wcslcpy.os
rm -rf libc/string/wcslen.os
rm -rf libc/string/wcsncasecmp.os
rm -rf libc/string/wcsncat.os
rm -rf libc/string/wcsncmp.os
rm -rf libc/string/wcsncpy.os
rm -rf libc/string/wcsnlen.os
rm -rf libc/string/wcspbrk.os
rm -rf libc/string/wcsrchr.os
rm -rf libc/string/wcsspn.os
rm -rf libc/string/wcsstr.os
rm -rf libc/string/wcstok.os
rm -rf libc/string/wmemchr.os
rm -rf libc/string/wmemcmp.os
rm -rf libc/string/wmemcpy.os
rm -rf libc/string/wmemmove.os
rm -rf libc/string/wmempcpy.os
rm -rf libc/string/wmemset.os
rm -rf libc/sysdeps/linux/common/.__rt_sigtimedwait.os.dep
rm -rf libc/sysdeps/linux/common/.__socketcall.os.dep
rm -rf libc/sysdeps/linux/common/.__syscall_fcntl.os.dep
rm -rf libc/sysdeps/linux/common/.__syscall_fcntl64.os.dep
rm -rf libc/sysdeps/linux/common/.__syscall_rt_sigaction.os.dep
rm -rf libc/sysdeps/linux/common/.__syscall_sigaction.os.dep
rm -rf libc/sysdeps/linux/common/._exit.os.dep
rm -rf libc/sysdeps/linux/common/.access.os.dep
rm -rf libc/sysdeps/linux/common/.acct.os.dep
rm -rf libc/sysdeps/linux/common/.adjtimex.os.dep
rm -rf libc/sysdeps/linux/common/.alarm.os.dep
rm -rf libc/sysdeps/linux/common/.arch_prctl.os.dep
rm -rf libc/sysdeps/linux/common/.bdflush.os.dep
rm -rf libc/sysdeps/linux/common/.capget.os.dep
rm -rf libc/sysdeps/linux/common/.capset.os.dep
rm -rf libc/sysdeps/linux/common/.chdir.os.dep
rm -rf libc/sysdeps/linux/common/.chmod.os.dep
rm -rf libc/sysdeps/linux/common/.chown.os.dep
rm -rf libc/sysdeps/linux/common/.chroot.os.dep
rm -rf libc/sysdeps/linux/common/.clock_getres.os.dep
rm -rf libc/sysdeps/linux/common/.clock_gettime.os.dep
rm -rf libc/sysdeps/linux/common/.clock_settime.os.dep
rm -rf libc/sysdeps/linux/common/.close.os.dep
rm -rf libc/sysdeps/linux/common/.cmsg_nxthdr.os.dep
rm -rf libc/sysdeps/linux/common/.creat64.os.dep
rm -rf libc/sysdeps/linux/common/.delete_module.os.dep
rm -rf libc/sysdeps/linux/common/.dup.os.dep
rm -rf libc/sysdeps/linux/common/.dup2.os.dep
rm -rf libc/sysdeps/linux/common/.epoll.os.dep
rm -rf libc/sysdeps/linux/common/.execve.os.dep
rm -rf libc/sysdeps/linux/common/.fchdir.os.dep
rm -rf libc/sysdeps/linux/common/.fchmod.os.dep
rm -rf libc/sysdeps/linux/common/.fchown.os.dep
rm -rf libc/sysdeps/linux/common/.fdatasync.os.dep
rm -rf libc/sysdeps/linux/common/.flock.os.dep
rm -rf libc/sysdeps/linux/common/.fork.os.dep
rm -rf libc/sysdeps/linux/common/.fstat.os.dep
rm -rf libc/sysdeps/linux/common/.fstat64.os.dep
rm -rf libc/sysdeps/linux/common/.fstatfs.os.dep
rm -rf libc/sysdeps/linux/common/.fsync.os.dep
rm -rf libc/sysdeps/linux/common/.ftruncate.os.dep
rm -rf libc/sysdeps/linux/common/.ftruncate64.os.dep
rm -rf libc/sysdeps/linux/common/.getcwd.os.dep
rm -rf libc/sysdeps/linux/common/.getdents.os.dep
rm -rf libc/sysdeps/linux/common/.getdents64.os.dep
rm -rf libc/sysdeps/linux/common/.getdirname.os.dep
rm -rf libc/sysdeps/linux/common/.getdomainname.os.dep
rm -rf libc/sysdeps/linux/common/.getdtablesize.os.dep
rm -rf libc/sysdeps/linux/common/.getegid.os.dep
rm -rf libc/sysdeps/linux/common/.geteuid.os.dep
rm -rf libc/sysdeps/linux/common/.getgid.os.dep
rm -rf libc/sysdeps/linux/common/.getgroups.os.dep
rm -rf libc/sysdeps/linux/common/.gethostname.os.dep
rm -rf libc/sysdeps/linux/common/.getitimer.os.dep
rm -rf libc/sysdeps/linux/common/.getpagesize.os.dep
rm -rf libc/sysdeps/linux/common/.getpgid.os.dep
rm -rf libc/sysdeps/linux/common/.getpgrp.os.dep
rm -rf libc/sysdeps/linux/common/.getpid.os.dep
rm -rf libc/sysdeps/linux/common/.getppid.os.dep
rm -rf libc/sysdeps/linux/common/.getpriority.os.dep
rm -rf libc/sysdeps/linux/common/.getresgid.os.dep
rm -rf libc/sysdeps/linux/common/.getresuid.os.dep
rm -rf libc/sysdeps/linux/common/.getrlimit.os.dep
rm -rf libc/sysdeps/linux/common/.getrlimit64.os.dep
rm -rf libc/sysdeps/linux/common/.getrusage.os.dep
rm -rf libc/sysdeps/linux/common/.getsid.os.dep
rm -rf libc/sysdeps/linux/common/.gettimeofday.os.dep
rm -rf libc/sysdeps/linux/common/.getuid.os.dep
rm -rf libc/sysdeps/linux/common/.init_module.os.dep
rm -rf libc/sysdeps/linux/common/.inotify.os.dep
rm -rf libc/sysdeps/linux/common/.ioctl.os.dep
rm -rf libc/sysdeps/linux/common/.ioperm.os.dep
rm -rf libc/sysdeps/linux/common/.iopl.os.dep
rm -rf libc/sysdeps/linux/common/.kill.os.dep
rm -rf libc/sysdeps/linux/common/.klogctl.os.dep
rm -rf libc/sysdeps/linux/common/.lchown.os.dep
rm -rf libc/sysdeps/linux/common/.link.os.dep
rm -rf libc/sysdeps/linux/common/.llseek.os.dep
rm -rf libc/sysdeps/linux/common/.longjmp.os.dep
rm -rf libc/sysdeps/linux/common/.lseek.os.dep
rm -rf libc/sysdeps/linux/common/.lstat.os.dep
rm -rf libc/sysdeps/linux/common/.lstat64.os.dep
rm -rf libc/sysdeps/linux/common/.madvise.os.dep
rm -rf libc/sysdeps/linux/common/.mincore.os.dep
rm -rf libc/sysdeps/linux/common/.mkdir.os.dep
rm -rf libc/sysdeps/linux/common/.mkfifo.os.dep
rm -rf libc/sysdeps/linux/common/.mknod.os.dep
rm -rf libc/sysdeps/linux/common/.mlock.os.dep
rm -rf libc/sysdeps/linux/common/.mlockall.os.dep
rm -rf libc/sysdeps/linux/common/.mmap.os.dep
rm -rf libc/sysdeps/linux/common/.mmap64.os.dep
rm -rf libc/sysdeps/linux/common/.modify_ldt.os.dep
rm -rf libc/sysdeps/linux/common/.mount.os.dep
rm -rf libc/sysdeps/linux/common/.mprotect.os.dep
rm -rf libc/sysdeps/linux/common/.mremap.os.dep
rm -rf libc/sysdeps/linux/common/.msync.os.dep
rm -rf libc/sysdeps/linux/common/.munlock.os.dep
rm -rf libc/sysdeps/linux/common/.munlockall.os.dep
rm -rf libc/sysdeps/linux/common/.munmap.os.dep
rm -rf libc/sysdeps/linux/common/.nanosleep.os.dep
rm -rf libc/sysdeps/linux/common/.nice.os.dep
rm -rf libc/sysdeps/linux/common/.noophooks.os.dep
rm -rf libc/sysdeps/linux/common/.ntp_gettime.os.dep
rm -rf libc/sysdeps/linux/common/.open.os.dep
rm -rf libc/sysdeps/linux/common/.open64.os.dep
rm -rf libc/sysdeps/linux/common/.pause.os.dep
rm -rf libc/sysdeps/linux/common/.personality.os.dep
rm -rf libc/sysdeps/linux/common/.pipe.os.dep
rm -rf libc/sysdeps/linux/common/.pivot_root.os.dep
rm -rf libc/sysdeps/linux/common/.poll.os.dep
rm -rf libc/sysdeps/linux/common/.posix_fadvise.os.dep
rm -rf libc/sysdeps/linux/common/.posix_fadvise64.os.dep
rm -rf libc/sysdeps/linux/common/.ppoll.os.dep
rm -rf libc/sysdeps/linux/common/.prctl.os.dep
rm -rf libc/sysdeps/linux/common/.pread_write.os.dep
rm -rf libc/sysdeps/linux/common/.pselect.os.dep
rm -rf libc/sysdeps/linux/common/.ptrace.os.dep
rm -rf libc/sysdeps/linux/common/.quotactl.os.dep
rm -rf libc/sysdeps/linux/common/.read.os.dep
rm -rf libc/sysdeps/linux/common/.readahead.os.dep
rm -rf libc/sysdeps/linux/common/.readlink.os.dep
rm -rf libc/sysdeps/linux/common/.readv.os.dep
rm -rf libc/sysdeps/linux/common/.reboot.os.dep
rm -rf libc/sysdeps/linux/common/.remap_file_pages.os.dep
rm -rf libc/sysdeps/linux/common/.rename.os.dep
rm -rf libc/sysdeps/linux/common/.rmdir.os.dep
rm -rf libc/sysdeps/linux/common/.sbrk.os.dep
rm -rf libc/sysdeps/linux/common/.sched_get_priority_max.os.dep
rm -rf libc/sysdeps/linux/common/.sched_get_priority_min.os.dep
rm -rf libc/sysdeps/linux/common/.sched_getaffinity.os.dep
rm -rf libc/sysdeps/linux/common/.sched_getparam.os.dep
rm -rf libc/sysdeps/linux/common/.sched_getscheduler.os.dep
rm -rf libc/sysdeps/linux/common/.sched_rr_get_interval.os.dep
rm -rf libc/sysdeps/linux/common/.sched_setaffinity.os.dep
rm -rf libc/sysdeps/linux/common/.sched_setparam.os.dep
rm -rf libc/sysdeps/linux/common/.sched_setscheduler.os.dep
rm -rf libc/sysdeps/linux/common/.sched_yield.os.dep
rm -rf libc/sysdeps/linux/common/.select.os.dep
rm -rf libc/sysdeps/linux/common/.sendfile.os.dep
rm -rf libc/sysdeps/linux/common/.sendfile64.os.dep
rm -rf libc/sysdeps/linux/common/.setdomainname.os.dep
rm -rf libc/sysdeps/linux/common/.setegid.os.dep
rm -rf libc/sysdeps/linux/common/.seteuid.os.dep
rm -rf libc/sysdeps/linux/common/.setfsgid.os.dep
rm -rf libc/sysdeps/linux/common/.setfsuid.os.dep
rm -rf libc/sysdeps/linux/common/.setgid.os.dep
rm -rf libc/sysdeps/linux/common/.setgroups.os.dep
rm -rf libc/sysdeps/linux/common/.sethostname.os.dep
rm -rf libc/sysdeps/linux/common/.setitimer.os.dep
rm -rf libc/sysdeps/linux/common/.setpgid.os.dep
rm -rf libc/sysdeps/linux/common/.setpgrp.os.dep
rm -rf libc/sysdeps/linux/common/.setpriority.os.dep
rm -rf libc/sysdeps/linux/common/.setregid.os.dep
rm -rf libc/sysdeps/linux/common/.setresgid.os.dep
rm -rf libc/sysdeps/linux/common/.setresuid.os.dep
rm -rf libc/sysdeps/linux/common/.setreuid.os.dep
rm -rf libc/sysdeps/linux/common/.setrlimit.os.dep
rm -rf libc/sysdeps/linux/common/.setrlimit64.os.dep
rm -rf libc/sysdeps/linux/common/.setsid.os.dep
rm -rf libc/sysdeps/linux/common/.settimeofday.os.dep
rm -rf libc/sysdeps/linux/common/.setuid.os.dep
rm -rf libc/sysdeps/linux/common/.sigaltstack.os.dep
rm -rf libc/sysdeps/linux/common/.signalfd.os.dep
rm -rf libc/sysdeps/linux/common/.sigpending.os.dep
rm -rf libc/sysdeps/linux/common/.sigprocmask.os.dep
rm -rf libc/sysdeps/linux/common/.sigqueue.os.dep
rm -rf libc/sysdeps/linux/common/.sigsuspend.os.dep
rm -rf libc/sysdeps/linux/common/.splice.os.dep
rm -rf libc/sysdeps/linux/common/.stat.os.dep
rm -rf libc/sysdeps/linux/common/.stat64.os.dep
rm -rf libc/sysdeps/linux/common/.statfs.os.dep
rm -rf libc/sysdeps/linux/common/.stime.os.dep
rm -rf libc/sysdeps/linux/common/.swapoff.os.dep
rm -rf libc/sysdeps/linux/common/.swapon.os.dep
rm -rf libc/sysdeps/linux/common/.symlink.os.dep
rm -rf libc/sysdeps/linux/common/.sync.os.dep
rm -rf libc/sysdeps/linux/common/.sync_file_range.os.dep
rm -rf libc/sysdeps/linux/common/.sysctl.os.dep
rm -rf libc/sysdeps/linux/common/.sysfs.os.dep
rm -rf libc/sysdeps/linux/common/.sysinfo.os.dep
rm -rf libc/sysdeps/linux/common/.tee.os.dep
rm -rf libc/sysdeps/linux/common/.time.os.dep
rm -rf libc/sysdeps/linux/common/.times.os.dep
rm -rf libc/sysdeps/linux/common/.truncate.os.dep
rm -rf libc/sysdeps/linux/common/.truncate64.os.dep
rm -rf libc/sysdeps/linux/common/.ulimit.os.dep
rm -rf libc/sysdeps/linux/common/.umask.os.dep
rm -rf libc/sysdeps/linux/common/.umount.os.dep
rm -rf libc/sysdeps/linux/common/.umount2.os.dep
rm -rf libc/sysdeps/linux/common/.uname.os.dep
rm -rf libc/sysdeps/linux/common/.unlink.os.dep
rm -rf libc/sysdeps/linux/common/.uselib.os.dep
rm -rf libc/sysdeps/linux/common/.ustat.os.dep
rm -rf libc/sysdeps/linux/common/.utime.os.dep
rm -rf libc/sysdeps/linux/common/.utimes.os.dep
rm -rf libc/sysdeps/linux/common/.vhangup.os.dep
rm -rf libc/sysdeps/linux/common/.vmsplice.os.dep
rm -rf libc/sysdeps/linux/common/.wait.os.dep
rm -rf libc/sysdeps/linux/common/.wait3.os.dep
rm -rf libc/sysdeps/linux/common/.wait4.os.dep
rm -rf libc/sysdeps/linux/common/.waitid.os.dep
rm -rf libc/sysdeps/linux/common/.waitpid.os.dep
rm -rf libc/sysdeps/linux/common/.write.os.dep
rm -rf libc/sysdeps/linux/common/.writev.os.dep
rm -rf libc/sysdeps/linux/common/.xattr.os.dep
rm -rf libc/sysdeps/linux/common/.xstatconv.os.dep
rm -rf libc/sysdeps/linux/common/__rt_sigtimedwait.os
rm -rf libc/sysdeps/linux/common/__socketcall.os
rm -rf libc/sysdeps/linux/common/__syscall_fcntl.os
rm -rf libc/sysdeps/linux/common/__syscall_fcntl64.os
rm -rf libc/sysdeps/linux/common/__syscall_rt_sigaction.os
rm -rf libc/sysdeps/linux/common/__syscall_sigaction.os
rm -rf libc/sysdeps/linux/common/_exit.os
rm -rf libc/sysdeps/linux/common/access.os
rm -rf libc/sysdeps/linux/common/acct.os
rm -rf libc/sysdeps/linux/common/adjtimex.os
rm -rf libc/sysdeps/linux/common/alarm.os
rm -rf libc/sysdeps/linux/common/arch_prctl.os
rm -rf libc/sysdeps/linux/common/bdflush.os
rm -rf libc/sysdeps/linux/common/capget.os
rm -rf libc/sysdeps/linux/common/capset.os
rm -rf libc/sysdeps/linux/common/chdir.os
rm -rf libc/sysdeps/linux/common/chmod.os
rm -rf libc/sysdeps/linux/common/chown.os
rm -rf libc/sysdeps/linux/common/chroot.os
rm -rf libc/sysdeps/linux/common/clock_getres.os
rm -rf libc/sysdeps/linux/common/clock_gettime.os
rm -rf libc/sysdeps/linux/common/clock_settime.os
rm -rf libc/sysdeps/linux/common/close.os
rm -rf libc/sysdeps/linux/common/cmsg_nxthdr.os
rm -rf libc/sysdeps/linux/common/creat64.os
rm -rf libc/sysdeps/linux/common/delete_module.os
rm -rf libc/sysdeps/linux/common/dup.os
rm -rf libc/sysdeps/linux/common/dup2.os
rm -rf libc/sysdeps/linux/common/epoll.os
rm -rf libc/sysdeps/linux/common/execve.os
rm -rf libc/sysdeps/linux/common/fchdir.os
rm -rf libc/sysdeps/linux/common/fchmod.os
rm -rf libc/sysdeps/linux/common/fchown.os
rm -rf libc/sysdeps/linux/common/fdatasync.os
rm -rf libc/sysdeps/linux/common/flock.os
rm -rf libc/sysdeps/linux/common/fork.os
rm -rf libc/sysdeps/linux/common/fstat.os
rm -rf libc/sysdeps/linux/common/fstat64.os
rm -rf libc/sysdeps/linux/common/fstatfs.os
rm -rf libc/sysdeps/linux/common/fsync.os
rm -rf libc/sysdeps/linux/common/ftruncate.os
rm -rf libc/sysdeps/linux/common/ftruncate64.os
rm -rf libc/sysdeps/linux/common/getcwd.os
rm -rf libc/sysdeps/linux/common/getdents.os
rm -rf libc/sysdeps/linux/common/getdents64.os
rm -rf libc/sysdeps/linux/common/getdirname.os
rm -rf libc/sysdeps/linux/common/getdomainname.os
rm -rf libc/sysdeps/linux/common/getdtablesize.os
rm -rf libc/sysdeps/linux/common/getegid.os
rm -rf libc/sysdeps/linux/common/geteuid.os
rm -rf libc/sysdeps/linux/common/getgid.os
rm -rf libc/sysdeps/linux/common/getgroups.os
rm -rf libc/sysdeps/linux/common/gethostname.os
rm -rf libc/sysdeps/linux/common/getitimer.os
rm -rf libc/sysdeps/linux/common/getpagesize.os
rm -rf libc/sysdeps/linux/common/getpgid.os
rm -rf libc/sysdeps/linux/common/getpgrp.os
rm -rf libc/sysdeps/linux/common/getpid.os
rm -rf libc/sysdeps/linux/common/getppid.os
rm -rf libc/sysdeps/linux/common/getpriority.os
rm -rf libc/sysdeps/linux/common/getresgid.os
rm -rf libc/sysdeps/linux/common/getresuid.os
rm -rf libc/sysdeps/linux/common/getrlimit.os
rm -rf libc/sysdeps/linux/common/getrlimit64.os
rm -rf libc/sysdeps/linux/common/getrusage.os
rm -rf libc/sysdeps/linux/common/getsid.os
rm -rf libc/sysdeps/linux/common/gettimeofday.os
rm -rf libc/sysdeps/linux/common/getuid.os
rm -rf libc/sysdeps/linux/common/init_module.os
rm -rf libc/sysdeps/linux/common/inotify.os
rm -rf libc/sysdeps/linux/common/ioctl.os
rm -rf libc/sysdeps/linux/common/ioperm.os
rm -rf libc/sysdeps/linux/common/iopl.os
rm -rf libc/sysdeps/linux/common/kill.os
rm -rf libc/sysdeps/linux/common/klogctl.os
rm -rf libc/sysdeps/linux/common/lchown.os
rm -rf libc/sysdeps/linux/common/link.os
rm -rf libc/sysdeps/linux/common/llseek.os
rm -rf libc/sysdeps/linux/common/longjmp.os
rm -rf libc/sysdeps/linux/common/lseek.os
rm -rf libc/sysdeps/linux/common/lstat.os
rm -rf libc/sysdeps/linux/common/lstat64.os
rm -rf libc/sysdeps/linux/common/madvise.os
rm -rf libc/sysdeps/linux/common/mincore.os
rm -rf libc/sysdeps/linux/common/mkdir.os
rm -rf libc/sysdeps/linux/common/mkfifo.os
rm -rf libc/sysdeps/linux/common/mknod.os
rm -rf libc/sysdeps/linux/common/mlock.os
rm -rf libc/sysdeps/linux/common/mlockall.os
rm -rf libc/sysdeps/linux/common/mmap.os
rm -rf libc/sysdeps/linux/common/mmap64.os
rm -rf libc/sysdeps/linux/common/modify_ldt.os
rm -rf libc/sysdeps/linux/common/mount.os
rm -rf libc/sysdeps/linux/common/mprotect.os
rm -rf libc/sysdeps/linux/common/mremap.os
rm -rf libc/sysdeps/linux/common/msync.os
rm -rf libc/sysdeps/linux/common/munlock.os
rm -rf libc/sysdeps/linux/common/munlockall.os
rm -rf libc/sysdeps/linux/common/munmap.os
rm -rf libc/sysdeps/linux/common/nanosleep.os
rm -rf libc/sysdeps/linux/common/nice.os
rm -rf libc/sysdeps/linux/common/noophooks.os
rm -rf libc/sysdeps/linux/common/ntp_gettime.os
rm -rf libc/sysdeps/linux/common/open.os
rm -rf libc/sysdeps/linux/common/open64.os
rm -rf libc/sysdeps/linux/common/pause.os
rm -rf libc/sysdeps/linux/common/personality.os
rm -rf libc/sysdeps/linux/common/pipe.os
rm -rf libc/sysdeps/linux/common/pivot_root.os
rm -rf libc/sysdeps/linux/common/poll.os
rm -rf libc/sysdeps/linux/common/posix_fadvise.os
rm -rf libc/sysdeps/linux/common/posix_fadvise64.os
rm -rf libc/sysdeps/linux/common/ppoll.os
rm -rf libc/sysdeps/linux/common/prctl.os
rm -rf libc/sysdeps/linux/common/pread_write.os
rm -rf libc/sysdeps/linux/common/pselect.os
rm -rf libc/sysdeps/linux/common/ptrace.os
rm -rf libc/sysdeps/linux/common/quotactl.os
rm -rf libc/sysdeps/linux/common/read.os
rm -rf libc/sysdeps/linux/common/readahead.os
rm -rf libc/sysdeps/linux/common/readlink.os
rm -rf libc/sysdeps/linux/common/readv.os
rm -rf libc/sysdeps/linux/common/reboot.os
rm -rf libc/sysdeps/linux/common/remap_file_pages.os
rm -rf libc/sysdeps/linux/common/rename.os
rm -rf libc/sysdeps/linux/common/rmdir.os
rm -rf libc/sysdeps/linux/common/sbrk.os
rm -rf libc/sysdeps/linux/common/sched_get_priority_max.os
rm -rf libc/sysdeps/linux/common/sched_get_priority_min.os
rm -rf libc/sysdeps/linux/common/sched_getaffinity.os
rm -rf libc/sysdeps/linux/common/sched_getparam.os
rm -rf libc/sysdeps/linux/common/sched_getscheduler.os
rm -rf libc/sysdeps/linux/common/sched_rr_get_interval.os
rm -rf libc/sysdeps/linux/common/sched_setaffinity.os
rm -rf libc/sysdeps/linux/common/sched_setparam.os
rm -rf libc/sysdeps/linux/common/sched_setscheduler.os
rm -rf libc/sysdeps/linux/common/sched_yield.os
rm -rf libc/sysdeps/linux/common/select.os
rm -rf libc/sysdeps/linux/common/sendfile.os
rm -rf libc/sysdeps/linux/common/sendfile64.os
rm -rf libc/sysdeps/linux/common/setdomainname.os
rm -rf libc/sysdeps/linux/common/setegid.os
rm -rf libc/sysdeps/linux/common/seteuid.os
rm -rf libc/sysdeps/linux/common/setfsgid.os
rm -rf libc/sysdeps/linux/common/setfsuid.os
rm -rf libc/sysdeps/linux/common/setgid.os
rm -rf libc/sysdeps/linux/common/setgroups.os
rm -rf libc/sysdeps/linux/common/sethostname.os
rm -rf libc/sysdeps/linux/common/setitimer.os
rm -rf libc/sysdeps/linux/common/setpgid.os
rm -rf libc/sysdeps/linux/common/setpgrp.os
rm -rf libc/sysdeps/linux/common/setpriority.os
rm -rf libc/sysdeps/linux/common/setregid.os
rm -rf libc/sysdeps/linux/common/setresgid.os
rm -rf libc/sysdeps/linux/common/setresuid.os
rm -rf libc/sysdeps/linux/common/setreuid.os
rm -rf libc/sysdeps/linux/common/setrlimit.os
rm -rf libc/sysdeps/linux/common/setrlimit64.os
rm -rf libc/sysdeps/linux/common/setsid.os
rm -rf libc/sysdeps/linux/common/settimeofday.os
rm -rf libc/sysdeps/linux/common/setuid.os
rm -rf libc/sysdeps/linux/common/sigaltstack.os
rm -rf libc/sysdeps/linux/common/signalfd.os
rm -rf libc/sysdeps/linux/common/sigpending.os
rm -rf libc/sysdeps/linux/common/sigprocmask.os
rm -rf libc/sysdeps/linux/common/sigqueue.os
rm -rf libc/sysdeps/linux/common/sigsuspend.os
rm -rf libc/sysdeps/linux/common/splice.os
rm -rf libc/sysdeps/linux/common/stat.os
rm -rf libc/sysdeps/linux/common/stat64.os
rm -rf libc/sysdeps/linux/common/statfs.os
rm -rf libc/sysdeps/linux/common/stime.os
rm -rf libc/sysdeps/linux/common/swapoff.os
rm -rf libc/sysdeps/linux/common/swapon.os
rm -rf libc/sysdeps/linux/common/symlink.os
rm -rf libc/sysdeps/linux/common/sync.os
rm -rf libc/sysdeps/linux/common/sync_file_range.os
rm -rf libc/sysdeps/linux/common/sysctl.os
rm -rf libc/sysdeps/linux/common/sysfs.os
rm -rf libc/sysdeps/linux/common/sysinfo.os
rm -rf libc/sysdeps/linux/common/tee.os
rm -rf libc/sysdeps/linux/common/time.os
rm -rf libc/sysdeps/linux/common/times.os
rm -rf libc/sysdeps/linux/common/truncate.os
rm -rf libc/sysdeps/linux/common/truncate64.os
rm -rf libc/sysdeps/linux/common/ulimit.os
rm -rf libc/sysdeps/linux/common/umask.os
rm -rf libc/sysdeps/linux/common/umount.os
rm -rf libc/sysdeps/linux/common/umount2.os
rm -rf libc/sysdeps/linux/common/uname.os
rm -rf libc/sysdeps/linux/common/unlink.os
rm -rf libc/sysdeps/linux/common/uselib.os
rm -rf libc/sysdeps/linux/common/ustat.os
rm -rf libc/sysdeps/linux/common/utime.os
rm -rf libc/sysdeps/linux/common/utimes.os
rm -rf libc/sysdeps/linux/common/vhangup.os
rm -rf libc/sysdeps/linux/common/vmsplice.os
rm -rf libc/sysdeps/linux/common/wait.os
rm -rf libc/sysdeps/linux/common/wait3.os
rm -rf libc/sysdeps/linux/common/wait4.os
rm -rf libc/sysdeps/linux/common/waitid.os
rm -rf libc/sysdeps/linux/common/waitpid.os
rm -rf libc/sysdeps/linux/common/write.os
rm -rf libc/sysdeps/linux/common/writev.os
rm -rf libc/sysdeps/linux/common/xattr.os
rm -rf libc/sysdeps/linux/common/xstatconv.os
rm -rf libc/sysdeps/linux/ubicom32/.__syscall_error.os.dep
rm -rf libc/sysdeps/linux/ubicom32/.brk.os.dep
rm -rf libc/sysdeps/linux/ubicom32/.clone.os.dep
rm -rf libc/sysdeps/linux/ubicom32/.setjmp.os.dep
rm -rf libc/sysdeps/linux/ubicom32/.syscall.os.dep
rm -rf libc/sysdeps/linux/ubicom32/.vfork.os.dep
rm -rf libc/sysdeps/linux/ubicom32/__syscall_error.os
rm -rf libc/sysdeps/linux/ubicom32/brk.os
rm -rf libc/sysdeps/linux/ubicom32/clone.os
rm -rf libc/sysdeps/linux/ubicom32/setjmp.os
rm -rf libc/sysdeps/linux/ubicom32/syscall.os
rm -rf libc/sysdeps/linux/ubicom32/vfork.os
rm -rf libc/termios/.cfmakeraw.os.dep
rm -rf libc/termios/.cfsetspeed.os.dep
rm -rf libc/termios/.isatty.os.dep
rm -rf libc/termios/.speed.os.dep
rm -rf libc/termios/.tcdrain.os.dep
rm -rf libc/termios/.tcflow.os.dep
rm -rf libc/termios/.tcflush.os.dep
rm -rf libc/termios/.tcgetattr.os.dep
rm -rf libc/termios/.tcgetpgrp.os.dep
rm -rf libc/termios/.tcgetsid.os.dep
rm -rf libc/termios/.tcsendbrk.os.dep
rm -rf libc/termios/.tcsetattr.os.dep
rm -rf libc/termios/.tcsetpgrp.os.dep
rm -rf libc/termios/.ttyname.os.dep
rm -rf libc/termios/cfmakeraw.os
rm -rf libc/termios/cfsetspeed.os
rm -rf libc/termios/isatty.os
rm -rf libc/termios/speed.os
rm -rf libc/termios/tcdrain.os
rm -rf libc/termios/tcflow.os
rm -rf libc/termios/tcflush.os
rm -rf libc/termios/tcgetattr.os
rm -rf libc/termios/tcgetpgrp.os
rm -rf libc/termios/tcgetsid.os
rm -rf libc/termios/tcsendbrk.os
rm -rf libc/termios/tcsetattr.os
rm -rf libc/termios/tcsetpgrp.os
rm -rf libc/termios/ttyname.os
rm -rf libc/unistd/.__exec_alloc.os.dep
rm -rf libc/unistd/.confstr.os.dep
rm -rf libc/unistd/.daemon.os.dep
rm -rf libc/unistd/.execl.os.dep
rm -rf libc/unistd/.execle.os.dep
rm -rf libc/unistd/.execlp.os.dep
rm -rf libc/unistd/.execv.os.dep
rm -rf libc/unistd/.execvp.os.dep
rm -rf libc/unistd/.fpathconf.os.dep
rm -rf libc/unistd/.getlogin.os.dep
rm -rf libc/unistd/.getopt.os.dep
rm -rf libc/unistd/.getpass.os.dep
rm -rf libc/unistd/.getsubopt.os.dep
rm -rf libc/unistd/.pathconf.os.dep
rm -rf libc/unistd/.sleep.os.dep
rm -rf libc/unistd/.swab.os.dep
rm -rf libc/unistd/.sysconf.os.dep
rm -rf libc/unistd/.ualarm.os.dep
rm -rf libc/unistd/.usershell.os.dep
rm -rf libc/unistd/.usleep.os.dep
rm -rf libc/unistd/__exec_alloc.os
rm -rf libc/unistd/confstr.os
rm -rf libc/unistd/daemon.os
rm -rf libc/unistd/execl.os
rm -rf libc/unistd/execle.os
rm -rf libc/unistd/execlp.os
rm -rf libc/unistd/execv.os
rm -rf libc/unistd/execvp.os
rm -rf libc/unistd/fpathconf.os
rm -rf libc/unistd/getlogin.os
rm -rf libc/unistd/getopt.os
rm -rf libc/unistd/getpass.os
rm -rf libc/unistd/getsubopt.os
rm -rf libc/unistd/pathconf.os
rm -rf libc/unistd/sleep.os
rm -rf libc/unistd/swab.os
rm -rf libc/unistd/sysconf.os
rm -rf libc/unistd/ualarm.os
rm -rf libc/unistd/usershell.os
rm -rf libc/unistd/usleep.os
rm -rf libcrypt/.crypt.os.dep
rm -rf libcrypt/.des.os.dep
rm -rf libcrypt/.md5.os.dep
rm -rf libcrypt/crypt.os
rm -rf libcrypt/des.os
rm -rf libcrypt/md5.os
rm -rf libm/.acosf.os.dep
rm -rf libm/.acoshf.os.dep
rm -rf libm/.asinf.os.dep
rm -rf libm/.asinhf.os.dep
rm -rf libm/.atan2f.os.dep
rm -rf libm/.atanf.os.dep
rm -rf libm/.atanhf.os.dep
rm -rf libm/.cabsf.os.dep
rm -rf libm/.carg.os.dep
rm -rf libm/.cargf.os.dep
rm -rf libm/.cbrtf.os.dep
rm -rf libm/.ceilf.os.dep
rm -rf libm/.copysignf.os.dep
rm -rf libm/.cosf.os.dep
rm -rf libm/.coshf.os.dep
rm -rf libm/.e_acos.os.dep
rm -rf libm/.e_acosh.os.dep
rm -rf libm/.e_asin.os.dep
rm -rf libm/.e_atan2.os.dep
rm -rf libm/.e_atanh.os.dep
rm -rf libm/.e_cosh.os.dep
rm -rf libm/.e_exp.os.dep
rm -rf libm/.e_fmod.os.dep
rm -rf libm/.e_gamma.os.dep
rm -rf libm/.e_gamma_r.os.dep
rm -rf libm/.e_hypot.os.dep
rm -rf libm/.e_j0.os.dep
rm -rf libm/.e_j1.os.dep
rm -rf libm/.e_jn.os.dep
rm -rf libm/.e_lgamma.os.dep
rm -rf libm/.e_lgamma_r.os.dep
rm -rf libm/.e_log.os.dep
rm -rf libm/.e_log10.os.dep
rm -rf libm/.e_log2.os.dep
rm -rf libm/.e_pow.os.dep
rm -rf libm/.e_rem_pio2.os.dep
rm -rf libm/.e_remainder.os.dep
rm -rf libm/.e_scalb.os.dep
rm -rf libm/.e_sinh.os.dep
rm -rf libm/.e_sqrt.os.dep
rm -rf libm/.erfcf.os.dep
rm -rf libm/.erff.os.dep
rm -rf libm/.exp2f.os.dep
rm -rf libm/.expf.os.dep
rm -rf libm/.expm1f.os.dep
rm -rf libm/.fabsf.os.dep
rm -rf libm/.fdimf.os.dep
rm -rf libm/.floorf.os.dep
rm -rf libm/.fmaf.os.dep
rm -rf libm/.fmaxf.os.dep
rm -rf libm/.fminf.os.dep
rm -rf libm/.fmodf.os.dep
rm -rf libm/.frexpf.os.dep
rm -rf libm/.gammaf.os.dep
rm -rf libm/.hypotf.os.dep
rm -rf libm/.ilogbf.os.dep
rm -rf libm/.k_cos.os.dep
rm -rf libm/.k_rem_pio2.os.dep
rm -rf libm/.k_sin.os.dep
rm -rf libm/.k_standard.os.dep
rm -rf libm/.k_tan.os.dep
rm -rf libm/.ldexpf.os.dep
rm -rf libm/.lgammaf.os.dep
rm -rf libm/.llrintf.os.dep
rm -rf libm/.llroundf.os.dep
rm -rf libm/.log10f.os.dep
rm -rf libm/.log1pf.os.dep
rm -rf libm/.log2f.os.dep
rm -rf libm/.logbf.os.dep
rm -rf libm/.logf.os.dep
rm -rf libm/.lrintf.os.dep
rm -rf libm/.lroundf.os.dep
rm -rf libm/.modff.os.dep
rm -rf libm/.nan.os.dep
rm -rf libm/.nearbyintf.os.dep
rm -rf libm/.nextafterf.os.dep
rm -rf libm/.powf.os.dep
rm -rf libm/.remainderf.os.dep
rm -rf libm/.remquof.os.dep
rm -rf libm/.rintf.os.dep
rm -rf libm/.roundf.os.dep
rm -rf libm/.s_asinh.os.dep
rm -rf libm/.s_atan.os.dep
rm -rf libm/.s_cbrt.os.dep
rm -rf libm/.s_ceil.os.dep
rm -rf libm/.s_copysign.os.dep
rm -rf libm/.s_cos.os.dep
rm -rf libm/.s_erf.os.dep
rm -rf libm/.s_expm1.os.dep
rm -rf libm/.s_fabs.os.dep
rm -rf libm/.s_fdim.os.dep
rm -rf libm/.s_finite.os.dep
rm -rf libm/.s_finitef.os.dep
rm -rf libm/.s_floor.os.dep
rm -rf libm/.s_fma.os.dep
rm -rf libm/.s_fmax.os.dep
rm -rf libm/.s_fmin.os.dep
rm -rf libm/.s_fpclassify.os.dep
rm -rf libm/.s_fpclassifyf.os.dep
rm -rf libm/.s_frexp.os.dep
rm -rf libm/.s_ilogb.os.dep
rm -rf libm/.s_isinf.os.dep
rm -rf libm/.s_isinff.os.dep
rm -rf libm/.s_isnan.os.dep
rm -rf libm/.s_isnanf.os.dep
rm -rf libm/.s_ldexp.os.dep
rm -rf libm/.s_lib_version.os.dep
rm -rf libm/.s_llrint.os.dep
rm -rf libm/.s_llround.os.dep
rm -rf libm/.s_log1p.os.dep
rm -rf libm/.s_logb.os.dep
rm -rf libm/.s_lrint.os.dep
rm -rf libm/.s_lround.os.dep
rm -rf libm/.s_matherr.os.dep
rm -rf libm/.s_modf.os.dep
rm -rf libm/.s_nearbyint.os.dep
rm -rf libm/.s_nextafter.os.dep
rm -rf libm/.s_remquo.os.dep
rm -rf libm/.s_rint.os.dep
rm -rf libm/.s_round.os.dep
rm -rf libm/.s_scalbln.os.dep
rm -rf libm/.s_scalbn.os.dep
rm -rf libm/.s_signbit.os.dep
rm -rf libm/.s_signbitf.os.dep
rm -rf libm/.s_signgam.os.dep
rm -rf libm/.s_significand.os.dep
rm -rf libm/.s_sin.os.dep
rm -rf libm/.s_tan.os.dep
rm -rf libm/.s_tanh.os.dep
rm -rf libm/.s_trunc.os.dep
rm -rf libm/.scalbf.os.dep
rm -rf libm/.scalblnf.os.dep
rm -rf libm/.scalbnf.os.dep
rm -rf libm/.significandf.os.dep
rm -rf libm/.sinf.os.dep
rm -rf libm/.sinhf.os.dep
rm -rf libm/.sqrtf.os.dep
rm -rf libm/.tanf.os.dep
rm -rf libm/.tanhf.os.dep
rm -rf libm/.tgammaf.os.dep
rm -rf libm/.truncf.os.dep
rm -rf libm/.w_acos.os.dep
rm -rf libm/.w_acosh.os.dep
rm -rf libm/.w_asin.os.dep
rm -rf libm/.w_atan2.os.dep
rm -rf libm/.w_atanh.os.dep
rm -rf libm/.w_cabs.os.dep
rm -rf libm/.w_cosh.os.dep
rm -rf libm/.w_drem.os.dep
rm -rf libm/.w_exp.os.dep
rm -rf libm/.w_exp2.os.dep
rm -rf libm/.w_fmod.os.dep
rm -rf libm/.w_gamma.os.dep
rm -rf libm/.w_hypot.os.dep
rm -rf libm/.w_j0.os.dep
rm -rf libm/.w_j1.os.dep
rm -rf libm/.w_jn.os.dep
rm -rf libm/.w_lgamma.os.dep
rm -rf libm/.w_lgamma_r.os.dep
rm -rf libm/.w_log.os.dep
rm -rf libm/.w_log10.os.dep
rm -rf libm/.w_log2.os.dep
rm -rf libm/.w_pow.os.dep
rm -rf libm/.w_remainder.os.dep
rm -rf libm/.w_scalb.os.dep
rm -rf libm/.w_sinh.os.dep
rm -rf libm/.w_sqrt.os.dep
rm -rf libm/.w_tgamma.os.dep
rm -rf libm/acosf.os
rm -rf libm/acoshf.os
rm -rf libm/asinf.os
rm -rf libm/asinhf.os
rm -rf libm/atan2f.os
rm -rf libm/atanf.os
rm -rf libm/atanhf.os
rm -rf libm/cabsf.os
rm -rf libm/carg.os
rm -rf libm/cargf.os
rm -rf libm/cbrtf.os
rm -rf libm/ceilf.os
rm -rf libm/copysignf.os
rm -rf libm/cosf.os
rm -rf libm/coshf.os
rm -rf libm/e_acos.os
rm -rf libm/e_acosh.os
rm -rf libm/e_asin.os
rm -rf libm/e_atan2.os
rm -rf libm/e_atanh.os
rm -rf libm/e_cosh.os
rm -rf libm/e_exp.os
rm -rf libm/e_fmod.os
rm -rf libm/e_gamma.os
rm -rf libm/e_gamma_r.os
rm -rf libm/e_hypot.os
rm -rf libm/e_j0.os
rm -rf libm/e_j1.os
rm -rf libm/e_jn.os
rm -rf libm/e_lgamma.os
rm -rf libm/e_lgamma_r.os
rm -rf libm/e_log.os
rm -rf libm/e_log10.os
rm -rf libm/e_log2.os
rm -rf libm/e_pow.os
rm -rf libm/e_rem_pio2.os
rm -rf libm/e_remainder.os
rm -rf libm/e_scalb.os
rm -rf libm/e_sinh.os
rm -rf libm/e_sqrt.os
rm -rf libm/erfcf.os
rm -rf libm/erff.os
rm -rf libm/exp2f.os
rm -rf libm/expf.os
rm -rf libm/expm1f.os
rm -rf libm/fabsf.os
rm -rf libm/fdimf.os
rm -rf libm/floorf.os
rm -rf libm/fmaf.os
rm -rf libm/fmaxf.os
rm -rf libm/fminf.os
rm -rf libm/fmodf.os
rm -rf libm/frexpf.os
rm -rf libm/gammaf.os
rm -rf libm/hypotf.os
rm -rf libm/ilogbf.os
rm -rf libm/k_cos.os
rm -rf libm/k_rem_pio2.os
rm -rf libm/k_sin.os
rm -rf libm/k_standard.os
rm -rf libm/k_tan.os
rm -rf libm/ldexpf.os
rm -rf libm/lgammaf.os
rm -rf libm/llrintf.os
rm -rf libm/llroundf.os
rm -rf libm/log10f.os
rm -rf libm/log1pf.os
rm -rf libm/log2f.os
rm -rf libm/logbf.os
rm -rf libm/logf.os
rm -rf libm/lrintf.os
rm -rf libm/lroundf.os
rm -rf libm/modff.os
rm -rf libm/nan.os
rm -rf libm/nearbyintf.os
rm -rf libm/nextafterf.os
rm -rf libm/powf.os
rm -rf libm/remainderf.os
rm -rf libm/remquof.os
rm -rf libm/rintf.os
rm -rf libm/roundf.os
rm -rf libm/s_asinh.os
rm -rf libm/s_atan.os
rm -rf libm/s_cbrt.os
rm -rf libm/s_ceil.os
rm -rf libm/s_copysign.os
rm -rf libm/s_cos.os
rm -rf libm/s_erf.os
rm -rf libm/s_expm1.os
rm -rf libm/s_fabs.os
rm -rf libm/s_fdim.os
rm -rf libm/s_finite.os
rm -rf libm/s_finitef.os
rm -rf libm/s_floor.os
rm -rf libm/s_fma.os
rm -rf libm/s_fmax.os
rm -rf libm/s_fmin.os
rm -rf libm/s_fpclassify.os
rm -rf libm/s_fpclassifyf.os
rm -rf libm/s_frexp.os
rm -rf libm/s_ilogb.os
rm -rf libm/s_isinf.os
rm -rf libm/s_isinff.os
rm -rf libm/s_isnan.os
rm -rf libm/s_isnanf.os
rm -rf libm/s_ldexp.os
rm -rf libm/s_lib_version.os
rm -rf libm/s_llrint.os
rm -rf libm/s_llround.os
rm -rf libm/s_log1p.os
rm -rf libm/s_logb.os
rm -rf libm/s_lrint.os
rm -rf libm/s_lround.os
rm -rf libm/s_matherr.os
rm -rf libm/s_modf.os
rm -rf libm/s_nearbyint.os
rm -rf libm/s_nextafter.os
rm -rf libm/s_remquo.os
rm -rf libm/s_rint.os
rm -rf libm/s_round.os
rm -rf libm/s_scalbln.os
rm -rf libm/s_scalbn.os
rm -rf libm/s_signbit.os
rm -rf libm/s_signbitf.os
rm -rf libm/s_signgam.os
rm -rf libm/s_significand.os
rm -rf libm/s_sin.os
rm -rf libm/s_tan.os
rm -rf libm/s_tanh.os
rm -rf libm/s_trunc.os
rm -rf libm/scalbf.os
rm -rf libm/scalblnf.os
rm -rf libm/scalbnf.os
rm -rf libm/significandf.os
rm -rf libm/sinf.os
rm -rf libm/sinhf.os
rm -rf libm/sqrtf.os
rm -rf libm/tanf.os
rm -rf libm/tanhf.os
rm -rf libm/tgammaf.os
rm -rf libm/truncf.os
rm -rf libm/w_acos.os
rm -rf libm/w_acosh.os
rm -rf libm/w_asin.os
rm -rf libm/w_atan2.os
rm -rf libm/w_atanh.os
rm -rf libm/w_cabs.os
rm -rf libm/w_cosh.os
rm -rf libm/w_drem.os
rm -rf libm/w_exp.os
rm -rf libm/w_exp2.os
rm -rf libm/w_fmod.os
rm -rf libm/w_gamma.os
rm -rf libm/w_hypot.os
rm -rf libm/w_j0.os
rm -rf libm/w_j1.os
rm -rf libm/w_jn.os
rm -rf libm/w_lgamma.os
rm -rf libm/w_lgamma_r.os
rm -rf libm/w_log.os
rm -rf libm/w_log10.os
rm -rf libm/w_log2.os
rm -rf libm/w_pow.os
rm -rf libm/w_remainder.os
rm -rf libm/w_scalb.os
rm -rf libm/w_sinh.os
rm -rf libm/w_sqrt.os
rm -rf libm/w_tgamma.os
rm -rf libnsl/.nsl.os.dep
rm -rf libnsl/nsl.os
rm -rf libpthread/linuxthreads.old/.attr.os.dep
rm -rf libpthread/linuxthreads.old/.cancel.os.dep
rm -rf libpthread/linuxthreads.old/.condvar.os.dep
rm -rf libpthread/linuxthreads.old/.errno.os.dep
rm -rf libpthread/linuxthreads.old/.events.os.dep
rm -rf libpthread/linuxthreads.old/.forward.oS.dep
rm -rf libpthread/linuxthreads.old/.join.os.dep
rm -rf libpthread/linuxthreads.old/.libc_pthread_init.oS.dep
rm -rf libpthread/linuxthreads.old/.libc_pthread_init.os.dep
rm -rf libpthread/linuxthreads.old/.lockfile.os.dep
rm -rf libpthread/linuxthreads.old/.manager.os.dep
rm -rf libpthread/linuxthreads.old/.mutex.os.dep
rm -rf libpthread/linuxthreads.old/.oldsemaphore.os.dep
rm -rf libpthread/linuxthreads.old/.pt-machine.os.dep
rm -rf libpthread/linuxthreads.old/.ptfork.os.dep
rm -rf libpthread/linuxthreads.old/.pthread.oS.dep
rm -rf libpthread/linuxthreads.old/.pthread.os.dep
rm -rf libpthread/linuxthreads.old/.ptlongjmp.os.dep
rm -rf libpthread/linuxthreads.old/.rwlock.os.dep
rm -rf libpthread/linuxthreads.old/.semaphore.os.dep
rm -rf libpthread/linuxthreads.old/.signals.os.dep
rm -rf libpthread/linuxthreads.old/.specific.os.dep
rm -rf libpthread/linuxthreads.old/.spinlock.os.dep
rm -rf libpthread/linuxthreads.old/.wrapsyscall.os.dep
rm -rf libpthread/linuxthreads.old/attr.os
rm -rf libpthread/linuxthreads.old/cancel.os
rm -rf libpthread/linuxthreads.old/condvar.os
rm -rf libpthread/linuxthreads.old/errno.os
rm -rf libpthread/linuxthreads.old/events.os
rm -rf libpthread/linuxthreads.old/forward.oS
rm -rf libpthread/linuxthreads.old/join.os
rm -rf libpthread/linuxthreads.old/libc_pthread_init.oS
rm -rf libpthread/linuxthreads.old/libc_pthread_init.os
rm -rf libpthread/linuxthreads.old/libpthread_so.a
rm -rf libpthread/linuxthreads.old/lockfile.os
rm -rf libpthread/linuxthreads.old/manager.os
rm -rf libpthread/linuxthreads.old/mutex.os
rm -rf libpthread/linuxthreads.old/oldsemaphore.os
rm -rf libpthread/linuxthreads.old/pt-machine.os
rm -rf libpthread/linuxthreads.old/ptfork.os
rm -rf libpthread/linuxthreads.old/pthread.oS
rm -rf libpthread/linuxthreads.old/pthread.os
rm -rf libpthread/linuxthreads.old/ptlongjmp.os
rm -rf libpthread/linuxthreads.old/rwlock.os
rm -rf libpthread/linuxthreads.old/semaphore.os
rm -rf libpthread/linuxthreads.old/signals.os
rm -rf libpthread/linuxthreads.old/specific.os
rm -rf libpthread/linuxthreads.old/spinlock.os
rm -rf libpthread/linuxthreads.old/wrapsyscall.os
rm -rf libpthread/linuxthreads.old_db/.td_init.os.dep
rm -rf libpthread/linuxthreads.old_db/.td_log.os.dep
rm -rf libpthread/linuxthreads.old_db/.td_symbol_list.os.dep
rm -rf libpthread/linuxthreads.old_db/.td_ta_clear_event.os.dep
rm -rf libpthread/linuxthreads.old_db/.td_ta_delete.os.dep
rm -rf libpthread/linuxthreads.old_db/.td_ta_enable_stats.os.dep
rm -rf libpthread/linuxthreads.old_db/.td_ta_event_addr.os.dep
rm -rf libpthread/linuxthreads.old_db/.td_ta_event_getmsg.os.dep
rm -rf libpthread/linuxthreads.old_db/.td_ta_get_nthreads.os.dep
rm -rf libpthread/linuxthreads.old_db/.td_ta_get_ph.os.dep
rm -rf libpthread/linuxthreads.old_db/.td_ta_get_stats.os.dep
rm -rf libpthread/linuxthreads.old_db/.td_ta_map_id2thr.os.dep
rm -rf libpthread/linuxthreads.old_db/.td_ta_map_lwp2thr.os.dep
rm -rf libpthread/linuxthreads.old_db/.td_ta_new.os.dep
rm -rf libpthread/linuxthreads.old_db/.td_ta_reset_stats.os.dep
rm -rf libpthread/linuxthreads.old_db/.td_ta_set_event.os.dep
rm -rf libpthread/linuxthreads.old_db/.td_ta_setconcurrency.os.dep
rm -rf libpthread/linuxthreads.old_db/.td_ta_thr_iter.os.dep
rm -rf libpthread/linuxthreads.old_db/.td_ta_tsd_iter.os.dep
rm -rf libpthread/linuxthreads.old_db/.td_thr_clear_event.os.dep
rm -rf libpthread/linuxthreads.old_db/.td_thr_dbresume.os.dep
rm -rf libpthread/linuxthreads.old_db/.td_thr_dbsuspend.os.dep
rm -rf libpthread/linuxthreads.old_db/.td_thr_event_enable.os.dep
rm -rf libpthread/linuxthreads.old_db/.td_thr_event_getmsg.os.dep
rm -rf libpthread/linuxthreads.old_db/.td_thr_get_info.os.dep
rm -rf libpthread/linuxthreads.old_db/.td_thr_getfpregs.os.dep
rm -rf libpthread/linuxthreads.old_db/.td_thr_getgregs.os.dep
rm -rf libpthread/linuxthreads.old_db/.td_thr_getxregs.os.dep
rm -rf libpthread/linuxthreads.old_db/.td_thr_getxregsize.os.dep
rm -rf libpthread/linuxthreads.old_db/.td_thr_set_event.os.dep
rm -rf libpthread/linuxthreads.old_db/.td_thr_setfpregs.os.dep
rm -rf libpthread/linuxthreads.old_db/.td_thr_setgregs.os.dep
rm -rf libpthread/linuxthreads.old_db/.td_thr_setprio.os.dep
rm -rf libpthread/linuxthreads.old_db/.td_thr_setsigpending.os.dep
rm -rf libpthread/linuxthreads.old_db/.td_thr_setxregs.os.dep
rm -rf libpthread/linuxthreads.old_db/.td_thr_sigsetmask.os.dep
rm -rf libpthread/linuxthreads.old_db/.td_thr_tls_get_addr.os.dep
rm -rf libpthread/linuxthreads.old_db/.td_thr_tsd.os.dep
rm -rf libpthread/linuxthreads.old_db/.td_thr_validate.os.dep
rm -rf libpthread/linuxthreads.old_db/td_init.os
rm -rf libpthread/linuxthreads.old_db/td_log.os
rm -rf libpthread/linuxthreads.old_db/td_symbol_list.os
rm -rf libpthread/linuxthreads.old_db/td_ta_clear_event.os
rm -rf libpthread/linuxthreads.old_db/td_ta_delete.os
rm -rf libpthread/linuxthreads.old_db/td_ta_enable_stats.os
rm -rf libpthread/linuxthreads.old_db/td_ta_event_addr.os
rm -rf libpthread/linuxthreads.old_db/td_ta_event_getmsg.os
rm -rf libpthread/linuxthreads.old_db/td_ta_get_nthreads.os
rm -rf libpthread/linuxthreads.old_db/td_ta_get_ph.os
rm -rf libpthread/linuxthreads.old_db/td_ta_get_stats.os
rm -rf libpthread/linuxthreads.old_db/td_ta_map_id2thr.os
rm -rf libpthread/linuxthreads.old_db/td_ta_map_lwp2thr.os
rm -rf libpthread/linuxthreads.old_db/td_ta_new.os
rm -rf libpthread/linuxthreads.old_db/td_ta_reset_stats.os
rm -rf libpthread/linuxthreads.old_db/td_ta_set_event.os
rm -rf libpthread/linuxthreads.old_db/td_ta_setconcurrency.os
rm -rf libpthread/linuxthreads.old_db/td_ta_thr_iter.os
rm -rf libpthread/linuxthreads.old_db/td_ta_tsd_iter.os
rm -rf libpthread/linuxthreads.old_db/td_thr_clear_event.os
rm -rf libpthread/linuxthreads.old_db/td_thr_dbresume.os
rm -rf libpthread/linuxthreads.old_db/td_thr_dbsuspend.os
rm -rf libpthread/linuxthreads.old_db/td_thr_event_enable.os
rm -rf libpthread/linuxthreads.old_db/td_thr_event_getmsg.os
rm -rf libpthread/linuxthreads.old_db/td_thr_get_info.os
rm -rf libpthread/linuxthreads.old_db/td_thr_getfpregs.os
rm -rf libpthread/linuxthreads.old_db/td_thr_getgregs.os
rm -rf libpthread/linuxthreads.old_db/td_thr_getxregs.os
rm -rf libpthread/linuxthreads.old_db/td_thr_getxregsize.os
rm -rf libpthread/linuxthreads.old_db/td_thr_set_event.os
rm -rf libpthread/linuxthreads.old_db/td_thr_setfpregs.os
rm -rf libpthread/linuxthreads.old_db/td_thr_setgregs.os
rm -rf libpthread/linuxthreads.old_db/td_thr_setprio.os
rm -rf libpthread/linuxthreads.old_db/td_thr_setsigpending.os
rm -rf libpthread/linuxthreads.old_db/td_thr_setxregs.os
rm -rf libpthread/linuxthreads.old_db/td_thr_sigsetmask.os
rm -rf libpthread/linuxthreads.old_db/td_thr_tls_get_addr.os
rm -rf libpthread/linuxthreads.old_db/td_thr_tsd.os
rm -rf libpthread/linuxthreads.old_db/td_thr_validate.os
rm -rf libresolv/.resolv.os.dep
rm -rf libresolv/resolv.os
rm -rf librt/.mq_close.os.dep
rm -rf librt/.mq_getsetattr.os.dep
rm -rf librt/.mq_notify.os.dep
rm -rf librt/.mq_open.os.dep
rm -rf librt/.mq_receive.os.dep
rm -rf librt/.mq_send.os.dep
rm -rf librt/.mq_unlink.os.dep
rm -rf librt/.timer_create.os.dep
rm -rf librt/.timer_delete.os.dep
rm -rf librt/.timer_getoverr.os.dep
rm -rf librt/.timer_gettime.os.dep
rm -rf librt/.timer_settime.os.dep
rm -rf librt/mq_close.os
rm -rf librt/mq_getsetattr.os
rm -rf librt/mq_notify.os
rm -rf librt/mq_open.os
rm -rf librt/mq_receive.os
rm -rf librt/mq_send.os
rm -rf librt/mq_unlink.os
rm -rf librt/timer_create.os
rm -rf librt/timer_delete.os
rm -rf librt/timer_getoverr.os
rm -rf librt/timer_gettime.os
rm -rf librt/timer_settime.os
rm -rf libutil/.forkpty.os.dep
rm -rf libutil/.login.os.dep
rm -rf libutil/.login_tty.os.dep
rm -rf libutil/.logout.os.dep
rm -rf libutil/.logwtmp.os.dep
rm -rf libutil/.openpty.os.dep
rm -rf libutil/forkpty.os
rm -rf libutil/login.os
rm -rf libutil/login_tty.os
rm -rf libutil/logout.os
rm -rf libutil/logwtmp.os
rm -rf libutil/openpty.os
