#!/bin/sh
# Copyright (C) 2010 Ubicom, Inc.

STATE_MAJOR_NUMBER=$(cat /sys/devices/system/ubicom_wish/ubicom_wish0/wish_dev_major)

#
# Mount the special file that allows us to read the state of the classifier
#
mknod /dev/ubicom_wish c $STATE_MAJOR_NUMBER 0

