#
#	Makefile -- Build instructions for Ubicom32 / IP5K
#

# include the common rules for creating/cleaning a root filesystem
include $(ROOTDIR)/vendors/config/ubicom32nommu/Makefile.common

romfs:
# no other rules needed as Makefile.common does it all.
