#OBJS=l2tpd.o nvl2tp.o nvpptp.o pptpd.o vpn.o ipsec.o vpn_cmds.o ipsec_hw_parser.o
OBJS=vpn.o ipsec.o vpn_cmds.o ipsec_hw_parser.o ipsec_monitor.o l2tpd.o pptpd.o nvpptp.o nvl2tp.o sslvpn.o ddns_append_fqdn.o

include ../../Rules.make
