struct items_range vlan_bw_qos[] = { 
	{ "vlan_enable", "0", NV_RESET},
	{ "vlan2ports", "", NV_RESET},
	{ "vlan3ports", "", NV_RESET},
	{ "vlan4ports", "", NV_RESET},
	{ "vlan5ports", "", NV_RESET},
	{ "vlan6ports", "", NV_RESET},
	{ "vlan7ports", "", NV_RESET},
	{ "vlan8ports", "", NV_RESET},
	{ "vlan9ports", "", NV_RESET},
	{ "vlan10ports", "", NV_RESET},
	{ "vlan11ports", "", NV_RESET},
	{ "vlan12ports", "", NV_RESET},
	{ "vlan13ports", "", NV_RESET},
	{ "vlan14ports", "", NV_RESET},
	{ "vlan15ports", "", NV_RESET},
	{ "vlanpriority0", "3", NV_RESET},
	{ "vlanpriority1", "3", NV_RESET},
	{ "vlanpriority2", "2", NV_RESET},
	{ "vlanpriority3", "2", NV_RESET},
	{ "vlanpriority4", "1", NV_RESET},
	{ "vlanpriority5", "1", NV_RESET},
	{ "vlanpriority6", "0", NV_RESET},
	{ "vlanpriority7", "0", NV_RESET},
	{ "bw_enable", "0", NV_RESET},
	{ "bw_uplink", "512", NV_RESET},
	{ "bw_downlink", "512", NV_RESET},
	{ "bw_ctrl_", "", NV_RESET, 0, 24},
	{ "is_enable_qos", "1", NV_RESET},
	{ "qos_auto_classif", "1", NV_RESET},
	{ "qos_dynamic_frag", "1", NV_RESET},
	{ "qos_rule", "0", NV_RESET, 1, 10},
	{ "qos_weight_rule", "", NV_RESET},
	{ "checksum", "", NV_RESET},
	{NULL, NULL}
};
