#!/bin/sh
#
# This script is run by the pppd after the link is established.
# It is used to add routes, set IP address, run the mailq etc.
#
# This script is called with the following arguments:
#    Arg  Name                          Example
#    $1   Interface name                ppp0
#    $2   The tty                       ttyS1
#    $3   The link speed                38400
#    $4   Local IP number               12.34.56.78
#    $5   Peer  IP number               12.34.56.99
#    $6   Optional ``ipparam'' value    foo

. /etc/rgw_config

# These variables are for the use of the scripts run by run-parts
PPP_IFACE="$1"
PPP_TTY="$2"
PPP_SPEED="$3"
PPP_LOCAL="$4"
PPP_REMOTE="$5"
PPP_IPPARAM="$6"

DNS1=`cat /var/run/$PPP_IFACE.resolv| grep nameserver | cut -c 12-30 | cut -f1 -d '
'`
DNS2=`cat /var/run/$PPP_IFACE.resolv | grep nameserver | cut -c 12-30 | cut -f2 -d '
'`
DNS3=`cat /var/run/$PPP_IFACE.resolv | grep nameserver | cut -c 12-30 | cut -f3 -d '
'`
sed -i '/^PPPDNS1=/ c\PPPDNS1='$DNS1'' /etc/rgw_config
sed -i '/^PPPDNS2=/ c\PPPDNS2='$DNS2'' /etc/rgw_config
sed -i '/^PPPDNS3=/ c\PPPDNS3='$DNS3'' /etc/rgw_config
sed -i '/^PPPLOCALIP=/ c\PPPLOCALIP='$PPP_LOCAL'' /etc/rgw_config
sed -i '/^PPPREMOTEIP=/ c\PPPREMOTEIP='$PPP_REMOTE'' /etc/rgw_config
sed -i '/^PPPINTERFACE=/ c\PPPINTERFACE='$PPP_IFACE'' /etc/rgw_config
sed -i '/^WAN_MODE_INTERFACE=/ c\WAN_MODE_INTERFACE='$PPP_IFACE'' /etc/rgw_config

if [ ! -f /etc/config/config/resolv.conf ]; then 
	ln -s /var/run/$PPP_IFACE.resolv /etc/config/config/resolv.conf
fi

if [ "$WANCONNECTIONTYPE" = "pptp" ]; then
	route del default > /dev/null 2>&1
fi

route add default gw $PPP_REMOTE

iptables --table nat --append POSTROUTING --out-interface $PPP_IFACE --jump MASQUERADE

