/* MiniUPnP Project
 * http://miniupnp.free.fr/ or http://miniupnp.tuxfamily.org/
 * (c) 2006-2008 Thomas Bernard
 * generated by ./genconfig.sh on Fri Apr  3 15:07:36 CST 2009 */
#ifndef __CONFIG_H__
#define __CONFIG_H__

#define UPNP_VERSION	"2009014"
#define USE_NETFILTER 1
#define OS_NAME		"Linux"
#define OS_VERSION	" "
#define OS_URL		"http://www.kernel.org/"

/* syslog facility to be used by miniupnpd */
#define LOG_MINIUPNPD		 LOG_DAEMON

/* Uncomment the following line to allow miniupnpd to be
 * controlled by miniupnpdctl */
/*#define USE_MINIUPNPDCTL*/

/* Comment the following line to disable NAT-PMP operations */
// jimmy marked
//#define ENABLE_NATPMP

/* Uncomment the following line to enable generation of
 * filter rules with pf */
/*#define PF_ENABLE_FILTER_RULES*/

/* Uncomment the following line to enable caching of results of
 * the getifstats() function */
/*#define ENABLE_GETIFSTATS_CACHING*/
/* The cache duration is indicated in seconds */
#define GETIFSTATS_CACHING_DURATION 2

/* Uncomment the following line to enable multiple external ip support */
/* note : Thas is EXPERIMENTAL, do not use that unless you know perfectly what you are doing */
/*#define MULTIPLE_EXTERNAL_IP*/

/* Comment the following line to use home made daemonize() func instead
 * of BSD daemon() */
// jimmy marked
//#define USE_DAEMON

/* Uncomment the following line to enable lease file support */
// this is for the function record port maping in files, and when
// booting , upnpd will automatically reload this rules
// jimmy marked, we defined this definition in apps/.config
// and used within Makefile (CFLAGS)
//#define ENABLE_LEASEFILE

/* Define one or none of the two following macros in order to make some
 * clients happy. It will change the XML Root Description of the IGD.
 * Enabling the Layer3Forwarding Service seems to be the more compatible
 * option. */
 /*
 Note:
 	Currently, we forece to ENABLE_L3F_SERVICE instead HAS_DUMMY_SERVICE
	If
	1. we use ENABLE_L3F_SERVICE and mark HAS_DUMMY_SERVICE
		- Router icon in XP "network connections" will show up
		- Intel device validator will pass
	2. we mark ENABLE_L3F_SERVICE and unmark HAS_DUMMY_SERVICE
		- Router icon in XP "network connections" will show up
		- Intel device validator will fail in Notify and Discovery for service "DUMMY_SERVICE"
	3. we unmark ENABLE_L3F_SERVICE and unmark HAS_DUMMY_SERVICE
		- We should not use this way
		- I don't know will this scenario will cause any issue
	4. Using L3F is recommended
	5. Related files
		- upnpdescgen.c
		- minissdp.c
		- upnpevents.c
 */
//#define HAS_DUMMY_SERVICE
#define ENABLE_L3F_SERVICE

/* Experimental UPnP Events support. */
// jimmy uncomment
#define ENABLE_EVENTS

/* include interface name in pf and ipf rules */
#define USE_IFNAME_IN_RULES

//#define CHECK_VS_NVRAM appen in CLFAGS in Makefile
//#define CHECK_PF_NVRAM

/*	Date:	2009-04-29
*	Name:	jimmy huang
*	Reason:	Currently, due to miniupnpd's architecture(select,noblock),
*			we may not immediately send notify after variable changed (Add / Del PortMapping...)
*			This definition is used to force when after soap, we use sock with block
*			to send notify right after AddPortMapping, search this definition within codes
*			for more detail
*	Note:	Not test this feature well
*/
//#define IMMEDIATELY_SEND_NOTIFY

/*	Date:	2009-05-07
*	Name:	jimmy huang
*	Reason:	For some features that we current not been ask to implement
*			But which is required by UPnP Spec
*			just mark it for feature request
*	Note:	1. Test with Intel Device Validator
*/
#define UPNP_FULLLY_FEATURE

/* ---------------------------------------------- */

#endif
