/* $Id: upnpdescstrings.h,v 1.4 2009/06/26 08:50:57 jimmy_huang Exp $ */
/* miniupnp project
 * http://miniupnp.free.fr/ or http://miniupnp.tuxfamily.org/
 * (c) 2006 Thomas Bernard
 * This software is subject to the coditions detailed in
 * the LICENCE file provided within the distribution */
#ifndef __UPNPDESCSTRINGS_H__
#define __UPNPDESCSTRINGS_H__

#include "config.h"

/* strings used in the root device xml description */
#define ROOTDEV_FRIENDLYNAME		friendlyname // OS_NAME " router"
#define ROOTDEV_MANUFACTURER		manufacturername // OS_NAME
#define ROOTDEV_MANUFACTURERURL		manufacturerurl // OS_URL
#define ROOTDEV_MODELNAME			modelname // OS_NAME " router"

/*
FIXME: 
	For each project, friendlyname may differ from modeldescription
	Currently friendlyname is read from miniupnpd.conf
	And miniupnpd.conf is generated by rc/app.c (read by nvram)
*/
//#define ROOTDEV_MODELDESCRIPTION	modelname // OS_NAME " router"
#define ROOTDEV_MODELDESCRIPTION	friendlyname
// --------
#define ROOTDEV_MODELURL			modelurl // OS_URL
#define ROOTDEV_MODELNUMBER			modelnumber // MODEL_NUMBER

#define WANDEV_FRIENDLYNAME			friendlyname // "WANDevice"
#define WANDEV_MANUFACTURER			manufacturername //"MiniUPnP"
#define WANDEV_MANUFACTURERURL		manufacturerurl // "http://miniupnp.free.fr/"
#define WANDEV_MODELNAME			modelname // "WAN Device"
#define WANDEV_MODELDESCRIPTION		friendlyname // "Internet Access Router" // "WAN Device"
#define WANDEV_MODELNUMBER			modelnumber // UPNP_VERSION
#define WANDEV_MODELURL				modelurl // "http://miniupnp.free.fr/"
#define WANDEV_UPC					UPC // "MINIUPNPD"

#define WANCDEV_FRIENDLYNAME		friendlyname // "WANConnectionDevice"
#define WANCDEV_MANUFACTURER		manufacturername // WANDEV_MANUFACTURER
#define WANCDEV_MANUFACTURERURL		manufacturerurl // WANDEV_MANUFACTURERURL
#define WANCDEV_MODELNAME			modelname // "WANConnectionDevice" // "MiniUPnPd"
#define WANCDEV_MODELDESCRIPTION	friendlyname // "WANConnectionDevice" // "MiniUPnP daemon"
#define WANCDEV_MODELNUMBER			modelnumber // UPNP_VERSION
#define WANCDEV_MODELURL			modelurl // "http://miniupnp.free.fr/"
#define WANCDEV_UPC					UPC // "MINIUPNPD"

/*	Date:	2009-04-20
*	Name:	jimmy huang
*	Reason:	For wps enable / disable and UPnP related stuff
*/
#define WFA_FRIENDLYNAME			"WFADevice"
#define WFA_MANUFACTURER			manufacturername
#define WFA_MANUFACTURERURL			manufacturerurl
#define WFA_MODELNAME				modelname
#define WFA_MODELDESCRIPTION		modelname
#define	WFA_MODELNUMBER				modelnumber
#define WFA_MODELURL				modelurl
#define WFA_SERIALNUMBER			serialnumber
#define WFA_UPC						UPC
//----------

#endif

