CFLAGS += -I$(shell pwd)/../../../rc -I$(shell pwd)/../../../sutil -I$(shell pwd)/../../../../include/modules/ -I$(ROOTDIR)/config

OBJS= wlutils.o wlan_insmod.o wlan_vap.o wlan_wsc.o wlan_ifnum.o wlan_mac.o wlan_util.o wlan_wps.o wlan_rate.o wlan_ath_setup.o wlan_init.o wlan.o
include ../../Rules.make
