#!/bin/sh /etc/rc.common
# Copyright (C) 2009 Ubicom, Inc.

if [ $action = "start" ]	
then
	echo "Starting NETBIOS daemon"
	nmbd -i >/dev/null 2>&1 &
elif [ $action = "stop"	]
then
	echo "Stopping NETBIOS daemon"
fi	

