#OBJS=firmware.o hnap.o ips.o pure_xml.o sscinf.o wan_util.o x509.o
OBJS=hnap.o hnap_main.o hnap_system.o hnap_network.o hnap_firewall.o hnap_wlan.o hnap_wan.o hnap_connection.o
include ../Rules.make
