#! /bin/sh

        st=0
        # check if given sourceip is local and add as alias if not
        if ! ip -o route get ${PLUTO_MY_SOURCEIP%/*} | grep -q ^local
        then
            it="ip addr add ${PLUTO_MY_SOURCEIP%/*}/32 dev ${PLUTO_INTERFACE%:*}"
            oops="`eval $it 2>&1`"
            st=$?
            if test " $oops" = " " -a " $st" != " 0"
            then
                oops="silent error, exit status $st"
            fi
            case "$oops" in
                    'RTNETLINK answers: File exists'*)
                    # should not happen, but ... ignore if the
                    # address was already assigned on interface
                    oops=""
                    st=0
                    ;;
            esac
            if test " $oops" != " " -o " $st" != " 0"
            then
                echo "$0: addsource \`$it' failed ($oops)" >&2
            fi
        fi
        return $st

