#OBJS=firmware.o hnap.o ips.o pure_xml.o sscinf.o wan_util.o x509.o
OBJS=sscinf.o x509.o firmware.o lang.o rcctrl.o restore_default.o timeset.o logpages.o wizard_wlan.o mtd.o hnap_post.o hnap_get.o online_firmware_check.o lan_revoke.o reject.o ipv6.o
include ../Rules.make
