#!/bin/sh
# Copyright (C) 2010 Ubicom, Inc.

#
# (re)start rule set on the StreamEngine HTTP Content classifier
#

. /etc/rgw_config
#. /etc/functions.sh

ANY_RULE_APPLIED=0

#
# echo_debug(msg)
#	Echo only if SE_DEBUG environment variable is set to 1
echo_debug()
{
	if [ "$SE_DEBUG" == "1" ]; then
		echo "$*"
	fi
}

#
# qos_rule_get(rule_num)
#	Read a qos rule from nvram config
# 
qos_rule_set()
{
	#
	# NVRAM rules look like:
	# http_content_rule_00 = <en dis>/<name>/<prio>/<major>/<minor>
	#
	RULE_NAME=http_content_rule_$1
	#config_get RULE_SPEC streamengine $RULE_NAME
	RULE_SPEC=$(nvram get $RULE_NAME | cut -c24- -)
	QOS_RULE_ENABLED=$(echo $RULE_SPEC | cut -d/ -f1 -)

	echo_debug QoS rule $RULE_NAME
	echo_debug Rule spec = $RULE_SPEC
	echo_debug QOS_RULE_ENABLED=$QOS_RULE_ENABLED

	if [ $QOS_RULE_ENABLED -ne "1" ] ; then
		echo_debug Rule not enabled
		return 0
	fi

	ANY_RULE_APPLIED=1
	echo_debug Setting rule
	echo -n $RULE_SPEC > /sys/devices/system/streamengine_classifier_http_content/streamengine_classifier_http_content0/add_http_type
}

#
# Clear all existing rules
#
echo 1 > /sys/devices/system/streamengine_classifier_http_content/streamengine_classifier_http_content0/clear_http_types

#
# Add rules into the table
#
qos_rule_set 00
qos_rule_set 01
qos_rule_set 02
qos_rule_set 03
qos_rule_set 04
qos_rule_set 05
qos_rule_set 06
qos_rule_set 07
qos_rule_set 08
qos_rule_set 09
qos_rule_set 10
qos_rule_set 11
qos_rule_set 12
qos_rule_set 13
qos_rule_set 14
qos_rule_set 15
qos_rule_set 16
qos_rule_set 17
qos_rule_set 18
qos_rule_set 19

if [ "$ANY_RULE_APPLIED" == "1" ]; then
	echo "Some StreamEngine HTTP Content rules are applied."
fi

