#!/bin/sh
# Copyright (C) 2011 Ubicom, Inc.

insmod /lib/modules/`uname -r`/ubicom_streamengine_tracker.ko
insmod /lib/modules/`uname -r`/ubicom_streamengine_db.ko
insmod /lib/modules/`uname -r`/ubicom_streamengine_tracker_tcp.ko
insmod /lib/modules/`uname -r`/ubicom_streamengine_tracker_udp.ko
insmod /lib/modules/`uname -r`/ubicom_streamengine_tracker_datagram.ko
insmod /lib/modules/`uname -r`/ubicom_streamengine_classifier_default.ko
insmod /lib/modules/`uname -r`/ubicom_streamengine_classifier_user_rules.ko
insmod /lib/modules/`uname -r`/ubicom_streamengine_classifier_bittorrent.ko
insmod /lib/modules/`uname -r`/ubicom_streamengine_classifier_http.ko
insmod /lib/modules/`uname -r`/ubicom_streamengine_classifier_http_content.ko
insmod /lib/modules/`uname -r`/ubicom_streamengine_classifier_ftp.ko
insmod /lib/modules/`uname -r`/ubicom_streamengine_classifier.ko

#
# If if_name sys node is not ready and writeble, wait one second to be sure
#
SE_SYSFS_WAN_IF=/sys/devices/system/streamengine_classifier/streamengine_classifier0/streamengine_classifier_if_name
if [ ! -w ${SE_SYSFS_WAN_IF} ]; then
	sleep 1
fi

