#ifndef __ASM_OFFSETS_H__
#define __ASM_OFFSETS_H__
/*
 * DO NOT MODIFY.
 *
 * This file was generated by Kbuild
 *
 */

#define TASK_STATE 0 /* offsetof(struct task_struct, state)	; */
#define TASK_FLAGS 12 /* offsetof(struct task_struct, flags)	; */
#define TASK_PTRACE 16 /* offsetof(struct task_struct, ptrace)	; */
#define TASK_BLOCKED 572 /* offsetof(struct task_struct, blocked)	; */
#define TASK_THREAD 516 /* offsetof(struct task_struct, thread)	; */
#define TASK_THREAD_INFO 4 /* offsetof(struct task_struct, stack)	; */
#define TASK_MM 168 /* offsetof(struct task_struct, mm)	; */
#define TASK_ACTIVE_MM 172 /* offsetof(struct task_struct, active_mm)	; */
#define STAT_IRQ 72 /* offsetof(struct kernel_stat, irqs)	; */
#define CPUSTAT_SOFTIRQ_PENDING 0 /* offsetof(irq_cpustat_t, __softirq_pending)	; */
#define THREAD_D10 0 /* offsetof(struct thread_struct, d10)	; */
#define THREAD_D11 4 /* offsetof(struct thread_struct, d11)	; */
#define THREAD_D12 8 /* offsetof(struct thread_struct, d12)	; */
#define THREAD_D13 12 /* offsetof(struct thread_struct, d13)	; */
#define THREAD_A1 16 /* offsetof(struct thread_struct, a1)	; */
#define THREAD_A2 20 /* offsetof(struct thread_struct, a2)	; */
#define THREAD_A5 24 /* offsetof(struct thread_struct, a5)	; */
#define THREAD_A6 28 /* offsetof(struct thread_struct, a6)	; */
#define THREAD_SP 32 /* offsetof(struct thread_struct, sp)	; */
#define PT_D0 0 /* offsetof(struct pt_regs, dn[0])	; */
#define PT_D1 4 /* offsetof(struct pt_regs, dn[1])	; */
#define PT_D2 8 /* offsetof(struct pt_regs, dn[2])	; */
#define PT_D3 12 /* offsetof(struct pt_regs, dn[3])	; */
#define PT_D4 16 /* offsetof(struct pt_regs, dn[4])	; */
#define PT_D5 20 /* offsetof(struct pt_regs, dn[5])	; */
#define PT_D6 24 /* offsetof(struct pt_regs, dn[6])	; */
#define PT_D7 28 /* offsetof(struct pt_regs, dn[7])	; */
#define PT_D8 32 /* offsetof(struct pt_regs, dn[8])	; */
#define PT_D9 36 /* offsetof(struct pt_regs, dn[9])	; */
#define PT_D10 40 /* offsetof(struct pt_regs, dn[10])	; */
#define PT_D11 44 /* offsetof(struct pt_regs, dn[11])	; */
#define PT_D12 48 /* offsetof(struct pt_regs, dn[12])	; */
#define PT_D13 52 /* offsetof(struct pt_regs, dn[13])	; */
#define PT_D14 56 /* offsetof(struct pt_regs, dn[14])	; */
#define PT_D15 60 /* offsetof(struct pt_regs, dn[15])	; */
#define PT_A0 64 /* offsetof(struct pt_regs, an[0])	; */
#define PT_A1 68 /* offsetof(struct pt_regs, an[1])	; */
#define PT_A2 72 /* offsetof(struct pt_regs, an[2])	; */
#define PT_A3 76 /* offsetof(struct pt_regs, an[3])	; */
#define PT_A4 80 /* offsetof(struct pt_regs, an[4])	; */
#define PT_A5 84 /* offsetof(struct pt_regs, an[5])	; */
#define PT_A6 88 /* offsetof(struct pt_regs, an[6])	; */
#define PT_A7 92 /* offsetof(struct pt_regs, an[7])	; */
#define PT_SP 92 /* offsetof(struct pt_regs, an[7])	; */
#define PT_ACC0HI 96 /* offsetof(struct pt_regs, acc0[0])	; */
#define PT_ACC0LO 100 /* offsetof(struct pt_regs, acc0[1])	; */
#define PT_MAC_RC16 104 /* offsetof(struct pt_regs, mac_rc16)	; */
#define PT_ACC1HI 108 /* offsetof(struct pt_regs, acc1[0])	; */
#define PT_ACC1LO 112 /* offsetof(struct pt_regs, acc1[1])	; */
#define PT_SOURCE3 116 /* offsetof(struct pt_regs, source3)	; */
#define PT_INST_CNT 120 /* offsetof(struct pt_regs, inst_cnt)	; */
#define PT_CSR 124 /* offsetof(struct pt_regs, csr)	; */
#define PT_DUMMY_UNUSED 128 /* offsetof(struct pt_regs, dummy_unused)	; */
#define PT_INT_MASK0 132 /* offsetof(struct pt_regs, int_mask0)	; */
#define PT_INT_MASK1 136 /* offsetof(struct pt_regs, int_mask1)	; */
#define PT_PC 144 /* offsetof(struct pt_regs, pc)	; */
#define PT_TRAP_CAUSE 140 /* offsetof(struct pt_regs, trap_cause)	; */
#define PT_SIZE 192 /* sizeof(struct pt_regs)	; */
#define PT_FRAME_TYPE 152 /* offsetof(struct pt_regs, frame_type)	; */
#define PT_ORIGINAL_D0 148 /* offsetof(struct pt_regs, original_dn_0)	; */
#define PT_PREVIOUS_PC 156 /* offsetof(struct pt_regs, previous_pc)	; */
#define PT_INT_MASK2 168 /* offsetof(struct pt_regs, int_mask2)	; */
#define PT_UCSR 172 /* offsetof(struct pt_regs, ucsr)	; */
#define STAT_IRQ 72 /* offsetof(struct kernel_stat, irqs)	; */
#define SIGSEGV 11 /* SIGSEGV	; */
#define SIGTRAP 5 /* SIGTRAP	; */
#define PT_PTRACED 1 /* PT_PTRACED	; */
#define PT_DTRACE 2 /* PT_DTRACE	; */
#define ASM_THREAD_SIZE 16384 /* THREAD_SIZE	; */
#define TI_TASK 0 /* offsetof(struct thread_info, task)	; */
#define TI_EXECDOMAIN 4 /* offsetof(struct thread_info, exec_domain)	; */
#define TI_FLAGS 8 /* offsetof(struct thread_info, flags)	; */
#define TI_PREEMPTCOUNT 16 /* offsetof(struct thread_info, preempt_count)	; */
#define TI_CPU 12 /* offsetof(struct thread_info, cpu)	; */
#define TI_INTR_NESTING 20 /* offsetof(struct thread_info, interrupt_nesting)	; */
#define ASM_TIF_NEED_RESCHED 2 /* TIF_NEED_RESCHED	; */
#define ASM_TIF_SYSCALL_TRACE 0 /* TIF_SYSCALL_TRACE	; */
#define ASM_TIF_SIGPENDING 1 /* TIF_SIGPENDING	; */

#endif
