#include "hnap.h"

char *is_device_ready_result = 
"<?xml version=\"1.0\" encoding=\"utf-8\"?>"
"<soap:Envelope xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\" "
	       "xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\" "
	       "xmlns:soap=\"http://schemas.xmlsoap.org/soap/envelope/\">"
	"<soap:Body>"
		"<IsDeviceReadyResponse xmlns=\"http://purenetworks.com/HNAP1/\">"
			"<IsDeviceReadyResult>%s</IsDeviceReadyResult>"
		"</IsDeviceReadyResponse>"
	"</soap:Body>"
"</soap:Envelope>";

char *unknown_call = 
"<?xml version=\"1.0\" encoding=\"utf-8\"?>"
"<soap:Envelope xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\" "
	       "xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\" "
	       "xmlns:soap=\"http://schemas.xmlsoap.org/soap/envelope/\">"
	"<soap:Body>"
		"<soap:Fault>"
			"<faultcode>soap:Client</faultcode>"
			"<faultstring>Error unknow</faultstring>"
		"</soap:Fault>"
	"</soap:Body>"
"</soap:Envelope>";

char *get_device_settings_result =
"<?xml version=\"1.0\" encoding=\"utf-8\"?>"
"<soap:Envelope xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\" "
               "xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\" "
	       "xmlns:soap=\"http://schemas.xmlsoap.org/soap/envelope/\">"
	"<soap:Body>"
		"<GetDeviceSettingsResponse xmlns=\"http://purenetworks.com/HNAP1/\">"
			"<GetDeviceSettingsResult>OK</GetDeviceSettingsResult>"
			"<Type>%s</Type>"
			"<DeviceName>%s</DeviceName>"
			"<VendorName>%s</VendorName>"
			"<ModelDescription>%s</ModelDescription>"
			"<ModelName>\"%s\"</ModelName>"
			"<FirmwareVersion>%s</FirmwareVersion>"
			"<PresentationURL>%s</PresentationURL>"
#ifdef AUTHGRAPH
			"<CAPTCHA>%s</CAPTCHA>"
#endif
			"<SOAPActions>"
				"<string>http://purenetworks.com/HNAP1/GetDeviceSettings</string>"
				"<string>http://purenetworks.com/HNAP1/SetDeviceSettings</string>"
				"<string>http://purenetworks.com/HNAP1/SetWLanSettings24</string>"
				"<string>http://purenetworks.com/HNAP1/GetWLanSettings24</string>"
				"<string>http://purenetworks.com/HNAP1/SetWanSettings</string>"
				"<string>http://purenetworks.com/HNAP1/GetWanSettings</string>"
				"<string>http://purenetworks.com/HNAP1/SetWLanSecurity</string>"
				"<string>http://purenetworks.com/HNAP1/GetWLanSecurity</string>"
				"<string>http://purenetworks.com/HNAP1/IsDeviceReady</string>"
				"<string>http://purenetworks.com/HNAP1/AddPortMapping</string>"
				"<string>http://purenetworks.com/HNAP1/DeletePortMapping</string>"
				"<string>http://purenetworks.com/HNAP1/GetPortMappings</string>"
				"<string>http://purenetworks.com/HNAP1/SetMACFilters2</string>"
				"<string>http://purenetworks.com/HNAP1/GetMACFilters2</string>"
				"<string>http://purenetworks.com/HNAP1/GetConnectedDevices</string>"
				"<string>http://purenetworks.com/HNAP1/GetNetworkStats</string>"
				"<string>http://purenetworks.com/HNAP1/RenewWanConnection</string>"
				"<string>http://purenetworks.com/HNAP1/Reboot</string>"
				"<string>http://purenetworks.com/HNAP1/GetRouterLanSettings</string>"
				"<string>http://purenetworks.com/HNAP1/SetRouterLanSettings</string>"
				"<string>http://purenetworks.com/HNAP1/GetWLanRadios</string>"
				"<string>http://purenetworks.com/HNAP1/GetWLanRadioSettings</string>"
				"<string>http://purenetworks.com/HNAP1/SetWLanRadioSettings</string>"
				"<string>http://purenetworks.com/HNAP1/GetWLanRadioSecurity</string>"
				"<string>http://purenetworks.com/HNAP1/SetWLanRadioSecurity</string>"
			"</SOAPActions>"
			"<SubDeviceURLs></SubDeviceURLs>"
			"<Tasks>"
				"<TaskExtension>"
					"<Name>Wireless settings</Name>"
					"<URL>%s</URL>"
					"<Type>Browser</Type>"
				"</TaskExtension>"
				"<TaskExtension>"
					"<Name>Block network access</Name>"
					"<URL>%s</URL>"
					"<Type>Browser</Type>"
				"</TaskExtension>"
				"<TaskExtension>"
					"<Name>Parental controls</Name>"
					"<URL>%s</URL>"
					"<Type>Browser</Type>"
				"</TaskExtension>"
				"<TaskExtension>"
					"<Name>%s Tech Support</Name>"
					"<URL>%s</URL>"
					"<Type>Browser</Type>"
				"</TaskExtension>"
				"<TaskExtension>"
					"<Name>Reboot router</Name>"
					"<URL>/restart.cgi</URL>"
					"<Type>Silent</Type>"
				"</TaskExtension>"
			"</Tasks>"
		"</GetDeviceSettingsResponse>"
	"</soap:Body>"
"</soap:Envelope>";

char *reboot_result =
"<?xml version=\"1.0\" encoding=\"utf-8\"?>"
"<soap:Envelope xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\" "
	       "xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\" "
	       "xmlns:soap=\"http://schemas.xmlsoap.org/soap/envelope/\">"
	"<soap:Body>"
		"<RebootResponse xmlns=\"http://purenetworks.com/HNAP1/\">"
			"<RebootResult>REBOOT</RebootResult>"
		"</RebootResponse>"
	"</soap:Body>"
"</soap:Envelope>";

char *getrouter_lansettings_result =
"<?xml version=\"1.0\" encoding=\"utf-8\"?>"
"<soap:Envelope xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\" "
	       "xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\" "
	       "xmlns:soap=\"http://schemas.xmlsoap.org/soap/envelope/\">"
	"<soap:Body>"
		"<GetRouterLanSettingsResponse xmlns=\"http://purenetworks.com/HNAP1/\">"
			"<GetRouterLanSettingsResult>OK</GetRouterLanSettingsResult>"
			"<RouterIPAddress>%s</RouterIPAddress>"
			"<RouterSubnetMask>%s</RouterSubnetMask>"
			"<DHCPServerEnabled>%s</DHCPServerEnabled>"
		"</GetRouterLanSettingsResponse>"
	"</soap:Body>"
"</soap:Envelope>";

char *setdevice_settings_result = 
"<?xml version=\"1.0\" encoding=\"utf-8\"?>"
"<soap:Envelope xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\" "
	       "xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\" "
	       "xmlns:soap=\"http://schemas.xmlsoap.org/soap/envelope/\">"
	"<soap:Body>"
		"<SetDeviceSettingsResponse xmlns=\"http://purenetworks.com/HNAP1/\">"
			"<SetDeviceSettingsResult>OK</SetDeviceSettingsResult>"
		"</SetDeviceSettingsResponse>"
	"</soap:Body>"
"</soap:Envelope>";

char *setrouter_lansettings_result =
"<?xml version=\"1.0\" encoding=\"utf-8\"?>"
"<soap:Envelope xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\" "
	       "xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\" "
	       "xmlns:soap=\"http://schemas.xmlsoap.org/soap/envelope/\">"
	"<soap:Body>"
		"<SetRouterLanSettingsResponse xmlns=\"http://purenetworks.com/HNAP1/\">"        
			"<SetRouterLanSettingsResult>%s</SetRouterLanSettingsResult>"                    
		"</SetRouterLanSettingsResponse>"
	"</soap:Body>"
"</soap:Envelope>";

char *get_wlan_setting24_result = 
"<?xml version=\"1.0\" encoding=\"utf-8\"?>"
"<soap:Envelope xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\" "
	       "xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\" "
	       "xmlns:soap=\"http://schemas.xmlsoap.org/soap/envelope/\">"
	"<soap:Body>"
		"<GetWLanSettings24Response xmlns=\"http://purenetworks.com/HNAP1/\">"
			"<GetWLanSettings24Result>OK</GetWLanSettings24Result>"
			"<Enabled>%s</Enabled>"
			"<MacAddress>%s</MacAddress>"
			"<SSID>%s</SSID>"
			"<SSIDBroadcast>%s</SSIDBroadcast>"
			"<Channel>%s</Channel>"
		"</GetWLanSettings24Response>"
	"</soap:Body>"
"</soap:Envelope>";

char *set_wlan_setting24_result = 
"<?xml version=\"1.0\" encoding=\"utf-8\"?>"
"<soap:Envelope xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\" "
	       "xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\" "
	       "xmlns:soap=\"http://schemas.xmlsoap.org/soap/envelope/\">"
	"<soap:Body>"
		"<SetWLanSettings24Response xmlns=\"http://purenetworks.com/HNAP1/\">"
			"<SetWLanSettings24Result>OK</SetWLanSettings24Result>"
		"</SetWLanSettings24Response>"
	"</soap:Body>"
"</soap:Envelope>";

char *get_wlan_security_result = 
"<?xml version=\"1.0\" encoding=\"utf-8\"?>"
"<soap:Envelope xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\" "
		"xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\" "
		"xmlns:soap=\"http://schemas.xmlsoap.org/soap/envelope/\">"
	"<soap:Body>"
		"<GetWLanSecurityResponse xmlns=\"http://purenetworks.com/HNAP1/\">"
			"<GetWLanSecurityResult>%s</GetWLanSecurityResult>"
			"<Enabled>%s</Enabled>"
			"<Type>%s</Type>"
			"<WEPKeyBits>%s</WEPKeyBits>"
			"<SupportedWEPKeyBits>"
				"<int>64</int>"
				"<int>128</int>"
				"<int>152</int>"
			"</SupportedWEPKeyBits>"
			"<Key>%s</Key>"
			"<RadiusIP1>%s</RadiusIP1>"
			"<RadiusPort1>%s</RadiusPort1>"
			"<RadiusIP2>%s</RadiusIP2>"
			"<RadiusPort2>%s</RadiusPort2>"
		"</GetWLanSecurityResponse>"
	"</soap:Body>"
"</soap:Envelope>";

char *set_wlan_security_result = 
"<?xml version=\"1.0\" encoding=\"utf-8\"?>"
	"<soap:Envelope xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\" "
			"xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\" "
			"xmlns:soap=\"http://schemas.xmlsoap.org/soap/envelope/\">"
	"<soap:Body>"
		"<SetWLanSecurityResponse xmlns=\"http://purenetworks.com/HNAP1/\">"
			"<SetWLanSecurityResult>REBOOT</SetWLanSecurityResult>"
		"</SetWLanSecurityResponse>"
	"</soap:Body>"
"</soap:Envelope>";

char *WideChannels_24GHZ =
"<WideChannel>"
	"<Channel>3</Channel>"
	"<SecondaryChannels>"
		"<int>1</int>"
		"<int>5</int>"
	"</SecondaryChannels>"
"</WideChannel>"
"<WideChannel>"
	"<Channel>4</Channel>"
	"<SecondaryChannels>"
		"<int>2</int>"
		"<int>6</int>"
	"</SecondaryChannels>"
"</WideChannel>"
"<WideChannel>"
	"<Channel>5</Channel>"
	"<SecondaryChannels>"
		"<int>3</int>"
		"<int>7</int>"
	"</SecondaryChannels>"
"</WideChannel>"
"<WideChannel>"
	"<Channel>6</Channel>"
	"<SecondaryChannels>"
		"<int>4</int>"
		"<int>8</int>"
	"</SecondaryChannels>"
"</WideChannel>"
"<WideChannel>"
	"<Channel>7</Channel>"
	"<SecondaryChannels>"
		"<int>5</int>"
		"<int>9</int>"
	"</SecondaryChannels>"
"</WideChannel>"
"<WideChannel>"
	"<Channel>8</Channel>"
	"<SecondaryChannels>"
		"<int>6</int>"
		"<int>10</int>"
	"</SecondaryChannels>"
"</WideChannel>"
"<WideChannel>"
	"<Channel>9</Channel>"
	"<SecondaryChannels>"
		"<int>7</int>"
		"<int>11</int>"
	"</SecondaryChannels>"
"</WideChannel>";

char *SecurityInfo =
"<SecurityInfo>"
	"<SecurityType>WEP-OPEN</SecurityType>"
	"<Encryptions>"
		"<string>WEP-64</string>"
		"<string>WEP-128</string>"
	"</Encryptions>"
"</SecurityInfo>"
"<SecurityInfo>"
	"<SecurityType>WEP-SHARED</SecurityType>"
	"<Encryptions>"
		"<string>WEP-64</string>"
		"<string>WEP-128</string>"
	"</Encryptions>"
"</SecurityInfo>"
"<SecurityInfo>"
	"<SecurityType>WPA-PSK</SecurityType>"
	"<Encryptions>"
		"<string>TKIP</string>"
	"</Encryptions>"
"</SecurityInfo>"
"<SecurityInfo>"
	"<SecurityType>WPA-RADIUS</SecurityType>"
	"<Encryptions>"
		"<string>TKIP</string>"
	"</Encryptions>"
"</SecurityInfo>"
"<SecurityInfo>"
	"<SecurityType>WPA2-PSK</SecurityType>"
	"<Encryptions>"
		"<string>TKIP</string>"
		"<string>AES</string>"
		"<string>TKIPORAES</string>"
	"</Encryptions>"
"</SecurityInfo>"
"<SecurityInfo>"
	"<SecurityType>WPA2-RADIUS</SecurityType>"
	"<Encryptions>"
		"<string>TKIP</string>"
		"<string>AES</string>"
		"<string>TKIPORAES</string>"
	"</Encryptions>"
"</SecurityInfo>";



char *RadioInfo_24GHZ =
"<RadioID %s>RADIO_24GHz</RadioID>"
"<Frequency %s>2</Frequency>"
"<SupportedModes %s>"
	"<string>802.11b</string>"
	"<string>802.11g</string>"
	"<string>802.11n</string>"
	"<string>802.11bg</string>"
	"<string>802.11gn</string>"
	"<string>802.11bgn</string>"
"</SupportedModes>"
"<Channels %s>%s</Channels>"
"<WideChannels %s>%s</WideChannels>"
"<SupportedSecurity %s>%s</SupportedSecurity>"
;

char *get_wlan_radio_settings_result =
	"<?xml version=\"1.0\" encoding=\"UTF-8\"?>"
		"<soap:Envelope xmlns:soap=\"http://schemas.xmlsoap.org/soap/envelope/\" "
			"soap:encodingStyle=\"http://schemas.xmlsoap.org/soap/encoding/\">"
	"<soap:Body>"
		"<GetWLanRadioSettingsResponse xmlns=\"http://purenetworks.com/HNAP1/\">"
			"<GetWLanRadioSettingsResult>%s</GetWLanRadioSettingsResult>"
			"<Enabled>%s</Enabled>"
			"<Mode>%s</Mode>"
			"<MacAddress>%s</MacAddress>"
			"<SSID>%s</SSID>"
			"<SSIDBroadcast>%s</SSIDBroadcast>"
			"<ChannelWidth>%s</ChannelWidth>"
			"<Channel>%s</Channel>"
			"<SecondaryChannel>%s</SecondaryChannel>" //not configured in 40 MHz channel width => return zero
			"<QoS>%s</QoS>"
		"</GetWLanRadioSettingsResponse>"
	"</soap:Body>"
"</soap:Envelope>"
;


char *get_wlan_radios_result =
"<?xml version=\"1.0\" encoding=\"utf-8\"?>"
	"<soap:Envelope xmlns:soap=\"http://schemas.xmlsoap.org/soap/envelope/\" "
			"soap:encodingStyle=\"http://schemas.xmlsoap.org/soap/encoding/\">"
		"<soap:Body>"
			"<GetWLanRadiosResponse xmlns=\"http://purenetworks.com/HNAP1/\">"
				"<GetWLanRadiosResult>%s</GetWLanRadiosResult>"
				"<RadioInfos>"
					"%s"	
				"</RadioInfos>"
		"</GetWLanRadiosResponse>"
	"</soap:Body>"
"</soap:Envelope>";

char *set_wlan_radio_settings_result =
"<?xml version=\"1.0\" encoding=\"utf-8\"?>"
"<soap:Envelope xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\" "
		"xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\" "
		"xmlns:soap=\"http://schemas.xmlsoap.org/soap/envelope/\">"
	"<soap:Body>"
		"<SetWLanRadioSettingsResponse xmlns=\"http://purenetworks.com/HNAP1/\">"
			"<SetWLanRadioSettingsResult>OK</SetWLanRadioSettingsResult>"
		"</SetWLanRadioSettingsResponse>"
	"</soap:Body>"
"</soap:Envelope>";

char *get_wlan_radio_security_result =
"<?xml version=\"1.0\" encoding=\"utf-8\"?>"
	"<soap:Envelope xmlns:soap=\"http://schemas.xmlsoap.org/soap/envelope/\" "
			"soap:encodingStyle=\"http://schemas.xmlsoap.org/soap/encoding/\">"
	"<soap:Body>"
		"<GetWLanRadioSecurityResponse xmlns=\"http://purenetworks.com/HNAP1/\">"
			"<GetWLanRadioSecurityResult>%s</GetWLanRadioSecurityResult>"
			"<Enabled>%s</Enabled>"
			"<Type>%s</Type>"
			"<Encryption>%s</Encryption>"
			"<Key>%s</Key>"
			"<KeyRenewal>%s</KeyRenewal>"
			"<RadiusIP1>%s</RadiusIP1>"
			"<RadiusPort1>%s</RadiusPort1>"
			"<RadiusSecret1>%s</RadiusSecret1>"
			"<RadiusIP2>%s</RadiusIP2>"
			"<RadiusPort2>%s</RadiusPort2>"
			"<RadiusSecret2>%s</RadiusSecret2>"
		"</GetWLanRadioSecurityResponse>"
	"</soap:Body>"
"</soap:Envelope>";

char *set_wLan_radio_security_result =
"<?xml version=\"1.0\" encoding=\"utf-8\"?>"
	"<soap:Envelope xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\" "
			"xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\" xmlns:soap=\"http://schemas.xmlsoap.org/soap/envelope/\">"
	"<soap:Body>"
		"<SetWLanRadioSecurityResponse xmlns=\"http://purenetworks.com/HNAP1/\">"
			"<SetWLanRadioSecurityResult>OK</SetWLanRadioSecurityResult>"
		"</SetWLanRadioSecurityResponse>"
	"</soap:Body>"
"</soap:Envelope>";


char *get_wan_settings_result =
"<?xml version=\"1.0\" encoding=\"utf-8\"?>"
	"<soap:Envelope xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\" "
			"xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\" "
			"xmlns:soap=\"http://schemas.xmlsoap.org/soap/envelope/\">"
	"<soap:Body>"
		"<GetWanSettingsResponse xmlns=\"http://purenetworks.com/HNAP1/\">"
			"<GetWanSettingsResult>%s</GetWanSettingsResult>"
			"<Type>%s</Type>"
			"<Username>%s</Username>"
			"<Password>%s</Password>"
			"<MaxIdleTime>%s</MaxIdleTime>"
			"<ServiceName>%s</ServiceName>"
			"<AutoReconnect>%s</AutoReconnect>"
			"<IPAddress>%s</IPAddress>"	
			"<SubnetMask>%s</SubnetMask>"
			"<Gateway>%s</Gateway>"
			"<DNS>"
				"<Primary>%s</Primary>"
				"<Secondary>%s</Secondary>"
			"</DNS>"
#ifdef OPENDNS
			"<OpenDNS>"
				"<enable>%s</enable>"
			"</OpenDNS>"
#endif
			"<MacAddress>%s</MacAddress>"
			"<MTU>%s</MTU>"
		"</GetWanSettingsResponse>"
	"</soap:Body>"
"</soap:Envelope>";

char *set_wan_settings_result = 
"<?xml version=\"1.0\" encoding=\"utf-8\"?>"
	"<soap:Envelope xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\" "
			"xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\" "
			"xmlns:soap=\"http://schemas.xmlsoap.org/soap/envelope/\">"
	"<soap:Body>"
		"<SetWanSettingsResponse xmlns=\"http://purenetworks.com/HNAP1/\">"
			"<SetWanSettingsResult>%s</SetWanSettingsResult>"
		"</SetWanSettingsResponse>"
	"</soap:Body>"
"</soap:Envelope>";

char *renew_wan_connection_result =
"<?xml version=\"1.0\" encoding=\"utf-8\"?>"
	"<soap:Envelope xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\" "
			"xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\" xmlns:soap=\"http://schemas.xmlsoap.org/soap/envelope/\">"
	"<soap:Body>"
		"<RenewWanConnectionResponse xmlns=\"http://purenetworks.com/HNAP1/\">"
		"<RenewWanConnectionResult>%s</RenewWanConnectionResult>"
		"</RenewWanConnectionResponse>"
	"</soap:Body>"
"</soap:Envelope>";


char *get_port_mappings_result =
"<?xml version=\"1.0\" encoding=\"utf-8\"?>"
	"<soap:Envelope xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\" "
			"xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\" xmlns:soap=\"http://schemas.xmlsoap.org/soap/envelope/\">"
	"<soap:Body>"
		"<GetPortMappingsResponse xmlns=\"http://purenetworks.com/HNAP1/\">"
			"<GetPortMappingsResult>%s</GetPortMappingsResult>"
			"<PortMappings>"
				"%s"
			"</PortMappings>"
		"</GetPortMappingsResponse>"
	"</soap:Body>"
"</soap:Envelope>";


char *port_mapping_result =
"<PortMapping>"
	"<PortMappingDescription>%s</PortMappingDescription>"
	"<InternalClient>%s</InternalClient>"
	"<PortMappingProtocol>%s</PortMappingProtocol>"
	"<ExternalPort>%s</ExternalPort>"
	"<InternalPort>%s</InternalPort>"
"</PortMapping>";

char *add_port_mapping_result =
"<?xml version=\"1.0\" encoding=\"utf-8\"?>"
	"<soap:Envelope xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\" "
			"xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\" "
			"xmlns:soap=\"http://schemas.xmlsoap.org/soap/envelope/\">"
	"<soap:Body>"
		"<AddPortMappingResponse xmlns=\"http://purenetworks.com/HNAP1/\">"
			"<AddPortMappingResult>%s</AddPortMappingResult>"
		"</AddPortMappingResponse>"
	"</soap:Body>"
"</soap:Envelope>";


char *delete_port_mapping_result =
"<?xml version=\"1.0\" encoding=\"utf-8\"?>"
	"<soap:Envelope xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\" "
			"xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\" "
			"xmlns:soap=\"http://schemas.xmlsoap.org/soap/envelope/\">"
	"<soap:Body>"
		"<DeletePortMappingResponse xmlns=\"http://purenetworks.com/HNAP1/\">"
		"<DeletePortMappingResult>%s</DeletePortMappingResult>"
		"</DeletePortMappingResponse>"
	"</soap:Body>"
"</soap:Envelope>";

char *get_macfilters2_result =
"<?xml version=\"1.0\" encoding=\"utf-8\"?>"
	"<soap:Envelope xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\" "
			"xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\" "
			"xmlns:soap=\"http://schemas.xmlsoap.org/soap/envelope/\">"
	"<soap:Body>"
		"<GetMACFilters2Response xmlns=\"http://purenetworks.com/HNAP1/\">"
			"<GetMACFilters2Result>%s</GetMACFilters2Result>"
			"<Enabled>%s</Enabled>"
			"<IsAllowList>%s</IsAllowList>"
			"<MACList>%s</MACList>"
		"</GetMACFilters2Response>"
	"</soap:Body>"
"</soap:Envelope>";

char *set_macfilters2_result =
"<?xml version=\"1.0\" encoding=\"utf-8\"?>"
	"<soap:Envelope xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\" "
			"xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\" "
			"xmlns:soap=\"http://schemas.xmlsoap.org/soap/envelope/\">"
	"<soap:Body>"
		"<SetMACFilters2Response xmlns=\"http://purenetworks.com/HNAP1/\">"
		"<SetMACFilters2Result>%s</SetMACFilters2Result>"
		"</SetMACFilters2Response>"
	"</soap:Body>"
"</soap:Envelope>";

char *mac_info =
"<MACInfo>"
        "<MacAddress>%s</MacAddress>"
        "<DeviceName>%s</DeviceName>"
"</MACInfo>";

char *get_connected_devices_result =
"<?xml version=\"1.0\" encoding=\"utf-8\"?>"
	"<soap:Envelope xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\" "
			"xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\" "
			"xmlns:soap=\"http://schemas.xmlsoap.org/soap/envelope/\">"
	"<soap:Body>"
		"<GetConnectedDevicesResponse xmlns=\"http://purenetworks.com/HNAP1/\">"
			"<GetConnectedDevicesResult>%s</GetConnectedDevicesResult>"
			"<ConnectedClients>"
				"%s"
			"</ConnectedClients>"
		"</GetConnectedDevicesResponse>"
	"</soap:Body>"
"</soap:Envelope>";

char *cnted_client =
"<ConnectedClient>"
	"<ConnectTime>%s</ConnectTime>"
	"<MacAddress>%s</MacAddress>"
	"<DeviceName>%s</DeviceName>"
	"<PortName>%s</PortName>"
	"<Wireless>%s</Wireless>"
	"<Active>%s</Active>"
"</ConnectedClient>";

char *get_network_stats_result =
"<?xml version=\"1.0\" encoding=\"utf-8\"?>"
	"<soap:Envelope xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\" "
			"xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\" "
			"xmlns:soap=\"http://schemas.xmlsoap.org/soap/envelope/\">"
	"<soap:Body>"
		"<GetNetworkStatsResponse xmlns=\"http://purenetworks.com/HNAP1/\">"
			"<GetNetworkStatsResult>OK</GetNetworkStatsResult>"
			"<Stats>"
				"<NetworkStats>"
					"<PortName>LAN</PortName>"
					"<PacketsReceived>%s</PacketsReceived>"
					"<PacketsSent>%s</PacketsSent>"
					"<BytesReceived>%s</BytesReceived>"
					"<BytesSent>%s</BytesSent>"
				"</NetworkStats>"
				"<NetworkStats>"
					"<PortName>WLAN 802.11g</PortName>"
					"<PacketsReceived>%s</PacketsReceived>"
					"<PacketsSent>%s</PacketsSent>"
					"<BytesReceived>%s</BytesReceived>"
					"<BytesSent>%s</BytesSent>"
				"</NetworkStats>"
			"</Stats>"
		"</GetNetworkStatsResponse>"
	"</soap:Body>"
"</soap:Envelope>";

