OBJS=utility_cmds.o utility_ipsec.o utility_openvpn.o utility_dns.o utility_pppd.o utility_vpn_mtime.o utility_dump.o utility_wclient.o vct.o
OBJS=utility_cmds.o utility_ipsec.o utility_vpn_mtime.o utility_pppd.o utility_openvpn.o

include ../Rules.make
